//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CARAPREV.rc
//
#define IDR_PREVIEW_CONTEXTMENU         101
#define IDB_TREE_IMAGES                 102
#define IDD_MENUBAR                     103
#define IDD_LISTDLG                     108
#define IDD_TREEDLG                     109
#define IDD_PREVIEW_DLG_BAR             110
#define IDI_PRT_SETUP                   112
#define IDI_PRINT                       113
#define IDI_ZOOM_OUT                    114
#define IDI_PREVIEW_CLOSE               116
#define IDI_ZOOM_IN                     117
#define IDR_EDIT_CURVE_VALUE_MENU       118
#define IDR_STATUSBAR_MENU              119
#define IDC_COPYCURSOR                  120
#define IDC_NODROPCURSOR                121
#define IDC_EDITCURSOR                  122
#define IDC_TRACKCURSOR                 123
#define IDC_OPENHANDCURSOR              124
#define IDC_ZOOMCURSOR                  125
#define IDC_CREATE_LINE                 126
#define IDC_CREATE_RECT                 127
#define IDC_CREATE_BEZIER               128
#define IDR_MAINFRAME                   128
#define IDC_CREATE_CIRCLE               129
#define IDC_CREATE_TEXT                 130
#define IDC_TRACKCURVE                  131
#define IDC_TRACKPLOT                   132
#define IDC_COPYPLOT                    133
#define IDC_COPYCURVE                   134
#define IDC_NODROPPLOT                  135
#define IDC_NODROPCURVE                 136
#define IDC_CREATE_BCIRCLE              137
#define IDR_PREVIEWBAR                  140
#define IDR_PREVIEWACCELERATORS         141
#define IDB_CARALOGO                    142
#define IDB_BULLET                      143
#define IDD_PASTE_SELECTIV              152
#define IDD_CATCH_GRID                  153
#define IDD_PROPPAGE_LINE               170
#define IDD_PROPPAGE_BRUSH              171
#define IDD_PROPPAGE_CURVE              172
#define IDD_PROPPAGE_FONT               173
#define IDD_PROPPAGE_PLOTRANGE          174
#define IDD_PROPPAGE_PLOTVIEW           175
#define IDD_PROPPAGE_CURVE_COLORS       176
#define IDD_PROPPAGE_DIBLABEL           177
#define IDD_PROPPAGE_COLORSCALE         230
#define IDD_TEXTDLG                     231
#define TBS_TOOLTIPS                    0x0100
#define IDC_PREVIEWSTD                  1000
#define IDC_FONT_FONT                   1001
#define IDC_FONT_HEIGHT                 1002
#define IDC_FONT_WIDTH                  1003
#define IDC_FONT_WEIGHT                 1004
#define IDC_FONT_EXTRASPACE             1005
#define IDC_FONT_CURSIV                 1006
#define IDC_FONT_UNDERLINE              1007
#define IDC_FONT_ALIGN_H                1008
#define IDC_FONT_ALIGN_V                1009
#define IDC_FONT_LINE                   1010
#define IDC_FONT_BKGNDCOLOR             1011
#define IDC_FONT_TEXTCOLOR              1012
#define IDC_FONT_BKGND                  1013
#define IDC_FONT_ZOOM0                  1014
#define IDC_FONT_ZOOM1                  1015
#define IDC_FONT_ZOOM2                  1016
#define IDC_FONT_ZOOM4                  1017
#define IDC_FONT_ZOOM3                  1018
#define IDC_FRAME_LINECOLOR             1020
#define IDC_FRAME_LINESTYLE             1021
#define IDC_FRAME_LINEWIDTH             1022
#define IDC_FRAME_LINEWIDTH_SPIN        1023
#define IDC_TEXTEDIT                    1025
#define IDC_TEXT_CALCRECT               1026
#define IDC_BRUSH_COLOR                 1030
#define IDC_BRUSH_STYLE                 1031
#define IDC_BRUSH_BKGNDCOLOR            1032
#define IDC_BRUSH_BITMAP                1033
#define IDC_PLT_CURVETEXTFRAME          1040
#define IDC_PLT_SHOWGRID_X              1041
#define IDC_PLT_SHOWGRID_Y              1042
#define IDC_PLT_SHOWTEXT_X              1043
#define IDC_PLT_SHOWTEXT_Y              1044
#define IDC_PLT_XDIVLIN                 1046
#define IDC_PLT_XDIVLOG                 1047
#define IDC_PLT_XDIVFRQ                 1048
#define IDC_PLT_YDIVLIN                 1049
#define IDC_PLT_YDIVLOG                 1050
#define IDC_PLT_YDIVFRQ                 1051
#define IDC_PLT_HEADINGFONT             1058
#define IDC_PLT_GRID_FONT               1059
#define IDC_PLT_NUM_REP_X               1060
#define IDC_PLT_NUM_REP_Y               1061
#define IDC_PLT_GRIDCOLOR               1062
#define IDC_PLT_GRIDSTEPY               1063
#define IDC_PLT_GRIDSTEPX               1064
#define IDC_PLT_X_Y_DIAG                1065
#define IDC_PLT_POLAR                   1066
#define IDC_PLT_RANGEX1                 1070
#define IDC_PLT_RANGEX2                 1071
#define IDC_PLT_RANGEY1                 1072
#define IDC_PLT_RANGEY2                 1073
#define IDC_PLT_UNITX                   1074
#define IDC_PLT_UNITY                   1075
#define IDC_PLT_PLOTHEADING             1076
#define IDC_PLT_SETDEFAULTRANGE         1077
#define IDC_PLT_DETERMINRANGE           1078
#define IDC_PASTESEL_FORMAT0            1081
#define IDC_PASTESEL_FORMAT1            1082
#define IDC_PASTESEL_FORMAT2            1083
#define IDC_PASTESEL_FORMAT3            1084
#define IDC_PICT_SCALING0               1090
#define IDC_PICT_SCALING1               1091
#define IDC_PICT_SCALING2               1092
#define IDC_PICT_OUTPUT0                1093
#define IDC_PICT_SHINY                  1095
#define IDC_PICT_HALFTONE               1096
#define IDC_PICT_FILE                   1097
#define IDC_PICT_FILENAME               1098
#define IDC_CSCALE_FONT                 1100
#define IDC_CSCALE_SHOWTEXT             1101
#define IDC_CSCALE_NUM_REP              1102
#define IDC_CSCALE_STEPWIDTH            1106
#define IDC_CURVECOLOR_BKGND            1110
#define IDC_CURVECOLOR1                 1111
#define IDC_CURVECOLOR2                 1112
#define IDC_CURVECOLOR3                 1113
#define IDC_CURVECOLOR4                 1114
#define IDC_CURVECOLOR5                 1115
#define IDC_CURVECOLOR6                 1116
#define IDC_CURVECOLOR7                 1117
#define IDC_CURVECOLOR8                 1118
#define IDC_CURVECOLOR9                 1119
#define IDC_CURVECOLOR10                1120
#define IDC_CURVECOLOR11                1121
#define IDC_CURVECOLOR12                1122
#define IDC_CURVECOLOR13                1123
#define IDC_CURVECOLOR14                1124
#define IDC_CURVECOLOR15                1125
#define IDC_CURVECOLOR16                1126
#define IDC_LST_LIST                    1130
#define IDC_TREE_TREECTRL               1131
#define IDC_CATCHGRID_ORG_X             1132
#define IDC_CATCHGRID_ORG_Y             1133
#define IDC_CATCHGRID_STEP_X            1134
#define IDC_CATCHGRID_STEP_Y            1135
#define IDC_CURVE_UNIT_X                1140
#define IDC_CURVE_UNIT_Y                1141
#define IDC_CURVE_VALUE_Y               1142
#define IDC_CURVE_VALUE_X               1143
#define IDC_CURVE_INDEX                 1144
#define IDC_CURVE_INDEX_SPIN            1145
#define IDC_CURVE_LIST                  1146
#define IDC_CURVE_WIDTH                 1147
#define IDC_CURVE_COLOR                 1148
#define IDC_CURVE_FONT                  1149
#define IDC_CURVE_UNIT_LOCUS            1149
#define IDC_CURVE_EDITABLE              1150
#define IDC_CURVE_EDITMODE2             1151
#define IDC_CURVE_EDITMODE1             1152
#define IDC_CURVE_VISIBLE               1153
#define IDC_CURVE_OFFSETY               1154
#define IDC_CURVE_ORIGIN                1155
#define IDC_CURVE_WIDTH_SPIN            1156
#define IDC_CURVE_STEP                  1157
#define IDC_CURVE_END                   1158
#define IDC_CURVE_TAB                   1160
#define IDC_CURVE_FORMAT                1161
#define IDC_CURVE_INDEX_TXT             1162
#define IDC_CURVE_VALUE_X_TXT           1163
#define IDC_CURVE_VALUE_Y_TXT           1164
#define IDC_CURVE_FORMAT_TXT            1165
#define IDC_CURVE_ORIGIN_TXT            1166
#define IDC_CURVE_STEP_TXT              1167
#define IDC_CURVE_OFFSETY_TXT           1168
#define IDC_CURVE_UNIT_X_TXT            1169
#define IDC_CURVE_UNIT_Y_TXT            1170
#define IDC_CURVE_UNIT_LOCUS_TXT        1171
#define IDC_CURVE_WIDTH_TXT             1172
#define IDC_CURVE_END_TXT               1173
#define IDC_CURVE_VALUE_LIST            1176
#define IDC_COMBO_SCATTER               1178
#define ID_EDIT_PASTE_SELECTIV          32780
#define ID_VIEW_TB                      32790
#define ID_VIEW_TB1                     32791
#define ID_VIEW_TB_TOP                  32792
#define ID_VIEW_TB_BOTTOM               32793
#define ID_VIEW_TB1_LEFT                32794
#define ID_VIEW_TB1_RIGHT               32795
#define ID_VIEW_TB1_TOP                 32796
#define ID_VIEW_TB1_BOTTOM              32797
#define ID_VIEW_PRINTER_COLORS          32798
#define ID_VIEW_FOREGROUND              32799
#define ID_OPTIONS_PICK                 32800
#define ID_OPTIONS_LINE                 32801
#define ID_OPTIONS_CIRCLE               32802
#define ID_OPTIONS_RECT                 32803
#define ID_OPTIONS_BEZIER               32804
#define ID_OPTIONS_TEXT                 32805
#define ID_OPTIONS_GRID                 32806
#define ID_FUNC_PICK                    32810
#define ID_FUNC_LINE                    32811
#define ID_FUNC_CIRCLE                  32812
#define ID_FUNC_RECTANGLE               32813
#define ID_FUNC_BEZIER                  32814
#define ID_FUNC_TEXT                    32815
#define ID_FUNC_UP                      32820
#define ID_FUNC_DOWN                    32821
#define ID_FUNC_HIGHEST                 32822
#define ID_FUNC_GROUP                   32823
#define ID_FUNC_UNGROUP                 32824
#define ID_FUNC_LOWEST                  32825
#define ID_FUNC_CATCH_GRID              32826
#define ID_FUNC_BEZIERCIRCLE            32827
#define IDX_HEAPWATCH                   32830
#define IDX_NO_LOGO                     32831
#define IDX_CONTEXT_MENU                32832
#define IDX_SHOW_LABELSTRUCTURE         32833
#define IDX_ADD_PAGE                    32834
#define IDX_REMOVE_PAGE                 32835
#define ID_VIEW_MENU                    32842
#define ID_PLOT_UNITS                   32843
#define ID_PLOT_GRIDLINES               32844
#define ID_PLOT_GRIDTEXT                32845
#define ID_PLOT_HEADING                 32846
#define ID_PLOT_CURVETEXT               32847
#define ID_VIEW_BALOON_TOOLTIPS         32847
#define ID_PLOT_PLOT                    32848
#define ID_HELP_SHORTCUTS               32849
#define IDM_EDIT_CURVE_VALUEX           32850
#define IDM_EDIT_CURVE_VALUEY           32851
#define IDM_DELETE_CURVE_VALUE          32852
#define IDM_INSERT_CURVE_VALUE          32853
#define IDS_PROPERTY_PLOT               50001
#define IDS_PROPERTY_RECTANGLE          50002
#define IDS_PROPERTY_BEZIER             50003
#define IDS_PROPERTY_CIRCLE             50004
#define IDS_PROPERTY_TEXT               50005
#define IDS_PROPERTY_PLOT_STD           50006
#define IDS_PROPERTIES                  50007
#define IDS_PROPERTY_CURVE              50008
#define IDS_PROPERTY_LINES              50009
#define IDS_STANDARD_PROPERTIES         50010
#define IDS_SELECT_ZOOMRANGE            50011
#define IDS_REQUEST_DELETE_RANGE        50012
#define IDS_PLOT_FROM                   50013
#define IDS_PLOT_TO                     50014
#define IDS_COLOR_OF_CURVE              50015
#define IDS_BACKGROUNDCOLOR             50020
#define IDS_CURVECOLOR                  50021
#define IDS_HEADINGFONT                 50022
#define IDS_GRIDCOLOR                   50023
#define IDS_GRIDFONT                    50024
#define IDS_CURVEFONT                   50025
#define IDS_LINECOLOR                   50026
#define IDS_BRUSHCOLOR                  50027
#define IDS_BKCOLOR                     50028
#define IDS_TEXTCOLOR                   50029
#define IDS_SAVE_CHANGES                50030
#define IDS_SCALEFONT                   50031
#define IDS_CANCEL                      50032
#define IDE_RANGE_TOO_SMALL             50050
#define IDE_DEFAULT_RANGE_ERROR         50051
#define IDS_PRINTPARAMS_CHANGED         50052
#define IDS_FORMAT_LARGE_MEM_REQUEST    50053
#define IDS_WARNING                     50054
#define IDS_PROPERTY_PICTURE            50055
#define IDS_PICKCOLOR                   50059
#define IDS_CRC_EXCEPTIONERROR          50061
#define IDS_CARA_BITMAP                 50062
#define IDS_NO_PICTURE                  50063
#define IDS_VERSION_EXCEPTIONERROR      50064
#define IDS_NO_PRINTER                  50065
#define IDS_PROPERTY_COLORSCALE         50066
#define IDS_PASTE_SPECIAL               50067
#define IDS_PASTEDATE_FMT               50068
#define IDS_PASTEDATE                   50069
#define IDS_PASTETIME                   50070
#define IDS_PASTEDATETIME               50071
#define IDS_PASTETIME_FMT               50072
#define IDS_PASTEDATETIME_FMT           50073
#define IDS_OPEN_DOCUMENT               50074
#define IDS_SAVE_DOCUMENT               50075
#define IDS_UNTITLED_DOCUMENT           50076
#define IDE_HEAP_EXISTS                 50077
#define IDE_HEAP_CREATION               50078
#define IDE_OUT_OF_MEMORY               50079
#define IDE_DESTRUCTION_WITHOUT_HEAP    50080
#define IDE_HEAP_FREE                   50081
#define IDE_HEAP_DESTROY                50082
#define IDE_MEMORY_LEAKS_CCURVE         50083
#define IDE_MEMORY_OBJECTS_CCURVE       50084
#define IDE_MEMORY_LEAKS_CLABEL         50085
#define IDE_MEMORY_OBJECTS_CLABEL       50086
#define IDS_LOAD_BMP                    50087
#define IDS_LIGHTVERSIONINFO            50088
#define IDS_CURVE_VALUES                50089
#define IDS_CURVE_PARAMS                50090
#define IDS_CURVE_UNITS                 50091
#define IDS_CHANGE_FORMAT_REQUEST       50092
#define IDS_CURVE_STEP_LOG              50093
#define IDS_CURVE_STEP_LIN              50094
#define IDS_CURVE_VALUE_LIST            50095
#define IDS_CURVE_LOCUS_AXIS            50096
#define IDS_OPEN_READ_ONLY_FILE         50097
#define IDS_PREVSTATUS_PANE1            50098
#define IDS_PREVSTATUS_PANE2            50099
#define IDS_STATUS_PANE0                50100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
