@rem = '
@echo off
v:\perl5\bin\perl.exe -w %0 %1 %2 %3 %4 %5 %6 %7 %8 %9
goto endofperl
@rem ';

$WrongStringIDTraced=0;

$lastID=0;
$maxIDC=0;
$maxIDR=0;
$maxStringID=0;
$maxCommandID=0;


$resourceID=0;
$resourceName="";

#
# PERL PART FOLLOWS HERE
#

	# assumes WorkSpaceDir
	# TEST only chdir ("d:/Project/SystemVerwaltung");
	
	if (-f "resource.h") {
		
		# Now replace resourceID's if necessary
		open (INFILE,"<resource.h");
		open (OFILE,">resourceTemp.h");
		print (OFILE "//generated by renumberResourceHeader\n");
		
		while (<INFILE>) {
			if (/^#define/ && !/\s\_/) {	# # exclude line with _APP.... defines
				$_ =~ s/\s+/ /g;	# merge whitespaces for the following split (including \r)
				
				($defineJunk,$resourceName,$resourceID) = split(/ /,$_,3);
				
				if (($resourceID-$lastID<100 && 	$resourceID<10000)
					|| ($resourceID-$lastID<5000 && 	$resourceID>10000)
				) {
					$resourceID = $lastID+1;
				}
				
				
				$numTabs = length($resourceName)/4;

				$myTab="";
				for ($i=8;$i>$numTabs;$i--) {
					$myTab .= "\t";
				}
				
				$lastID = $resourceID;
				
				if (   (/IDS_/ && $resourceID<25000)
					|| (/IDP_/ && $resourceID<25000)
				) {
					if ($resourceID > $maxStringID) {
						$maxStringID = $resourceID;
					}
				}
				if (   (/IDS_/ && $resourceID<10000)
					|| (/IDS_/ && $resourceID>25000)
					|| (/IDP_/ && $resourceID<10000)
					|| (/IDP_/ && $resourceID>25000)
				) {
					if ($WrongStringIDTraced == 0) {
						print ("Warning Wrong String resource <10000 or >25000\n");
						print ("Will be modified in next turn\n");
						$WrongStringIDTraced = 1;
					}
				}
				
				printf (OFILE "$defineJunk $resourceName$myTab $resourceID\n");
				
				# collect max values on the fly
				if (/IDC_/) {
					if ($lastID > $maxIDC) {
						$maxIDC = $lastID;
					}
				}
				elsif (/ID_/) {
					if ($lastID > $maxCommandID) {
						$maxCommandID = $lastID;
					}
				}
				
				# collect the maximum under 1000
				if ($resourceID<1000) {
					if ($lastID > $maxIDR) {
						$maxIDR = $lastID;
					}
				}
			}
			# special rules for max values
			elsif (/_APS_NEXT_COMMAND_VALUE/){
				printf (OFILE "#define _APS_NEXT_COMMAND_VALUE \t\t%d",$maxCommandID+1);
				print (OFILE "\t\t//generated by renumberResourceHeader\n");
			}
			elsif (/_APS_NEXT_RESOURCE_VALUE/){
				printf (OFILE "#define _APS_NEXT_RESOURCE_VALUE \t\t%d ",$maxIDR+1);
				print (OFILE "\t\t//generated by renumberResourceHeader\n");
			}
			elsif (/_APS_NEXT_CONTROL_VALUE/) {
				printf (OFILE "#define _APS_NEXT_CONTROL_VALUE \t\t%d",$maxIDC+1);
				print (OFILE "\t\t//generated by renumberResourceHeader\n");
			}
			else {
				print (OFILE "$_");
			}
		}
		
		close(OFILE);
		close(INFILE);

		# Second turn for String resources check for max String resourceID below 25000
#		print ("Renumbering String resource <10000 and >25000\n");
		printf ("MaxStringID: $maxStringID\n");
		open (INFILE,"<resourceTemp.h");
		open (OFILE,">resourceNew.h");
		while (<INFILE>) {
			if (/^#define/ && !/\s\_/) {	# # exclude line with _APP.... defines
				$_ =~ s/\s+/ /g;	# merge whitespaces for the following split (including \r)
				
				($defineJunk,$resourceName,$resourceID) = split(/ /,$_,3);
				
				if (   (/IDS_/ && $resourceID<10000)
					|| (/IDS_/ && $resourceID>25000)
					|| (/IDP_/ && $resourceID<10000)
					|| (/IDP_/ && $resourceID>25000)
				) {
					$resourceID = ++$maxStringID;
				}

				$numTabs = length($resourceName)/4;
				$myTab="";
				for ($i=8;$i>$numTabs;$i--) {
					$myTab .= "\t";
				}

				printf (OFILE "$defineJunk $resourceName$myTab $resourceID\n");
			}
			# special rules for max values
			elsif (/_APS_NEXT_COMMAND_VALUE/){
				printf (OFILE "#define _APS_NEXT_COMMAND_VALUE \t\t%d",$maxCommandID+1);
#				print (OFILE "\t\t//generated by renumberResourceHeader");
				print (OFILE "\n");
			}
			elsif (/_APS_NEXT_RESOURCE_VALUE/){
				printf (OFILE "#define _APS_NEXT_RESOURCE_VALUE \t\t%d ",$maxIDR+1);
#				print (OFILE "\t\t//generated by renumberResourceHeader");
				print (OFILE "\n");
			}
			elsif (/_APS_NEXT_CONTROL_VALUE/) {
				printf (OFILE "#define _APS_NEXT_CONTROL_VALUE \t\t%d",$maxIDC+1);
#				print (OFILE "\t\t//generated by renumberResourceHeader");
				print (OFILE "\n");
			}
			else {
				print (OFILE "$_");
			}
		}
		close(OFILE);
		close(INFILE);

	} else {
		die "resource.h not found\n";
	}

print ("DONE renumberResourceHeader\n");

__END__
:endofperl
