#if !defined(AFX_STARINTERFACE_H__86F3986A_A971_4633_97D7_352530B0BBDD__INCLUDED_)
#define AFX_STARINTERFACE_H__86F3986A_A971_4633_97D7_352530B0BBDD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CStarInterface wrapper class

class CStarInterface : public CWnd
{
protected:
	DECLARE_DYNCREATE(CStarInterface)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbaf60a5d, 0xdb16, 0x459d, { 0x97, 0x34, 0xba, 0xb5, 0xc8, 0x41, 0xed, 0x37 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetWorkIndex();
	void SetWorkIndex(short);
	CString GetBoardIndex();
	void SetBoardIndex(LPCTSTR);
	CString GetControllerDate();
	void SetControllerDate(LPCTSTR);
	CString GetControllerTime();
	void SetControllerTime(LPCTSTR);
	CString GetControllerWeek();
	void SetControllerWeek(LPCTSTR);
	CString GetFinger();
	void SetFinger(LPCTSTR);
	CString GetFingerUseFlag();
	void SetFingerUseFlag(LPCTSTR);
	CString GetHoliday();
	void SetHoliday(LPCTSTR);
	CString GetHolidayCode();
	void SetHolidayCode(LPCTSTR);
	CString GetMasterCard();
	void SetMasterCard(LPCTSTR);
	CString GetMasterFlag();
	void SetMasterFlag(LPCTSTR);
	CString GetMasterPassword();
	void SetMasterPassword(LPCTSTR);
	CString GetPassword();
	void SetPassword(LPCTSTR);
	CString GetReader();
	void SetReader(LPCTSTR);
	CString GetTimeSchedule();
	void SetTimeSchedule(LPCTSTR);
	CString GetTimeScheduleCode();
	void SetTimeScheduleCode(LPCTSTR);
	CString GetCardID();
	void SetCardID(LPCTSTR);

// Operations
public:
	BOOL CommPortOpen(LPCTSTR CommPort, short BaudRate);
	BOOL CommPortClose();
	BOOL SocketInitialize();
	BOOL SocketConnect(LPCTSTR ServerIP, short ServerPort);
	BOOL SocketClose();
	BOOL SocketReset();
	CString CardIDDownload(LPCTSTR CardID, LPCTSTR Password, LPCTSTR TimeSchedule, LPCTSTR Reader, LPCTSTR Finger);
	CString CardIDRead(LPCTSTR CardID);
	CString CardIDCount(LPCTSTR Flag);
	CString TimeScheduleDownload(LPCTSTR TimeScheduleCode, LPCTSTR TimeSchedule, LPCTSTR HolidayCode);
	CString TimeScheduleUpload(LPCTSTR TimeScheduleCode);
	CString HolidayDownload(LPCTSTR HolidayCode, LPCTSTR Holiday);
	CString HolidayUpload(LPCTSTR HolidayCode);
	CString FingerDataDownload(LPCTSTR CardID, LPCTSTR MasterFlag, LPCTSTR FingerData);
	CString FingerDataUpload(LPCTSTR CardID);
	CString FingerBatchUpload(short WorkIndex, LPCTSTR BoardType);
	CString MasterCardDownload(LPCTSTR MasterCard, LPCTSTR MasterPassword, LPCTSTR ModeFlag);
	CString MasterCardUpload();
	CString CardIDMemoryDownload(LPCTSTR MemoryCount);
	CString ModeChangeDownload(LPCTSTR Mode, LPCTSTR TimeScheduleCode);
	CString ModeUpload();
	CString OutputPortDownload(LPCTSTR OutputNo, LPCTSTR Status, LPCTSTR OperationTime);
	CString InOutputTableDownload(LPCTSTR InputNo, LPCTSTR TimeScheduleCode, LPCTSTR Output1, LPCTSTR Output2, LPCTSTR Output3, LPCTSTR Output4, LPCTSTR Output5);
	CString AntiPassbackDownload(LPCTSTR Status);
	CString AntiPassbackUpload();
	CString DuressModeDownload(LPCTSTR DuressModeKey, LPCTSTR UseFlag);
	CString CommSpeedDownload(long BPS);
	CString CommSpeedUpload();
	CString KeypadUseDownload(LPCTSTR UseFlag);
	CString KeypadUseUpload();
	CString FunctionKeyChange(LPCTSTR FunctionKey);
	CString DateTimeDownload(LPCTSTR Date, LPCTSTR Week, LPCTSTR Time);
	CString DateTimeUpload();
	CString SystemInitialize(LPCTSTR WorkIndex);
	BOOL PollingStart(short StartBoard, short EndBoard);
	BOOL PollingStop();
	BOOL BatchStart();
	BOOL BatchStop();
	CString CardIDDelete(LPCTSTR CardID);
	CString GlobalAntiPassbackDownload(LPCTSTR CardID, LPCTSTR UseFlag);
	CString FingerSRBatchUpload(short WorkIndex);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STARINTERFACE_H__86F3986A_A971_4633_97D7_352530B0BBDD__INCLUDED_)
