// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "starinterface.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CStarInterface

IMPLEMENT_DYNCREATE(CStarInterface, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CStarInterface properties

short CStarInterface::GetWorkIndex()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CStarInterface::SetWorkIndex(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

CString CStarInterface::GetBoardIndex()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetBoardIndex(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CStarInterface::GetControllerDate()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetControllerDate(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CStarInterface::GetControllerTime()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetControllerTime(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CStarInterface::GetControllerWeek()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetControllerWeek(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CStarInterface::GetFinger()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetFinger(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

CString CStarInterface::GetFingerUseFlag()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetFingerUseFlag(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

CString CStarInterface::GetHoliday()
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetHoliday(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

CString CStarInterface::GetHolidayCode()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetHolidayCode(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

CString CStarInterface::GetMasterCard()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetMasterCard(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

CString CStarInterface::GetMasterFlag()
{
	CString result;
	GetProperty(0xb, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetMasterFlag(LPCTSTR propVal)
{
	SetProperty(0xb, VT_BSTR, propVal);
}

CString CStarInterface::GetMasterPassword()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetMasterPassword(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

CString CStarInterface::GetPassword()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetPassword(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CStarInterface::GetReader()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetReader(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CStarInterface::GetTimeSchedule()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetTimeSchedule(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

CString CStarInterface::GetTimeScheduleCode()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetTimeScheduleCode(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

CString CStarInterface::GetCardID()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CStarInterface::SetCardID(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CStarInterface operations

BOOL CStarInterface::CommPortOpen(LPCTSTR CommPort, short BaudRate)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		CommPort, BaudRate);
	return result;
}

BOOL CStarInterface::CommPortClose()
{
	BOOL result;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CStarInterface::SocketInitialize()
{
	BOOL result;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CStarInterface::SocketConnect(LPCTSTR ServerIP, short ServerPort)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ServerIP, ServerPort);
	return result;
}

BOOL CStarInterface::SocketClose()
{
	BOOL result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CStarInterface::SocketReset()
{
	BOOL result;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CStarInterface::CardIDDownload(LPCTSTR CardID, LPCTSTR Password, LPCTSTR TimeSchedule, LPCTSTR Reader, LPCTSTR Finger)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID, Password, TimeSchedule, Reader, Finger);
	return result;
}

CString CStarInterface::CardIDRead(LPCTSTR CardID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID);
	return result;
}

CString CStarInterface::CardIDCount(LPCTSTR Flag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Flag);
	return result;
}

CString CStarInterface::TimeScheduleDownload(LPCTSTR TimeScheduleCode, LPCTSTR TimeSchedule, LPCTSTR HolidayCode)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		TimeScheduleCode, TimeSchedule, HolidayCode);
	return result;
}

CString CStarInterface::TimeScheduleUpload(LPCTSTR TimeScheduleCode)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		TimeScheduleCode);
	return result;
}

CString CStarInterface::HolidayDownload(LPCTSTR HolidayCode, LPCTSTR Holiday)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		HolidayCode, Holiday);
	return result;
}

CString CStarInterface::HolidayUpload(LPCTSTR HolidayCode)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		HolidayCode);
	return result;
}

CString CStarInterface::FingerDataDownload(LPCTSTR CardID, LPCTSTR MasterFlag, LPCTSTR FingerData)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID, MasterFlag, FingerData);
	return result;
}

CString CStarInterface::FingerDataUpload(LPCTSTR CardID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID);
	return result;
}

CString CStarInterface::FingerBatchUpload(short WorkIndex, LPCTSTR BoardType)
{
	CString result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WorkIndex, BoardType);
	return result;
}

CString CStarInterface::MasterCardDownload(LPCTSTR MasterCard, LPCTSTR MasterPassword, LPCTSTR ModeFlag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		MasterCard, MasterPassword, ModeFlag);
	return result;
}

CString CStarInterface::MasterCardUpload()
{
	CString result;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::CardIDMemoryDownload(LPCTSTR MemoryCount)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		MemoryCount);
	return result;
}

CString CStarInterface::ModeChangeDownload(LPCTSTR Mode, LPCTSTR TimeScheduleCode)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Mode, TimeScheduleCode);
	return result;
}

CString CStarInterface::ModeUpload()
{
	CString result;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::OutputPortDownload(LPCTSTR OutputNo, LPCTSTR Status, LPCTSTR OperationTime)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		OutputNo, Status, OperationTime);
	return result;
}

CString CStarInterface::InOutputTableDownload(LPCTSTR InputNo, LPCTSTR TimeScheduleCode, LPCTSTR Output1, LPCTSTR Output2, LPCTSTR Output3, LPCTSTR Output4, LPCTSTR Output5)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		InputNo, TimeScheduleCode, Output1, Output2, Output3, Output4, Output5);
	return result;
}

CString CStarInterface::AntiPassbackDownload(LPCTSTR Status)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Status);
	return result;
}

CString CStarInterface::AntiPassbackUpload()
{
	CString result;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::DuressModeDownload(LPCTSTR DuressModeKey, LPCTSTR UseFlag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		DuressModeKey, UseFlag);
	return result;
}

CString CStarInterface::CommSpeedDownload(long BPS)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		BPS);
	return result;
}

CString CStarInterface::CommSpeedUpload()
{
	CString result;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::KeypadUseDownload(LPCTSTR UseFlag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		UseFlag);
	return result;
}

CString CStarInterface::KeypadUseUpload()
{
	CString result;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::FunctionKeyChange(LPCTSTR FunctionKey)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		FunctionKey);
	return result;
}

CString CStarInterface::DateTimeDownload(LPCTSTR Date, LPCTSTR Week, LPCTSTR Time)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Date, Week, Time);
	return result;
}

CString CStarInterface::DateTimeUpload()
{
	CString result;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CStarInterface::SystemInitialize(LPCTSTR WorkIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WorkIndex);
	return result;
}

BOOL CStarInterface::PollingStart(short StartBoard, short EndBoard)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		StartBoard, EndBoard);
	return result;
}

BOOL CStarInterface::PollingStop()
{
	BOOL result;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CStarInterface::BatchStart()
{
	BOOL result;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CStarInterface::BatchStop()
{
	BOOL result;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CStarInterface::CardIDDelete(LPCTSTR CardID)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID);
	return result;
}

CString CStarInterface::GlobalAntiPassbackDownload(LPCTSTR CardID, LPCTSTR UseFlag)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		CardID, UseFlag);
	return result;
}

CString CStarInterface::FingerSRBatchUpload(short WorkIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		WorkIndex);
	return result;
}

void CStarInterface::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
