//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Skript1.rc
//
#define IDS_HELP1                       1
#define IDS_HELP2                       2
#define IDS_HELP3                       3
#define IDS_HELP4                       4
#define IDS_HELP5                       5
#define IDS_HELP6                       6
#define IDS_HELP7                       7
#define IDS_HELP8                       8
#define IDS_HELP9                       9
#define IDS_HELP11                      11
#define IDS_HELP12                      12
#define IDS_HELP13                      13
#define IDS_HELP14                      14
#define IDS_HELP21                      21
#define IDS_HELP22                      22
#define IDS_HELP23                      23
#define IDS_HELP31                      31
#define IDS_HELP32                      32
#define IDS_HELP33                      33
#define IDS_HELP34                      34
#define IDS_ERROR_ALPHA                 71
#define IDS_ERROR_ALPHA0                72
#define IDS_TXT_FIRSTGROUPNAME          80
#define IDS_TXT_CREATENEW               81
#define IDS_TXT_CAPTION_CREATENEW       82
#define IDS_TXT_MATEQUAL1               83
#define IDS_TXT_MATEQUAL2               84
#define IDS_TXT_MATEQUAL3               85
#define IDS_TXT_CAPTION_MATEQUAL        86
#define IDS_TXT_GRPEQUAL1               87
#define IDS_TXT_GRPEQUAL2               88
#define IDS_TXT_GRPEQUAL3               89
#define IDS_TXT_CAPTION_GRPEQUAL        90
#define IDS_TXT_ERROR_INPUT             91
#define IDS_HELP97                      97
#define IDS_HELP98                      98
#define IDS_HELP99                      99
#define IDD_DIALOGCREATE                101
#define IDD_DIALOGSELECT                102
#define IDI_ICON1                       128
#define IDB_NOBMP32                     198
#define IDB_NOBMP08                     199
#define IDB_BITMAP1                     201
#define IDB_BITMAP2                     202
#define IDB_BITMAP3                     203
#define IDB_BITMAP4                     204
#define IDB_BITMAP5                     205
#define IDB_BITMAP6                     206
#define IDB_BITMAP7                     207
#define IDB_BITMAP8                     208
#define IDB_BITMAP9                     209
#define IDB_BITMAP10                    210
#define IDB_BITMAP11                    211
#define IDB_BITMAP12                    212
#define IDB_BITMAP13                    213
#define IDB_BITMAP14                    214
#define IDB_BITMAP15                    215
#define IDB_BITMAP16                    216
#define IDB_BITMAP17                    217
#define IDB_BITMAP18                    218
#define IDB_BITMAP19                    219
#define IDB_BITMAP20                    220
#define IDB_BITMAP21                    221
#define IDB_BITMAP22                    222
#define IDB_BITMAP23                    223
#define IDB_BITMAP24                    224
#define IDB_BITMAP25                    225
#define IDB_BITMAP26                    226
#define IDB_BITMAP27                    227
#define IDB_BITMAP28                    228
#define IDB_BITMAP29                    229
#define IDB_BITMAP30                    230
#define IDB_BITMAP31                    231
#define IDB_BITMAP32                    232
#define IDB_BITMAP33                    233
#define IDB_BITMAP34                    234
#define IDB_BITMAP35                    235
#define IDB_BITMAP36                    236
#define IDB_BITMAP37                    237
#define IDB_BITMAP38                    238
#define IDB_BITMAP39                    239
#define IDB_BITMAP40                    240
#define IDB_BITMAP41                    241
#define IDB_BITMAP42                    242
#define IDB_BITMAP43                    243
#define IDB_BITMAP44                    244
#define IDB_BITMAP45                    245
#define IDB_BITMAP46                    246
#define IDB_BITMAP47                    247
#define IDB_BITMAP48                    248
#define IDB_BITMAP49                    249
#define IDB_BITMAP50                    250
#define IDB_BITMAP51                    251
#define IDB_BITMAP52                    252
#define IDB_BITMAP53                    253
#define IDB_BITMAP54                    254
#define IDB_BITMAP55                    255
#define IDB_BITMAP56                    256
#define IDB_BITMAP57                    257
#define IDB_BITMAP58                    258
#define IDB_BITMAP59                    259
#define IDB_BITMAP60                    260
#define IDB_BITMAP61                    261
#define IDB_BITMAP62                    262
#define IDB_BITMAP63                    263
#define IDB_BITMAP64                    264
#define IDB_BITMAP65                    265
#define IDB_BITMAP66                    266
#define IDB_BITMAP67                    267
#define IDB_BITMAP68                    268
#define IDB_BITMAP69                    269
#define IDB_BITMAP70                    270
#define IDB_BITMAP71                    271
#define IDB_BITMAP72                    272
#define IDB_BITMAP73                    273
#define IDB_BITMAP74                    274
#define IDB_BITMAP75                    275
#define IDB_BITMAP76                    276
#define IDB_BITMAP77                    277
#define IDB_BITMAP78                    278
#define IDB_BITMAP79                    279
#define IDB_BITMAP80                    280
#define IDB_BITMAP81                    281
#define IDB_BITMAP82                    282
#define IDB_BITMAP83                    283
#define IDB_BITMAP84                    284
#define IDB_BITMAP85                    285
#define IDB_BITMAP86                    286
#define IDC_TEXTCREATE1                 1001
#define IDC_TEXTCREATE2                 1002
#define IDC_TEXTCREATE3                 1003
#define IDC_TEXTCREATE4                 1004
#define IDC_TEXTCREATE5                 1005
#define IDC_TEXTCREATE6                 1006
#define IDC_TEXTCREATE7                 1007
#define IDC_TEXTCREATE8                 1008
#define IDC_TEXTSELECT2                 1102
#define IDC_TEXTSELECT3                 1103
#define IDC_TEXTSELECT4                 1104
#define IDC_TEXTSELECT8                 1108
#define IDC_TEXTCREATE2_1               2001
#define IDC_EDITCREATE2                 2002
#define IDC_EDITCREATE3                 2003
#define IDC_EDITCREATE5                 2005
#define IDC_TEXTCREATE2_7               2007
#define IDC_EDITCREATE8                 2008
#define IDC_TEXTSELECT2_2               2102
#define IDC_TEXTSELECT2_3               2103
#define IDC_TEXTSELECT2_8               2108
#define IDC_BILDCREATE4                 3004
#define IDC_BILDSELECT4                 3104
#define IDC_MAT_ABSPT_FRQ_RESP9         3109
#define IDC_TREECREATE                  4021
#define IDC_TREESELECT                  4121
#define IDC_LISTCREATEREP               5022
#define IDC_LISTCREATEBM                5023
#define IDC_GRUPPECREATE1               6011
#define IDC_GRUPPECREATE2               6012
#define IDC_GRUPPECREATE3               6013
#define IDC_GRUPPECREATE4               6014
#define IDC_GRUPPESELECT1               6111
#define IDC_RADIOCREATE1                7031
#define IDC_RADIOCREATE2                7032
#define IDC_RADIOCREATE3                7033
#define IDC_RADIOCREATE4                7034
#define IDC_OK2                         8097
#define IDC_CANCEL2                     8098
#define IDC_UEBERNEHMEN                 8099
#define IDC_GRUPPECREATE5               10006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        279
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         10007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
