//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ReplAll.rc
//
#define IDD_PRINTASC_DIALOG             102
#define IDS_PRINTDIALOG_STD             102
#define IDS_PRINTDIALOG_OK              103
#define IDS_PRINTDIALOG_ERROR           104
#define IDS_PRINTINFO_ERROR             105
#define IDS_PRINTDIALOG_OFFLINE         106
#define IDR_TOOLBAR_MEDIUM              128
#define IDR_TOOLBAR_LARGE               129
#define IDD_REPL                        129
#define IDR_REGEXPMENU                  130
#define IDD_COMMENT                     130
#define IDD_STARTUP                     131
#define IDI_VIDOKU                      132
#define IDB_STARTUP_BKGND               133
#define IDC_STATUS_TEXT                 1000
#define IDC_LOCATION_TEXT               1001
#define IDC_WHOLEWORD                   1002
#define IDC_COMMENT_TEXT                1002
#define IDC_MATCHCASE                   1003
#define IDC_STATUS                      1003
#define IDC_REGEXP                      1004
#define IDC_LOCATION                    1004
#define IDC_REGEXPFIND                  1005
#define IDC_COMMENT                     1005
#define IDC_FINDTEXT                    1006
#define IDC_COMBO_PRINTER               1006
#define IDC_REPLTEXT                    1007
#define IDC_REGEXPREPLACE               1008
#define IDC_PARAM_LIST                  1008
#define IDC_EDT_FUNCTION                1009
#define IDC_TAB_LENGTH                  1009
#define IDC_EDT_CLASS                   1010
#define IDC_SETUP                       1010
#define IDC_EDT_RESULT_TYPE             1011
#define IDC_CLIPBOARD_PRINT             1011
#define IDC_CK_INPUT_PARAM              1012
#define IDC_CK_OUTPUT_PARAM             1013
#define IDC_EDT_RESULT_TYPE_DESCRIPTION 1014
#define IDC_EDT_FUNCTION_DESCRIPTION    1015
#define IDC_CK_GERMAN                   1016
#define IDC_COMBO_AUTHORS               1017
#define IDC_BTN_SAVE_SETTINGS           1018
#define IDC_BTN_DEL_AUTHOR              1019
#define IDC_TXT_DOKU_TOOL               1019
#define IDC_CK_INSERT_DATE              1020
#define IDC_CK_START_DISABLE            1020
#define IDC_TXT_DOKU_TOOL1              1021
#define IDC_CK_INSERT_TITLE             1021
#define IDC_TXT_DOKU_TOOL2              1022
#define IDC_CK_INSERT_SOURCE_CODE       1022
#define IDC_CK_INSERT_AUTO_LINKS        1023
#define IDC_EDT_KEY_WORDS               1024
#define IDC_BTN_DEL_GROUP               1025
#define IDC_EDT_TOPICORDER              1026
#define IDC_SPIN_TOPIC                  1027
#define IDC_COMBO_GROUP                 1028
#define IDC_CK_TYPE_LINK                1029
#define IDC_CK_OPTIONAL_PARAM           1030
#define IDS_REPLALL_LONGNAME            20001
#define IDS_REPLALL_DESCRIPTION         20002
#define IDS_CMD_STRING                  20003
#define IDS_CMD_STRING2                 20004
#define IDS_DESCRIPTION                 20005
#define IDS_PARAM                       20006
#define IDS_TYPE                        20007
#define IDS_NO_TEXT_SELECTED            20008
#define IDS_HEADER_FORMAT_TOP           20009
#define IDS_HEADER_FORMAT_MIDDLE        20010
#define IDS_HEADER_FORMAT_BOTTOM        20011
#define IDS_NONE                        20012
#define IDS_HEADER_FORMAT_TOP2          20013
#define IDS_HEADER_FORMAT_MIDDLE2       20014
#define IDS_CMD_STRING3                 20015
#define IDS_NONE2                       20016
#define IDS_AUTHOR                      20017
#define IDS_HEADER_FORMAT_AUTHOR        20018
#define IDS_HEADER_FORMAT_RESULT        20019
#define IDS_HEADER_FORMAT_RESULT2       20020
#define IDS_WRONG_FORMAT                20021
#define IDS_DATE_GERMAN                 20022
#define IDS_DATE_ENGLISH                20023
#define IDS_TITLE                       20024
#define IDS_SOURCE_CODE                 20025
#define IDS_AUTOLINK                    20026
#define IDS_KEYWORDS                    20027
#define IDS_GROUP                       20028
#define IDS_TOPICORDER                  20029
#define IDS_GROUPX                      20030
#define IDS_HEADER_FORMAT_GROUP         20031
#define IDS_DEFAULT_VALUE_GER           20032
#define IDS_DEFAULT_VALUE_ENG           20033
#define ID_OPTIONS_ANYCHARACTER         32771
#define ID_OPTIONS_CHARACTERINRANGE     32772
#define ID_OPTIONS_CHARACTERNOTINRANGE  32773
#define ID_OPTIONS_BEGINNINGOFLINE      32774
#define ID_OPTIONS_ENDOFLINE            32775
#define ID_OPTIONS_TAGGEDEXPRESSION     32776
#define ID_OPTIONS_NOT                  32777
#define ID_OPTIONS_OR                   32778
#define ID_OPTIONS_0ORMOREMATCHES       32779
#define ID_OPTIONS_1ORMOREMATCHES       32780
#define ID_OPTIONS_GROUP                32781
#define ID_OPTIONS_WHITESPACE           32782
#define ID_OPTIONS_ALPHANUMERICCHARACTER 32783
#define ID_OPTIONS_ALPHABETICCHARACTER  32784
#define ID_OPTIONS_DECIMALDIGIT         32785
#define ID_OPTIONS_HEXADECIMALNUMBER    32786
#define ID_OPTIONS_NUMBER               32787
#define ID_OPTIONS_INTEGER              32788
#define ID_OPTIONS_CCIDENTIFIER         32789
#define ID_OPTIONS_ALPHABETICSTRING     32790
#define ID_OPTIONS_QUOTEDSTRING         32791
#define ID_OPTIONS2_FINDWHATTEXT        32792
#define ID_OPTIONS2_TAGGEDEXPRESSION1   32793
#define ID_OPTIONS2_TAGGEDEXPRESSION2   32794
#define ID_OPTIONS2_TAGGEDEXPRESSION3   32795
#define ID_OPTIONS2_TAGGEDEXPRESSION4   32796
#define ID_OPTIONS2_TAGGEDEXPRESSION5   32797
#define ID_OPTIONS2_TAGGEDEXPRESSION6   32798
#define ID_OPTIONS2_TAGGEDEXPRESSION7   32799
#define ID_OPTIONS2_TAGGEDEXPRESSION8   32800
#define ID_OPTIONS2_TAGGEDEXPRESSION9   32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
