//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resskript.rc
//
#define IDS_STATUS_READY                1
#define IDS_STATUS_BUSY                 2
#define IDS_STATUS_DOOR_OPEN            3
#define IDS_STATUS_ERROR                4
#define IDS_STATUS_INITIALIZING         5
#define IDS_STATUS_IO_ACTIVE            6
#define IDS_STATUS_MANUAL_FEED          7
#define IDS_STATUS_NO_TONER             8
#define IDS_STATUS_NOT_AVAILABLE        9
#define IDS_STATUS_OFFLINE              10
#define IDS_STATUS_OUT_OF_MEMORY        11
#define IDS_STATUS_OUTPUT_BIN_FULL      12
#define IDS_STATUS_PAGE_PUNT            13
#define IDS_STATUS_PAPER_JAM            14
#define IDS_STATUS_PAPER_OUT            15
#define IDS_STATUS_PAPER_PROBLEM        16
#define IDS_STATUS_PAUSED               17
#define IDS_STATUS_PENDING_DELETION     18
#define IDS_STATUS_POWER_SAVE           19
#define IDS_STATUS_PRINTING             20
#define IDS_STATUS_PROCESSING           21
#define IDS_STATUS_SERVER_UNKNOWN       22
#define IDS_STATUS_TONER_LOW            23
#define IDS_STATUS_USER_INTERVENTION    24
#define IDS_STATUS_WAITING              25
#define IDS_STATUS_WARMING_UP           26
#define IDS_DEFAULTPRINTER              27
#define IDS_DEFAULTDOC                  29
#define IDS_OFNFILTER                   30
#define IDS_OFNTITLE                    31
#define IDS_OFNDEFAULT                  32
#define IDS_MBNP_TITLE                  33
#define IDS_MBNP_TEXT                   34
#define IDS_DPRINTING                   35
#define IDS_DSETUP                      36
#define IDS_MBQ_PRINTING                37
#define IDI_ICON1                       102
#define IDI_ICON2                       103
#define IDI_ICON3                       104
#define IDD_PRINTERDIALOG               105
#define IDD_PRINTERDIALOGNO             107
#define IDC_PORTRAIT                    1003
#define IDC_LANDSCAPE                   1004
#define IDC_BUTTON_SETUP                1005
#define IDC_LEFT                        1007
#define IDC_RIGHT                       1008
#define IDC_TOP                         1009
#define IDC_BOTTOM                      1010
#define IDC_SELECTPRINTER               1011
#define IDC_COPIES                      1012
#define IDC_FILE                        1015
#define IDC_STATUS                      1018
#define IDC_ORT                         1019
#define IDC_TYP                         1020
#define IDC_COMMENT                     1021
#define IDC_ORIENTICON                  1022
#define IDC_PAGEPREVIEW                 1023

#define IDC_STATIC1                     1025
#define IDC_STATIC2                     1026
#define IDC_STATIC3                     1027
#define IDC_STATIC4                     1028
#define IDC_STATIC5                     1029
#define IDC_STATIC6                     1030
#define IDC_STATIC7                     1031
#define IDC_STATIC8                     1032
#define IDC_STATIC9                     1033
#define IDC_STATIC10                    1034
#define IDC_STATIC11                    1035
#define IDC_STATIC12                    1036
#define IDC_STATIC13                    1037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
