//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GenericUnit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define BIN_SMALL_TESTBILD              50
#define BIN_LARGE_TESTBILD              51
#define IDD_ABOUTBOX                    100
#define ID_ABOUT                        101
#define IDD_GENERIC_APP_DIALOG          102
#define IDB_GREEN                       106
#define IDB_RED                         107
#define IDB_INLAY                       108
#define IDB_MASK                        109
#define IDR_MAINFRAME                   110
#define IDD_DLG_MD_CONFIG               501
#define IDS_RTE_NO_VIDEO                1001
#define IDS_RTE_VIDEO                   1002
#define IDR_GENERICUNIT1                1100
#define IDR_GENERICUNIT2                1101
#define IDR_GENERICUNIT3                1102
#define IDC_SOURCE1                     1103
#define IDC_SOURCE2                     1104
#define IDC_SOURCE3                     1105
#define IDC_SOURCE4                     1106
#define IDC_SOURCE5                     1107
#define IDC_SOURCE6                     1108
#define IDC_SOURCE7                     1109
#define IDC_SOURCE8                     1110
#define IDC_SOURCE9                     1111
#define IDC_SOURCE10                    1112
#define IDC_SOURCE11                    1113
#define IDC_SOURCE12                    1114
#define IDC_SOURCE13                    1115
#define IDC_SOURCE14                    1116
#define IDC_SOURCE15                    1117
#define IDC_SOURCE16                    1118
#define IDC_FE_PAL_CCIR                 1119
#define IDC_FE_NTSC_CCIR                1120
#define IDC_FE_PAL_SQUARE               1121
#define IDC_FE_NTSC_SQUARE              1122
#define IDC_FE_FBAS                     1123
#define IDC_FE_SVHS                     1124
#define IDC_BE_PAL_CCIR                 1125
#define IDC_BE_NTSC_CCIR                1126
#define IDC_BE_PAL_SQUARE               1127
#define IDC_BE_NTSC_SQUARE              1128
#define IDC_DLG_LUMINANCE               1129
#define IDC_BE_COMPOSITE                1130
#define IDC_BE_RGB                      1131
#define IDC_FE_LNOTCH                   1132
#define IDC_FE_LDEC                     1133
#define IDC_EDGE7                       1134
#define IDC_EDGE6                       1135
#define IDC_EDGE5                       1136
#define IDC_EDGE4                       1137
#define IDC_EDGE3                       1138
#define IDC_EDGE2                       1139
#define IDC_EDGE1                       1140
#define IDC_EDGE0                       1141
#define IDC_ACK7                        1142
#define IDC_ACK6                        1143
#define IDC_ACK5                        1144
#define IDC_ACK4                        1145
#define IDC_ACK3                        1146
#define IDC_ACK2                        1147
#define IDC_ACK1                        1148
#define IDC_ACK0                        1149
#define IDC_RELAIS3                     1150
#define IDC_RELAIS2                     1151
#define IDC_RELAIS1                     1152
#define IDC_RELAIS0                     1153
#define IDC_DECODED_FRAMES              1154
#define IDC_ENCODED_FRAMES              1155
#define IDC_DEC_START                   1156
#define IDC_DEC_STOP                    1157
#define IDC_ENC_START                   1158
#define IDC_ENC_STOP                    1159
#define IDC_TEST                        1160
#define IDC_HIGH_RES                    1161
#define IDC_LOW_RES                     1162
#define IDC_COMPRESS_0                  1163
#define IDC_COMPRESS_1                  1164
#define IDC_COMPRESS_2                  1165
#define IDC_COMPRESS_3                  1166
#define IDC_COMPRESS_4                  1167
#define IDC_COMPRESS_5                  1168
#define IDC_VIDEOINLAY                  1169
#define IDC_DLG_MD_CONFIG               1170
#define ID_SETTINGS                     1171
#define IDC_TXT_DECODER                 1172
#define IDC_TXT_ENCODER                 1173
#define IDC_TXT_FRAMES1                 1182
#define IDC_TXT_FRAMES2                 1183
#define IDC_GROUP_RESOLUTION            1184
#define IDC_GROUP_COMPRESSION           1185
#define IDC_TXT_RELAIS                  1186
#define IDC_GROUP_EXTENSION             1187
#define IDC_GROUP_VIDEOSOURCE           1188
#define IDC_GROUP_VIDEOFRONTEND         1189
#define IDC_GROUP_VIDEOBACKEND          1190
#define IDC_GROUP_SOURCETYPE            1191
#define IDC_TXT_EDGE                    1192
#define IDC_TXT_ACK                     1193
#define IDC_MD_TRAINING                 1194
#define IDC_MD_INVERT_MASK              1195
#define IDC_ENABLE_TWO_FIELDS           1196
#define IDC_CONFIG_MD                   1197
#define IDC_INVERT_PERMANENT_MASK       6022
#define IDC_CLEAR_MASK                  6023
#define IDC_SAVE_MASK                   6024
#define IDC_SELECT_CAMERA               6025
#define IDC_COMBO1                      6025
#define IDC_INLAY_WND                   6026
#define IDC_DIFF_WND                    6027
#define IDC_INVERT_ADAPTIVE_MASK        6028
#define IDC_LOAD_MASK                   6029
#define IDC_HIDE_MASK                   6030
#define IDC_TITLE_INLAY                 6031
#define IDC_TITLE_MASK                  6032
#define IDC_SELECT_MASK_SENSITIVITY     6033
#define IDC_SELECT_ALARM_SENSITIVITY    6034
#define IDC_STATIC_AM                   6035
#define IDC_STATIC_PM                   6036
#define IDC_STATIC_LEGENDE              6037
#define IDC_HISTOGRAMM                  6039
#define IDC_STATIC_MD_SENSITIVITY       6040
#define IDC_STATIC_ALARM_SENSITIVITY    6041
#define IDC_FILTER                      6042
#define IDC_ACTIVATE_MD                 6043
#define IDS_CAMERA1                     59142
#define IDS_CAMERA2                     59143
#define IDS_CAMERA3                     59144
#define IDS_CAMERA4                     59145
#define IDS_CAMERA5                     59146
#define IDS_CAMERA6                     59147
#define IDS_CAMERA7                     59148
#define IDS_CAMERA8                     59149
#define IDS_CAMERA9                     59150
#define IDS_CAMERA10                    59151
#define IDS_CAMERA11                    59152
#define IDS_CAMERA12                    59153
#define IDS_CAMERA13                    59154
#define IDS_CAMERA14                    59155
#define IDS_CAMERA15                    59156
#define IDS_CAMERA16                    59157
#define IDS_HIGH                        59158
#define IDS_NORMAL                      59159
#define IDS_LOW                         59160
#define IDS_OFF                         59161

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
