//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TashaUnit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_TASHAUNIT_DIALOG            102
#define IDS_RTE_NO_VIDEO                102
#define IDS_RTE_VIDEO                   103
#define IDS_EEPROM_READBACK_FAILED      104
#define IDS_RTE_VIDEO_STREAM_ABORTED    105
#define IDS_RTE_VIDEO_STREAM_RESUMED    106
#define IDD_ANALOG_VIDEO                129
#define IDD_ENCODER_PARAM               130
#define IDR_MENU1                       131
#define IDR_MAINFRAME                   132
#define IDR_BINRES1                     133
#define IDD_PROGRESS                    134
#define IDI_ICON_ENABLED                135
#define IDI_ICON_DISABLED               136
#define IDI_ICON_FAILURE                137
#define IDI_ICON_ACTIVITY               138
#define IDC_PLAY                        1000
#define IDC_PAUSE                       1001
#define IDC_STOP                        1002
#define IDC_START                       1003
#define IDC_SCROLLBAR_BRIGHTNESS        1004
#define IDC_SCROLLBAR_CONTRAST          1005
#define IDC_SCROLLBAR_SATURATION        1006
#define IDC_STATIC_BRIGTNESS            1007
#define IDC_STATIC_CONTRAST             1008
#define IDC_STATIC_SATURATION           1009
#define IDC_SCROLLBAR_MD_TRESHOLD       1010
#define IDC_STATIC_FRAME                1011
#define IDC_STATIC_FPS                  1012
#define IDC_RADIO_CAM0                  1013
#define IDC_RADIO_CAM1                  1014
#define IDC_RADIO_CAM2                  1015
#define IDC_RADIO_CAM3                  1016
#define IDC_RADIO_CAM4                  1017
#define IDC_RADIO_CAM5                  1018
#define IDC_RADIO_CAM6                  1019
#define IDC_RADIO_CAM7                  1020
#define IDC_RELAIS3                     1021
#define IDC_RELAIS2                     1022
#define IDC_RELAIS1                     1023
#define IDC_RELAIS0                     1024
#define IDC_SCROLLBAR_MASK_TRESHOLD     1025
#define IDC_GROUP_VIDEO_INPUT           1026
#define IDC_CHECK_ALARM0                1027
#define IDC_CHECK_ALARM1                1028
#define IDC_CHECK_ALARM2                1029
#define IDC_CHECK_ALARM3                1030
#define IDC_CHECK_ALARM4                1031
#define IDC_CHECK_ALARM5                1032
#define IDC_CHECK_ALARM6                1033
#define IDC_CHECK_ALARM7                1034
#define IDC_STATIC_ALARME               1035
#define IDC_DOWNLOAD                    1036
#define IDC_DOWNLOAD_ALTERA             1036
#define IDC_DOWNLOAD_EEPROM             1037
#define IDC_SAVE_EEPROM                 1038
#define IDC_PREVIEW                     1039
#define IDC_PREVIEW1                    1039
#define IDC_CHECK_MULTY_VIEW            1040
#define IDC_CHECK_FRAME_SYNC            1041
#define IDC_CHECK_NOISEREDUCTION        1042
#define IDC_CHECK_SHOW_ADAPTIVE_MASK    1043
#define IDC_CHECK_SHOW_DIFF_IMAGE       1044
#define IDC_RESET_BF533                 1045
#define IDC_STATIC_MD_TRESHOLD          1046
#define IDC_STATIC_MASK_TRESHOLD        1047
#define IDC_SCROLLBAR_MASK_INCREMENT    1048
#define IDC_SCROLLBAR_MASK_DELAY        1049
#define IDC_STATIC_MASK_INCREMENT       1050
#define IDC_STATIC_MASK_DELAY           1051
#define IDC_SET_PERM_MASK               1052
#define IDC_CHECK_SHOW_PERMANENT_MASK   1053
#define IDC_CLEAR_MASK                  1054
#define IDC_INVERT_MASK                 1055
#define IDC_CROSSPOINT_0_0              1055
#define IDC_CROSSPOINT_1_0              1056
#define IDC_PREVIEW2                    1056
#define IDC_CROSSPOINT_2_0              1057
#define IDC_CROSSPOINT_3_0              1058
#define IDC_CROSSPOINT_4_0              1059
#define IDC_CROSSPOINT_5_0              1060
#define IDC_CROSSPOINT_6_0              1061
#define IDC_CROSSPOINT_7_0              1062
#define IDC_CROSSPOINT_0_1              1063
#define IDC_CROSSPOINT_1_1              1064
#define IDC_CROSSPOINT_2_1              1065
#define IDC_CROSSPOINT_3_1              1066
#define IDC_CROSSPOINT_4_1              1067
#define IDC_CROSSPOINT_5_1              1068
#define IDC_CROSSPOINT_6_1              1069
#define IDC_CROSSPOINT_7_1              1070
#define IDC_CROSSPOINT_0_2              1071
#define IDC_CROSSPOINT_1_2              1072
#define IDC_CROSSPOINT_2_2              1073
#define IDC_CROSSPOINT_3_2              1074
#define IDC_CROSSPOINT_4_2              1075
#define IDC_CROSSPOINT_5_2              1076
#define IDC_CROSSPOINT_6_2              1077
#define IDC_CROSSPOINT_7_2              1078
#define IDC_CROSSPOINT_0_3              1079
#define IDC_CROSSPOINT_1_3              1080
#define IDC_CROSSPOINT_2_3              1081
#define IDC_CROSSPOINT_3_3              1082
#define IDC_CROSSPOINT_4_3              1083
#define IDC_CROSSPOINT_5_3              1084
#define IDC_CROSSPOINT_6_3              1085
#define IDC_CROSSPOINT_7_3              1086
#define IDC_TERM_0                      1087
#define IDC_TERM_1                      1088
#define IDC_TERM_2                      1089
#define IDC_TERM_3                      1090
#define IDC_TERM_4                      1091
#define IDC_TERM_5                      1092
#define IDC_TERM_6                      1093
#define IDC_TERM_7                      1094
#define IDC_VID_ENABLE                  1095
#define IDC_CROSSPOINT                  1096
#define IDC_CROSSPOINT_ENABLE           1096
#define IDC_EDIT_REGISTER               1097
#define IDC_EDIT_REGISTER_VALUE         1098
#define IDC_SET_REG                     1099
#define IDC_CHECK_ADAPTER_SELECT0       1100
#define IDC_CHECK_ADAPTER_SELECT1       1101
#define IDC_CHECK_ADAPTER_SELECT2       1102
#define IDC_CHECK_ADAPTER_SELECT3       1103
#define IDC_CHECK_PC_KEYS0              1104
#define IDC_CHECK_PC_KEYS1              1105
#define IDC_CHECK_PC_KEYS2              1106
#define IDC_CHECK_PC_KEYS3              1107
#define IDC_CHECK_POWER_LED             1108
#define IDC_CHECK_RESET_LED             1109
#define IDC_CHECK_SAVE_TO_DISK          1110
#define IDC_RADIO_RESOLUTION_HIGH       1111
#define IDC_ENCODERPARAM                1111
#define IDC_RADIO_RESOLUTION_MID        1112
#define IDC_RADIO_RESOLUTION_LOW        1113
#define IDC_EDIT_BITRATE                1114
#define IDC_EDIT_FPS                    1116
#define IDC_EDIT_IFRAME_INTERVALL       1117
#define IDC_RADIO_MPEG4                 1118
#define IDC_RADIO_YUV422                1119
#define IDC_EDIT_PROZESSID              1120
#define IDC_SEND                        1122
#define IDC_EDIT_STREAMID               1123
#define IDC_READ                        1124
#define IDC_PROGRESS_BOOTING            1124
#define IDC_STATIC_INFOTEXT             1125
#define IDC_REQ_SINGLE_FIELD            1125
#define ID_FILE_ABOUT                   32771
#define ID_FILE_SETTINGS                32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
