
#ifndef _CIPCType_h
#define _CIPCType_h

enum CIPCType
{
	CIPC_NONE				= 0,
	CIPC_INPUT_CLIENT		= 1,
	CIPC_OUTPUT_CLIENT	= 2,
	CIPC_DATABASE_CLIENT	= 3,
	CIPC_ALARM_CLIENT		= 4,
	CIPC_INPUT_SERVER		= 5,
	CIPC_OUTPUT_SERVER	= 6,
	CIPC_DATABASE_SERVER	= 7,
	CIPC_ALARM_SERVER		= 8,
	CIPC_CONTROL_AUDIO    =12,
	CIPC_AUDIO_SERVER     =13,
	CIPC_AUDIO_CLIENT     =14
};
extern LPCTSTR NameOfEnum(CIPCType ct);

#endif
