//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISDNUnit.rc
//
#define IDC_UPDATE                      2
#define ID_ADVANCED_SETTINGS            3
#define IDR_MAINFRAME                   128
#define IDD_ABOUTBOX                    129
#define IDR_MAINFRAMEPT                 129
#define IDD_ISDN_SETTINGS               130
#define IDD_KNOCK_KNOCK_BOX             135
#define IDD_ABOUTBOX_GARNY              136
#define IDR_MAINFRAME_PT                136
#define IDD_ADVANCED_PT                 137
#define IDR_MAINFRAME_NO_DEVICE         138
#define IDR_MAINFRAME_PT_NO_DEVICE      139
#define IDC_BIGICON                     1000
#define IDC_RUFNUMMER                   1001
#define IDC_USER_ID                     1001
#define IDC_B_CHANNEL                   1002
#define IDC_MESSAGE                     1003
#define IDC_PASSWORD                    1003
#define IDC_CONNECT_STATE               1004
#define IDC_NR_B_CHANNELS               1005
#define IDC_CALLED_PARTY                1006
#define IDC_REMOTE_STATION              1006
#define IDC_STATIC_MODULE_VERSION       1007
#define IDC_STATIC_COPYRIGHT            1008
#define IDC_STATIC_CONNECT_STATE        1009
#define IDC_STATIC_REMOTE_STATION       1011
#define IDC_TIME                        1012
#define IDC_TRACE_SEND                  1012
#define IDC_TXT_TIME                    1013
#define IDC_TRACE_RECEIVE               1013
#define IDC_STATIC_VERSION              1014
#define IDC_TXT_HOSTNAME                1015
#define IDC_TXT_OWN_NUMBER              1016
#define IDC_STATIC_HOSTNAME             1017
#define IDC_STATIC_OWN_NUMBER           1018
#define IDC_TXT_CHANNELS                1019
#define IDC_TXT_PROCESSOR_USAGE         1019
#define IDC_NUM_CHANNELS                1020
#define IDC_USAGE_HIGH                  1020
#define IDC_USAGE_MEDIUM                1021
#define IDC_TXT_VERSION                 1021
#define IDC_USAGE_LOW                   1022
#define IDC_TXT_TRACES                  1023
#define IDC_TXT_NUM_B                   1024
#define IDC_CLOSE_ACTIVE_CONNECTION     1025
#define IDC_TXT_KNOCK_TIME              1026
#define IDC_KNOCK_TIME                  1027
#define IDC_TXT_KNOCK_NUMBER            1028
#define IDC_TXT_KNOCK_NAME              1029
#define IDC_KNOCK_NAME                  1030
#define IDC_KNOCK_NUMBER                1031
#define IDC_TXT_CURRENT_CONNECTION      1032
#define IDC_CURRENT_CONNECTION          1033
#define IDC_TXT_KNOCK_GROUP             1034
#define IDC_ENABLE_KNOCK_BOX            1035
#define IDC_TXT_KNOCK_SETTINGS          1036
#define IDC_TXT_OWN_SETTINGS            1037
#define IDC_TXT_MODULE_NAME             1038
#define IDC_TXT_COPYRIGHT               1039
#define IDC_CLOSE_ONE_CHANNEL           1040
#define IDC_HIDDEN_QUIT                 1041
#define IDC_TXT_ADVANCED_PT_WARNING     1042
#define IDC_TXT_HEX_DUMP                1043
#define IDC_DO_HEX_DUMP_SEND            1044
#define IDC_DO_HEX_DUMP_RECEIVE         1045
#define IDC_PT_PICTURE                  1046
#define IDC_PT_DISABLE_FRAME_GRABBING   1047
#define IDC_PT_LOW_AS_MID               1048
#define IDC_TXT_PT_MISC                 1049
#define IDC_PT_DISABLE_EEP_WRITE        1050
#define IDC_TXT_PT_ADVANCED_INFO        1051
#define IDC_MSN_SUPPORT                 1052
#define IDC_PT_DO_TRACE_PICTURES        1052
#define IDC_TXT_MSN_SUUPPORT            1053
#define IDC_STATIC_COMPRESSIONRATE      1054
#define IDC_COMPRESSIONRATE             1055
#define IDC_STATIC_COMPRESSIONRATE2     1056
#define IDC_STATIC_NAME_PW              1078
#define IDC_STATIC_NAME                 1079
#define IDC_STATIC_PW                   1080
#define IDC_STATIC_BITMAP               1084
#define ID_ABOUT                        0x1000
#define ID_SETTINGS                     0x1010
#define ID_CLOSE_ALL_ISDN_CONNECTIONS   0x1020
#define ID_CLOSE_MODUL                  0x1030
#define IDS_ABOUT                       10001
#define IDS_SETTINGS                    10002
#define IDS_CLOSE_ALL_ISDN_CONNECTIONS  10003
#define IDS_CE_USER_BUSY                10004
#define IDS_CE_CALL_REJECTED            10005
#define IDS_CE_34XX                     10006
#define IDS_ISDN_NOT_CLOSED             10007
#define IDS_ISDN_MODULE_CLOSING         10008
#define IDS_CE_NO_USER_RESPONDING       10009
#define IDS_CE_PROTOCOL_ERROR_LAYER_1   10010
#define IDS_CE_PROTOCOL_ERROR_LAYER_2   10011
#define IDS_CE_PROTOCOL_ERROR_LAYER_3   10012
#define IDS_CE_B1_PROTOCOL_NOT_SUPPORTED 10013
#define IDS_CE_B2_PROTOCOL_NOT_SUPPORTED 10014
#define IDS_CE_B3_PROTOCOL_NOT_SUPPORTED 10015
#define IDS_CE_B1_PARAMS_NOT_SUPPORTED  10016
#define IDS_CE_B2_PARAMS_NOT_SUPPORTED  10017
#define IDS_CE_B3_PARAMS_NOT_SUPPORTED  10018
#define IDS_CE_B_PROTOCOL_COMBINATION_NOT_SUPPORTED 10019
#define IDS_CONNECT_REQUEST_TIMEOUT     10020
#define IDS_UNIT_NOT_STARTED            10021
#define IDS_TOO_MANY_APPL               10022
#define IDS_CAPI_NOT_INSTALLED_1        10023
#define IDS_CAPI_NOT_ENOUGH_MEMORY      10024
#define IDS_CE_10XX                     10025
#define IDS_CE_11XX                     10026
#define IDS_CE_20XX                     10027
#define IDS_CE_30XX                     10028
#define IDS_CE_33XX                     10029
#define IDS_CE_ANOTHER_APPLICATION_GOT_THE_CALL 10031
#define IDS_CE_NORMAL_CALL_CLEARING     10035
#define IDS_CE_NO_ANSWER_FROM_USER      10036
#define IDS_CE_NUMBER_CHANGED           10037
#define IDS_CE_NON_SELECTED_USER_CLEARING 10038
#define IDS_CE_DESTINATION_OUT_OF_ORDER 10039
#define IDS_CE_INVALID_NUMBER_FORMAT    10040
#define IDS_CE_FACILITY_REJECTED        10041
#define IDS_CE_RESPONSE_TO_STATUS_ENQUIRY 10042
#define IDS_CE_NORMAL_UNSPECIFIED       10043
#define IDS_CE_NO_CHANNEL_AVAILABLE     10044
#define IDS_CE_NETWORK_OUT_OF_ORDER     10045
#define IDS_CE_TEMPORARY_FAILURE        10046
#define IDS_TT_PT_HEX_DUMP_SEND         10047
#define IDS_TT_PT_HEX_DUMP_RECEIVE      10048
#define IDS_TT_PT_DISABLE_FRAME_GRABBING 10049
#define IDS_TT_PT_LOW_AS_MID            10050
#define IDS_TT_PT_DISABLE_EEP_WRITE     10051
#define IDS_PROCTOCOL_ERROR_REMOTE_IST  10052
#define IDS_PROCTOCOL_ERROR_REMOTE_PTBOX 10053
#define IDS_PROCTOCOL_ERROR_REMOTE_PTUNIT 10054
#define IDS_PROCTOCOL_ERROR_REMOTE_UNKNOWN 10055
#define IDS_NO_ROUTING                  10056
#define IDS_ACCESS_DENIED               10057
#define IDS_INVALID_PERMISSION_ACCESS_DENIED 10057
#define IDS_STATE_TITLE_TRAILER         10058
#define IDS_INCOMING_CALL               10059
#define IDS_OUTGOING_CALL               10060
#define IDS_CLOSE_OUTGOING_CALL         10061
#define IDS_CLOSE_INCOMING_CALL         10062
#define IDS_REJECT_INCOMING_CALL        10063
#define IDS_REJECT_OUTGOING_CALL        10064
#define IDS_NO_DEVICE_FOUND             10065
#define IDS_ISDN_NOT_AVAILABLE          10066
#define IDS_EMPTY_HOST_NAME             10067
#define IDS_ISDN_BUSY                   10068
#define IDS_UNKNOWN                     10069
#define IDS_WITHOUT_NUMBER              10070
#define ID_SHOW_STATE                   32771
#define ID_CLOSE_ONE_ISDN_CHANNEL       32773
#define ID_OPEN_SECOND_B_CHANNEL        32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
