//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DVClient.rc
//
#define IDR_MAINFRAME                   128
#define IDD_PANEL                       131
#define IDC_POINTER                     132
#define IDR_ANICUR_DINO                 133
#define IDC_ARROW4                      134
#define IDC_ARROW1                      135
#define IDC_ARROW2                      136
#define IDC_GLASS                       137
#define IDC_ARROW3                      138
#define IDD_MINIMIZED                   139
#define IDD_KEYBOARD                    140
#define IDD_RTE                         141
#define IDB_SINGLE_FORWARD              142
#define IDB_BACK2                       143
#define IDB_FF2                         144
#define IDB_PAUSE2                      145
#define IDB_PLAY2                       146
#define IDB_REW2                        147
#define IDB_SINGLE_BACK2                148
#define IDB_SINGLE_FORWARD2             149
#define IDB_SKIP_BACK2                  150
#define IDB_SKIP_FORWARD2               151
#define IDB_STOP2                       152
#define IDB_EJECT2                      153
#define IDB_EXPORT                      154
#define IDB_PRINT                       155
#define IDB_POWER2                      156
#define IDB_SHIFT                       157
#define IDB_ENTER2                      158
#define IDB_DEL                         159
#define IDB_CONFIRM                     160
#define IDB_MINIMIZE                    161
#define IDB_MINIMIZE_AC                 162
#define IDB_MINIMIZED_AC                163
#define IDB_FF                          164
#define IDB_PAUSE                       165
#define IDB_STOP                        166
#define IDB_RIGHT                       167
#define IDB_LEFT                        168
#define IDB_UP                          169
#define IDB_DOWN                        170
#define IDB_ENTER                       171
#define IDB_SEARCH                      172
#define IDB_MINIMIZED                   173
#define IDB_BACKSPACE                   174
#define IDB_SKIP_BACK                   175
#define IDB_SKIP_FORWARD                176
#define IDB_SINGLE_BACK                 177
#define IDB_POWER                       178
#define IDB_EJECT                       179
#define IDB_REW                         180
#define IDB_PLAY                        181
#define IDB_SYMBOLS                     182
#define IDD_EXPORT                      183
#define IDB_CLOCK                       184
#define IDB_DEL_ALL                     185
#define IDB_ALARMLIST_PLAY2             186
#define IDB_ALARMLIST_PRINT             187
#define IDB_ALARMLIST_UP                188
#define IDB_ALARMLIST_DOWN              189
#define IDB_ALARMLIST_ENTER             190
#define IDB_ALARMLIST_ACTIVITY          191
#define IDB_ALARMLIST_EXTERN1           192
#define IDB_ALARMLIST_EXTERN2           193
#define IDB_ALARMLIST_DOWN2             194
#define IDB_ALARMLIST_UP2               195
#define IDB_INVERT                      196
#define IDD_STATISTIC_DLG               200
#define IDD_ALARMLIST_DIALOG            201
#define IDC_RECT                        203
#define IDD_MD                          204
#define IDB_SHOW_ADAPTIVE               207
#define IDD_HOSTS                       209
#define IDB_NEW                         210
#define IDB_DOWN_END                    211
#define IDB_UP_START                    212
#define IDR_ACCELERATOR_KEYBORD         213
#define IDB_MINIMIZE_PO                 214
#define IDB_MINIMIZED_PO                215
#define IDB_ALARMLIST_AUDIO             216
#define IDD_INFO_DLG                    218
#define IDC_PANLEFT                     222
#define IDC_PANRIGHT                    223
#define IDC_TILTUP                      224
#define IDC_TILTDOWN                    225
#define IDC_ZOOMIN                      226
#define IDC_ZOOMOUT                     227
#define IDC_LEFTTOP                     228
#define IDC_LEFTBOTTOM                  229
#define IDC_RIGHTBOTTOM                 230
#define IDC_RIGHTTOP                    231
#define IDC_FOCUS_FAR                   232
#define IDC_FOCUS_NEAR                  233
#define IDC_FOCUS_AUTO                  234
#define IDC_BUTTON_OK                   1000
#define IDC_CROSS_UP                    1001
#define IDC_BUTTON_NUM1                 1002
#define IDC_BUTTON_NUM2                 1003
#define IDC_BUTTON_NUM3                 1004
#define IDC_BUTTON_NUM4                 1005
#define IDC_BUTTON_NUM5                 1006
#define IDC_BUTTON_NUM6                 1007
#define IDC_BUTTON_NUM7                 1008
#define IDC_BUTTON_NUM8                 1009
#define IDC_BUTTON_NUM9                 1010
#define IDC_BUTTON_NUM0                 1011
#define IDC_DISPLAY_TIME                1013
#define IDC_BUTTON_PLUS                 1015
#define IDC_BUTTON_CLEAR                1016
#define IDC_BUTTON_NUMPLUS              1019
#define IDC_CROSS_DOWN                  1020
#define IDC_CROSS_RIGHT                 1022
#define IDC_BORDER1                     1024
#define IDC_DISPLAY_STATUS              1026
#define IDC_CROSS_LEFT                  1028
#define IDC_CROSS_SET                   1030
#define IDC_DISPLAY_MENU1               1032
#define IDC_DISPLAY_TOOLTIP             1034
#define IDC_BUTTON_MINUS                1036
#define IDC_DISPLAY_CAMERA              1039
#define IDC_DISPLAY_MENU2               1042
#define IDC_BUTTON_REWIND               1047
#define IDC_BUTTON_PLAY                 1048
#define IDC_BUTTON_PLAY_BACK            1049
#define IDC_BUTTON_STOP                 1050
#define IDC_BUTTON_FF                   1051
#define IDC_BUTTON_EJECT                1052
#define IDC_BUTTON_SKIP_BACK            1053
#define IDC_BUTTON_SINGLE_BACK          1054
#define IDC_BUTTON_SINGLE_FORWARD       1055
#define IDC_BUTTON_SEARCH               1056
#define IDC_BUTTON_SKIP_FORWARD         1058
#define IDC_BUTTON_EXPORT               1059
#define IDC_BUTTON_PRINT                1060
#define IDC_MINIMIZED                   1061
#define IDC_BUTTON_MINIMIZE             1062
#define IDC_BUTTON_BACKSPACE            1081
#define IDC_BUTTON_SHIFT                1082
#define IDC_BUTTON_SPACE                1083
#define IDC_RTE_DEL                     1084
#define IDC_RTE_BORDER                  1085
#define IDC_RTE_UP                      1086
#define IDC_RTE_DOWN                    1087
#define IDC_RTE_DISPLAY                 1088
#define IDC_RTE_CONFIRM                 1089
#define IDC_RTE_OK                      1090
#define IDC_RTE_TIMESTAMP               1091
#define IDC_RTE_CONF_DISPLAY            1092
#define IDC_BORDER_EXPORT               1093
#define IDC_RTE_DEL_ALL                 1094
#define IDC_DISPLAY_EXPORT_FROM         1095
#define IDC_RTE_PRINT                   1096
#define IDC_DISPLAY_EXPORT_TO           1097
#define IDC_CLOCK                       1098
#define IDC_STATIC_EXPORT               1099
#define IDC_BUILDNR                     1100
#define IDC_EXPORT_CAM1                 1101
#define IDC_EXPORT_CAM2                 1102
#define IDC_EXPORT_CAM3                 1103
#define IDC_EXPORT_CAM4                 1104
#define IDC_EXPORT_CAM5                 1105
#define IDC_EXPORT_CAM6                 1106
#define IDC_EXPORT_CAM7                 1107
#define IDC_EXPORT_CAM8                 1108
#define IDC_EXPORT_CAM9                 1109
#define IDC_EXPORT_CAM10                1110
#define IDC_EXPORT_CAM11                1111
#define IDC_EXPORT_CAM12                1112
#define IDC_EXPORT_CAM13                1113
#define IDC_EXPORT_CAM14                1114
#define IDC_EXPORT_CAM15                1115
#define IDC_EXPORT_CAM16                1116
#define IDC_STATISTIC_DISPLAY           1117
#define IDC_STATISTIC_BORDER            1118
#define IDC_MD_INLAY                    1119
#define IDC_MD_DEL                      1120
#define IDC_MD_INVERT                   1121
#define IDC_MD_SHOW_ADAPTIVE            1122
#define IDC_ALARMLIST_OK                1123
#define ID_MD_OK                        1124
#define IDC_HOSTS_OK                    1125
#define IDC_HOSTS_NEW                   1126
#define IDC_HOSTS_DELETE                1127
#define IDC_HOSTS_LIST                  1128
#define IDC_HOSTS_DISPLAY_NAME          1129
#define IDC_HOSTS_DISPLAY_IP            1130
#define IDC_HOSTS_FRAME_IP              1131
#define IDC_HOSTS_FRAME_NAME            1132
#define IDC_HOSTS_UP_START              1133
#define IDC_HOSTS_UP                    1134
#define IDC_HOSTS_DOWN                  1135
#define IDC_HOSTS_DOWN_END              1136
#define IDC_HOSTS_FRAME_TOOLTIP         1137
#define IDC_HOSTS_DISPLAY_TOOLTIP       1138
#define IDC_ALARMLIST_UP                1150
#define IDC_ALARMLIST_DOWN              1151
#define IDC_ALARMLIST_PRINT             1152
#define IDC_ALARMLIST_CAM0              1153
#define IDC_ALARMLIST_CAM1              1154
#define IDC_ALARMLIST_CAM2              1155
#define IDC_ALARMLIST_CAM3              1156
#define IDC_ALARMLIST_CAM4              1157
#define IDC_ALARMLIST_CAM5              1158
#define IDC_ALARMLIST_CAM6              1159
#define IDC_ALARMLIST_CAM7              1160
#define IDC_ALARMLIST_CAM8              1161
#define IDC_ALARMLIST_CAM9              1162
#define IDC_ALARMLIST_CAM10             1163
#define IDC_ALARMLIST_CAM11             1164
#define IDC_ALARMLIST_CAM12             1165
#define IDC_ALARMLIST_CAM13             1166
#define IDC_ALARMLIST_CAM14             1167
#define IDC_ALARMLIST_CAM15             1168
#define IDC_ALARMLIST_ACTIVITY          1169
#define IDC_ALARMLIST_EXTERN1           1170
#define IDC_ALARMLIST_EXTERN2           1171
#define IDC_ALARMLIST_IMAGE             1172
#define IDC_ALARMLIST_UP2               1173
#define IDC_ALARMLIST_DOWN2             1174
#define IDC_ALARMLIST_LIST              1175
#define IDC_ALARMLIST_DISPLAY_BORDER    1176
#define IDC_ALARMLIST_DISPLAY_TITLE     1177
#define IDC_ALARMLIST_ALARM_DISPLAY     1178
#define IDC_ALARMLIST_AUDIO             1178
#define IDC_ALARMLIST_ALARM_BORDER      1179
#define IDC_STATISTIC_OK                1181
#define IDC_FEATURE                     1187
#define IDC_BORDER                      1188
#define ID_INFO_OK                      1189
#define IDC_FEATURE_NAME                1192
#define IDC_BUTTON_KBLANG               1193
#define IDC_BUTTON_0                    2000
#define IDC_BUTTON_1                    2001
#define IDC_BUTTON_2                    2002
#define IDC_BUTTON_3                    2003
#define IDC_BUTTON_4                    2004
#define IDC_BUTTON_5                    2005
#define IDC_BUTTON_6                    2006
#define IDC_BUTTON_7                    2007
#define IDC_BUTTON_8                    2008
#define IDC_BUTTON_9                    2009
#define IDC_BUTTON_Q                    2010
#define IDC_BUTTON_W                    2011
#define IDC_BUTTON_E                    2012
#define IDC_BUTTON_R                    2013
#define IDC_BUTTON_T                    2014
#define IDC_BUTTON_Z                    2015
#define IDC_BUTTON_U                    2016
#define IDC_BUTTON_I                    2017
#define IDC_BUTTON_O                    2018
#define IDC_BUTTON_P                    2019
#define IDC_BUTTON_A                    2020
#define IDC_BUTTON_S                    2021
#define IDC_BUTTON_D                    2022
#define IDC_BUTTON_F                    2023
#define IDC_BUTTON_G                    2024
#define IDC_BUTTON_H                    2025
#define IDC_BUTTON_J                    2026
#define IDC_BUTTON_K                    2027
#define IDC_BUTTON_L                    2028
#define IDC_BUTTON_Y                    2029
#define IDC_BUTTON_X                    2030
#define IDC_BUTTON_C                    2031
#define IDC_BUTTON_V                    2032
#define IDC_BUTTON_B                    2033
#define IDC_BUTTON_N                    2034
#define IDC_BUTTON_M                    2035
#define IDC_BUTTON_UE                   2036
#define IDC_BUTTON_OE                   2037
#define IDC_BUTTON_AE                   2038
#define IDC_BUTTON_SC1                  2039
#define IDC_BUTTON_SC2                  2040
#define IDC_BUTTON_SC3                  2041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1194
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
