//
// VMPEG4Encoder.h
//
// VMPEG4Encoder

// Our GUID. Generated by the wizard to be unique.
// {caf31f40-b322-4049-afb5-2288e419141f}
DEFINE_GUID(CLSID_VMPEG4ENCODER,
0xcaf31f40, 0xb322, 0x4049, 0xaf, 0xb5, 0x22, 0x88, 0xe4, 0x19, 0x14, 0x1f);

//
// CVMPEG4Encoder
//
class CVMPEG4Encoder : public CBaseFilter
{
public:

    // filter object registration information
    static const AMOVIESETUP_FILTER sudFilter;

        // called to create the COM filter oject
    static CUnknown *WINAPI CreateInstance(LPUNKNOWN punk, HRESULT *phr);
        
    virtual ~CVMPEG4Encoder();

    DECLARE_IUNKNOWN;

private:

    // Constructor - just calls the base class constructor
    CVMPEG4Encoder(TCHAR *tszName, LPUNKNOWN punk, HRESULT *phr);

    // return the number of pins this filter has
    virtual int           GetPinCount();

    // pointer to a pin.
    virtual CBasePin* GetPin(int n);
    // use to serialize access to filter interface methods.
    CCritSec m_FilterLock;

    // CBaseFilter derived objects cannot be copied
    CVMPEG4Encoder(const CVMPEG4Encoder&);
    CVMPEG4Encoder& operator=(const CVMPEG4Encoder&);
};
