//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SystemVerwaltung.rc
//
#define IDR_MAINFRAME                   100
#define IDR_SYSTEMTYPE                  101
#define IDB_IMAGES                      102
#define IDD_HOSTLIST                    115
#define IDD_ISDN                        126
#define IDD_SOCKET                      127
#define IDD_APP                         137
#define IDB_UP                          145
#define IDD_ARCHIV                      147
#define IDB_DOWN                        148
#define IDD_DRIVE                       149
#define IDB_HOT                         150
#define IDB_COLD                        152
#define IDB_ARCHIVE                     154
#define IDB_DRIVES                      155
#define IDC_RUFNUMMER                   1002
#define IDC_DO_LISTEN                   1023
#define IDC_TXT_EXTENDED_OPTIONS        1056
#define IDC_GRP_APP                     1101
#define IDC_TXT_AUTO_APP                1103
#define IDC_TXT_CONF_APP                1104
#define IDC_EDIT_AUTO_APP               1105
#define IDC_EDIT_CONF_APP               1107
#define IDC_RADIO_512_KB                1108
#define IDC_CHECK_APP                   1109
#define IDC_RADIO_256_KB                1110
#define IDC_GRP_CONNECTION              1111
#define IDC_RADIO_128_KB                1112
#define IDC_CHECK_CONN                  1113
#define IDC_RADIO_64_KB                 1114
#define IDC_TXT_AUTO_CONN               1115
#define IDC_TXT_CONF_CONN               1117
#define IDC_EDIT_AUTO_CONN              1119
#define IDC_EDIT_CONF_CONN              1121
#define IDC_CHECK_MSN                   1125
#define IDC_RADIO_B1                    1127
#define IDC_RADIO_B2                    1128
#define IDC_LIST_HOST                   1224
#define IDC_STATIONS_NAME               1291
#define IDC_CHECK_SOCKET                1293
#define IDC_CHECK_ISDN                  1302
#define IDC_STATIC_HOST_NAME            1307
#define IDC_STATIC_ARCHIVE_NAME         1308
#define IDC_STATIC_NUMBER               1310
#define IDC_STATIC_OWN_NAME             1311
#define IDC_STATIC_ISDN                 1316
#define IDC_STATIC_SOCKET               1325
#define IDC_TXT_TYP                     1346
#define IDC_COMBO_TYPE_HOST             1347
#define IDC_RADIO_8MBIT                 1382
#define IDC_RADIO_4MBIT                 1383
#define IDC_RADIO_2MBIT                 1384
#define IDC_RADIO_1MBIT                 1385
#define IDC_ARCHIVE                     1393
#define IDC_STATIC_SIZE                 1397
#define IDC_EDIT_SIZE                   1398
#define IDC_STATIC_MB                   1399
#define IDC_COMBO_ALARM                 1400
#define IDC_STATIC_MAX                  1401
#define IDC_STATIC_MAX_MB               1402
#define IDC_STATIC_FREE                 1403
#define IDC_STATIC_WHOLE                1404
#define IDC_STATIC_USED_MB              1405
#define IDC_STATIC_WHOLE_MB             1406
#define IDC_TXT_USED                    1407
#define IDC_STATIC_SLASH                1408
#define IDC_DRIVES                      1409
#define IDC_RADIO_SYSTEM                1410
#define IDC_RADIO_NORMAL                1411
#define IDC_RADIO_DATABASE              1412
#define IDC_RADIO_BACKUP_WRITE_READ     1413
#define IDC_RADIO_BACKUP_READ           1414
#define IDC_TXT_SIZE                    1415
#define IDC_TXT_MB                      1416
#define IDC_GROUP_USE                   1417
#define IDC_TXT_DRIVE                   1418
#define IDC_STATIC_DRIVE                1419
#define IDC_TXT_USE                     1420
#define IDC_EDIT_USE                    1421
#define IDC_TXT_MB2                     1422
#define IDC_TXT_SIZE2                   1425
#define IDC_TXT_MB3                     1427
#define IDC_GROUP_PROPERTIES            1428
#define IDC_GROUP_DRIVE                 1429
#define IDC_GROUP_SIZE                  1430
#define IDC_STATIC_DRIVES_MB            1431
#define IDC_STATIC_ARCHIVS_MB           1432
#define IDC_ALL                         1433
#define IDC_NAME_HOST                   1503
#define IDC_NAME_ARCHIV                 1507
#define IDC_ADDRESS_HOST                1517
#define IDC_STATIC_REJECT               1568
#define IDC_STATIC_B_CHANNELS           1569
#define IDC_HOST_ARCHIVES               1575
#define IDC_EDIT_PREFIX                 1609
#define IDC_TXT_PREFIX                  1610
#define IDC_TXT_PREFIX_MINIMUM          1611
#define IDC_EDIT_PREFIX_MINIMUM         1612
#define IDS_HOSTS                       10008
#define IDS_NEW                         10016
#define IDS_NEWHOST                     10031
#define IDS_HOST                        10032
#define IDS_NUMBER                      10033
#define IDS_ISDN1                       10034
#define IDS_SOCKET                      10035
#define IDS_TYP                         10050
#define IDS_AUTOLOGOUT                  10064
#define IDP_SAVE_CHANGES                10080
#define IDS_RESET_FAILED                10101
#define IDP_DOUBLE_HOST                 10118
#define IDP_HOST_WITHOUT_NUMBER         10119
#define IDP_NOAPPWITHOUTCONN            10149
#define IDP_APP_LT_CONF                 10150
#define IDP_CONN_LT_CONF                10151
#define IDP_APP_LT_CONN                 10152
#define IDP_NO_LOCAL_HOSTNAME           10154
#define IDP_HOST_ILLEGAL_ROUTING        10167
#define IDP_INVALID_DONGLE              10194
#define IDP_ACCESS_DENIED               10195
#define IDS_NAME                        10217
#define IDS_LOCAL_HOST                  10223
#define IDS_DRIVES                      10227
#define IDS_ARCHIVES                    10228
#define IDS_NR                          10229
#define IDS_SIZE_MB                     10231
#define IDS_ALARM_ARCHIV                10232
#define IDS_RING_ARCHIV                 10233
#define IDS_VORRING_ARCHIV              10234
#define IDS_NEW_ARCHIV                  10237
#define IDS_DRIVE                       10238
#define IDS_USEDAS                      10239
#define IDS_USED                        10240
#define IDS_SIZE                        10241
#define IDS_QUOTA                       10242
#define IDS_DRIVE_FD                    10243
#define IDS_DRIVE_HD                    10244
#define IDS_DRIVE_NET                   10245
#define IDS_DRIVE_CD                    10246
#define IDS_ALL                         10247
#define IDS_USE_NORMAL                  10248
#define IDS_USE_DATABASE                10249
#define IDS_USE_BACKUP_READ             10250
#define IDS_USE_BACKUP_WRITE_READ       10251
#define IDS_USE_SYSTEM                  10252
#define IDS_TOO_LESS_DATABASE_DRIVES    10253
#define IDP_ARCHIVS_TOO_BIG             10255
#define IDS_DELETE_HOST_ARCHIV          10274
#define IDP_CREATE_NORMAL_ARCHIVE_FOR_HOST 10276
#define IDP_CREATE_SEARCH_ARCHIVE_FOR_HOST 10277
#define IDS_HOST_NORMAL_ARCHIVE         10279
#define IDS_HOST_SEARCH_ARCHIVE         10280
#define IDP_NO_AUTOMATIC_ARCHIV         10281
#define IDS_SAVE                        10282
#define IDS_SETTINGS                    10283
#define IDS_OPEN                        10284
#define IDS_SEARCH_RESULT               10294
#define IDS_ARCHIV                      10352
#define IDP_REGISTRY_IMPORT_WARNING     10361
#define IDP_HOST_ILLEGAL_ADDRESS        10364
#define IDP_ARCHIV_SIZE_ZERO            10371
#define IDP_ARCHIV_SIZE_TO_BIG          10372
#define IDS_LOGIN_SUCCESFUL             10375
#define IDS_LOGIN_DENIED                10376
#define IDP_FIXED_ARCHIVES_ON_DRIVE     10379
#define IDP_ARCHIVE_SIZE_ZERO           10398
#define IDP_CONFIG_DRIVE_FIRST          10399
#define ID_EDIT_NEW                     32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_CANCEL                  32773
#define ID_EDIT_SERVERINIT              32774
#define ID_VIEW_TOOLTIPS                32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1613
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
