//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VipCleanNT.rc
//
#define IDD_VIPCLEANNT_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_IDIPCLEAN_DIALOG            129
#define IDD_CLEAN98                     132
#define IDD_CLEANNT                     133
#define IDB_CHECK_OK                    135
#define IDB_CHECK_FAILED                136
#define IDC_OEM1                        1000
#define IDC_OEM2                        1001
#define IDC_OEM3                        1002
#define IDC_HOSTNAME                    1003
#define IDC_ORGA                        1004
#define IDC_WRITEREG                    1005
#define IDC_DELDIR                      1006
#define IDC_DEL                         1007
#define IDC_KAM                         1008
#define IDC_RADIO4KAM                   1009
#define IDC_IMAGE_TEST                  1010
#define IDC_RADIO8KAM                   1011
#define IDC_RADIO16KAM                  1012
#define IDC_NERO1                       1013
#define IDC_NERO2                       1014
#define IDC_NERO3                       1015
#define IDC_NERO4                       1016
#define IDC_NERO5                       1017
#define IDC_LOADERTIMEOUT               1018
#define IDC_NERO6                       1019
#define IDC_TEMP                        1020
#define IDC_OS                          1022
#define IDC_SR                          1024
#define IDC_BUILD                       1026
#define IDC_RADIO4CAMS                  1028
#define IDC_RADIO8CAMS                  1029
#define IDC_RADIO16CAMS                 1030
#define IDC_STATIC_LOADER               1032
#define IDC_STATIC_TEMP                 1034
#define IDC_CHECK_OEM                   1035
#define IDC_CHECK_COMPNAME              1036
#define IDC_CHECK_ORGA                  1037
#define IDC_OEM                         1038
#define IDC_COMPNAME                    1048
#define IDC_DRIVES                      1057
#define IDC_ARCHIVE                     1061
#define IDC_CHECK_LOG                   1062
#define IDC_CHECK_ARCHIVE               1063
#define IDC_CHECK_TEMP                  1064
#define IDC_DATETIMEPICKER2             1066
#define IDC_DATETIMEPICKER3             1067
#define IDC_SCREEN                      1068
#define IDC_ALLE_ARCHIVE                1069
#define IDC_DESK_FOLDER                 1070
#define IDC_SYSTEM_OVERVIEW             1071
#define IDC_FILE_LIST                   1072
#define IDC_CHECK_DESK_FOLDER           1073
#define IDC_CHECK_SYSTEM_OVERVIEW       1074
#define IDC_CHECK_FILE_LIST             1075
#define IDC_UEBERNEHMEN                 1082
#define IDC_AENDERUNGEN                 1087
#define IDC_KEINE_AENDERUNGEN           1088
#define IDC_ORDNERDATEI                 1089
#define IDC_KEINE_ORDNERDATEI           1090
#define IDC_INFO_DELDIR                 1093
#define IDC_INFO_NOTDELDIR              1094
#define IDC_STATUS                      1095
#define IDC_RESULT                      1096
#define IDC_DATE                        1100
#define IDC_TIME                        1101
#define IDC_ZONE                        1102
#define IDC_DATETIMEZONE                1103
#define IDOK2                           1104
#define IDC_PING                        1105
#define IDC_75HZ                        1106
#define IDC_BTN_CF_INIT                 1107
#define IDC_CHECK_ISDN                  1108
#define IDC_TWEAK_TOOL                  1109
#define IDC_BTN_CF_UNINIT               1110
#define IDC_CHECK_NET                   1111
#define IDC_IPADDRESS1                  1112
#define IDC_PING_OK                     1113
#define IDC_PING_NOTYET                 1114
#define IDC_FREQUENCE                   1115
#define IDC_HZ                          1116
#define IDC_ORGA_COMBO                  1117
#define IDC_COMPORT_OK                  1118
#define IDC_COMPORT_NOTOK               1119
#define IDC_60Hz                        1120
#define IDC_STATICOEM1                  1121
#define IDC_STATICOEM2                  1122
#define IDC_KAM4                        1123
#define IDC_KAM8                        1124
#define IDC_KAM16                       1125
#define IDC_KAM8_TASHA                  1126
#define IDC_STATICTEMP                  1127
#define IDC_STATICXPE                   1128
#define IDC_EDIT_XPE                    1129
#define IDC_STATICNERO                  1130
#define IDC_KAM16_TASHA                 1131
#define IDC_STATIC_DISPLAY              1132
#define IDC_CHECK_BACKUP                1133
#define IDC_OS_IN_USE                   1134
#define IDC_KAM16_TASHA2                1134
#define IDC_KAM_QUNIT                   1134
#define IDC_STATIC_XPE                  1135
#define IDC_STATIC_OEM                  1136
#define IDC_STATIC_OEM_MIDDLE           1137
#define IDC_EDIT_XP                     1138
#define IDC_STATIC_NERO                 1139
#define IDC_EDIT_NERO1                  1140
#define IDC_EDIT_NERO2                  1141
#define IDC_EDIT_NERO3                  1142
#define IDC_EDIT_NERO4                  1143
#define IDC_EDIT_NERO5                  1144
#define IDC_EDIT_NERO6                  1145
#define IDC_STATIC_SECONDS              1146
#define IDC_STATIC_HDD                  1147
#define IDC_EDIT_HDD                    1148
#define IDC_EDIT_HDD2                   1149
#define IDC_STATIC_HDD_LINE             1153
#define IDC_STATIC_ORDNER               1154
#define IDC_STATIC_LIST                 1155
#define IDC_STATIC_SYS                  1156
#define IDC_CHECK_HDD                   1157
#define IDC_STATIC_CREATE               1158
#define IDC_CHECK_DVD                   1159
#define IDC_SET_HDDID                   1160
#define IDC_BTN_AUDIO_VOLUMES           1162
#define IDC_CK_AUDIO_TEST               1165
#define IDC_STATICNERO_VERSION          1168
#define IDC_RADIO_LITEON                1170
#define IDC_RADIO_MITSUMI               1171
#define IDC_BTN_INIT_DISKS              1172
#define IDC_TXT_LOGPATH                 1173
#define IDC_TXT_TEMP_PATH               1174
#define IDS_MIXER_DEST0                 50100
#define IDS_MIXER_DEST1                 50101
#define IDS_MIXER_DEST2                 50102
#define IDS_MIXER_DEST3                 50103
#define IDS_MIXER_DEST4                 50104
#define IDS_MIXER_DEST5                 50105
#define IDS_MIXER_DEST6                 50106
#define IDS_MIXER_DEST7                 50107
#define IDS_MIXER_DEST8                 50108
#define IDS_MIXER_SRC0                  50120
#define IDS_MIXER_SRC1                  50121
#define IDS_MIXER_SRC2                  50122
#define IDS_MIXER_SRC3                  50123
#define IDS_MIXER_SRC4                  50124
#define IDS_MIXER_SRC5                  50125
#define IDS_MIXER_SRC6                  50126
#define IDS_MIXER_SRC7                  50127
#define IDS_MIXER_SRC8                  50128
#define IDS_MIXER_SRC9                  50129
#define IDS_MIXER_SRC10                 50130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
