//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WkTranslator.rc
//
#define IDC_STEP                        3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LANGTYPE                    129
#define IDD_EDIT                        130
#define IDD_FIND                        131
#define IDD_EDIT_REPLACE                132
#define IDD_IMPORT_GLOSSARY_INFO        133
#define IDD_SELECT_CODEPAGE             134
#define IDD_TRANSLATOR                  135
#define IDC_EDIT_ORIGINAL               1000
#define IDC_EDIT_TRANSLATE              1001
#define IDC_COPY                        1002
#define IDC_EDIT_SUGGESTION             1003
#define IDC_BUTTON_SUGGESTION           1004
#define IDC_TXT_TRANSLATOR              1005
#define IDC_TXT_COPYRIGHT               1006
#define IDC_STATIC_ICON                 1007
#define IDC_TXT_ORIGINAL                1008
#define IDC_TXT_COPY                    1009
#define IDC_TXT_TRANSLATION             1009
#define IDC_TXT_FIND                    1010
#define IDC_EDIT_FIND                   1011
#define IDC_CHECK_CASE_SENSITIVE        1012
#define IDC_TXT_FIND2                   1012
#define IDC_EDIT_REPLACE                1013
#define IDC_TXT_MAX_LENGTH              1014
#define IDC_EDIT_MAX_LENGTH             1015
#define IDC_TXT_SUGGESTION              1016
#define IDC_EDIT_COMMENT                1017
#define IDC_EDIT_ACTUAL_LENGTH          1018
#define IDC_TXT_ACTUAL_LENGTH           1019
#define IDC_TXT_GLOSSARY                1020
#define IDC_TXT_GLOSSARY_NR             1021
#define IDC_TXT_STRINGS                 1022
#define IDC_TXT_STRINGS_NR              1023
#define IDC_BTN_FONT                    1024
#define IDC_TXT_ORG                     1024
#define IDC_TXT_TRAN                    1025
#define IDC_COMBO_CODE_PAGE             1026
#define IDC_TXT_TRANSLATE_NR            1026
#define IDC_CK_STOP                     1028
#define IDC_CK_REPLACE                  1029
#define IDC_TXT_STRINGS2                1030
#define IDC_TXT_FILENAME                1031
#define WK_LANG_BLOCK_NUM               0x409
#define IDC_TXT_RESSOURCE_TYPE          1033
#define IDC_TXT_RESSOURCE_TYPE_NAME     1034
#define IDC_EDT_ORG_TEXT                1034
#define IDC_EDT_TRANS_TEXT              1035
#define IDC_BTN_CONVERT                 1036
#define IDC_EDT_CODEPAGE                1037
#define IDC_BTN_CODEPAGE                1038
#define IDC_BTN_SEARCH_CONVERT          1039
#define IDC_CK_MBCS                     1040
#define IDS_ORIGINAL                    10000
#define IDS_TRANSLATE                   10001
#define IDP_NOTHING_TODO                10002
#define IDP_ERROR_FORMAT_SPECIFIER      10003
#define IDP_NO_MORE_FOUND               10004
#define IDS_ERROR_STATIC                10005
#define IDS_ERROR                       10006
#define IDP_ERROR_MAX_LENGTH            10007
#define IDS_MAX_LENGTH                  10008
#define IDP_SEARCH_END_OF_DOC           10009
#define IDP_SAVE_FILE_FAILED            10010
#define IDP_ERROR_SPECIAL_START_CHARS   10011
#define IDP_CHECK_TRANSLATION           10012
#define IDP_ERROR_SPECIAL_CHARS_TO_AVOID 10013
#define IDP_GLOSSARY_ADDED              10014
#define IDP_FILE_OPEN_FAILED            10015
#define IDS_SUGGESTION                  10016
#define IDS_DEFAULTANSICODEPAGE         10017
#define IDS_DEFAULTOEMCODEPAGE          10018
#define IDS_UNICODE                     10019
#define IDS_START                       10020
#define IDS_STOP                        10021
#define IDS_RST_DEFAULT                 10022
#define IDS_RST_MENUITEM                10023
#define IDS_RST_POPUP                   10024
#define IDS_RST_CAPTION                 10025
#define IDS_RST_LTEXT                   10026
#define IDS_RST_CTEXT                   10027
#define IDS_RST_RTEXT                   10028
#define IDS_RST_DEFPUSHBUTTON           10029
#define IDS_RST_BUTTON                  10030
#define IDS_RST_GROUPBOX                10031
#define IDS_RST_CONTROL                 10032
#define IDS_RST_PUSHBOX                 10033
#define IDS_RST_SCROLLBAR               10034
#define IDS_RST_STATE3                  10035
#define IDS_RST_STRING                  10036
#define IDP_SEARCH_END_OF_DOC2          10037
#define IDS_CHECK_AND_REPLACE_MULTIPLE_OCCURRENCES 10037
#define IDS_REQUES_TREMOVE_ALL_TODOS    10038
#define ID_EDIT                         32771
#define ID_GLOSSARY_IMPORT              32772
#define ID_GLOSSARY_EXPORT              32773
#define ID_FILE_SAVE_AS_GLOSSARY        32774
#define ID_NEXT_TODO                    32775
#define ID_ENABLE_EDIT                  32776
#define ID_ENABLE_EDIT_ACC              32777
#define ID_CHECK_MAX_LENGTH             32778
#define ID_EDIT_FIND_NEXT               32779
#define ID_CHECK_TRANSLATION            32780
#define ID_CHECK_TRANSLATION_ALL        32781
#define ID_GLOSSARY_EXPORT_DEU          32782
#define ID_GLOSSARY_IMPORT_DEU          32783
#define ID_FILE_SAVE_AS_GLOSSARY_DEU    32784
#define ID_FILE_SAVE_TEXT_ONLY          32785
#define ID_FILE_SAVE_ORIGINAL_LEN_COMMENT 32786
#define ID_VIEW_SHOW_ONLY_TODO          32787
#define ID_GLOSSARY_IMPORT_TXT_FILE     32788
#define ID_VIEW_EDITFONT                32789
#define ID_VIEW_EDITFONTCHANGE          32790
#define ID_GLOSSARY_SELECT_CODEPAGE     32790
#define ID_VIEW_SHOW_ONLY_SUGGESTIONS   32791
#define ID_EDIT_REMOVE_ALL_TODOS        32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
