//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Factura.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PRINTASC_DIALOG             102
#define IDB_FLAG_IMAGES                 102
#define IDR_MAINFRAME                   128
#define IDR_FACTURTYPE                  129
#define IDD_CUSTOMER                    130
#define IDD_CUSTOMER_FIND               131
#define IDD_INVOICE                     132
#define IDD_PRODUCT                     133
#define IDD_PRODUCT_FIND                134
#define IDD_INVOICE_FIND                135
#define IDD_STATE                       136
#define IDD_PRINT_ADR_KL                137
#define IDD_PRINT_BANK_KL               138
#define IDD_EDIT_FORM                   139
#define IDR_PRODUCT_LISTMENU            140
#define IDD_PAY_MODE                    140
#define IDD_CURRENCY_UNIT               141
#define IDR_INV_PRT_ADR_KL              141
#define IDD_BASE_SETTINGS               142
#define IDR_SENDM_INSERT_ADR            142
#define IDD_PRINT_LABEL                 143
#define IDR_INV_SPEEDY_ITEM             143
#define IDD_SENDEMAIL                   144
#define IDD_PRINT_FROM_TO               145
#define IDD_LOG_ON                      146
#define IDC_STATUS_TEXT                 1000
#define IDC_LOCATION_TEXT               1001
#define IDC_COMMENT_TEXT                1002
#define IDC_STATUS                      1003
#define IDC_LOCATION                    1004
#define IDC_COMMENT                     1005
#define IDC_COMBO_PRINTER               1006
#define IDC_SETUP                       1007
#define IDC_CUSTOMER_NEW                1010
#define IDC_CUSTOMER_TITLE              1011
#define IDC_CUSTOMER_EMAIL              1012
#define IDC_CUSTOMER_FIND_THIS          1013
#define IDC_CUSTOMER_FAX                1014
#define IDC_CUSTOMER_COMPANY            1015
#define IDC_CUSTOMER_PHONE              1016
#define IDC_CUSTOMER_STATE              1017
#define IDC_CUSTOMER_MALE               1018
#define IDC_CUSTOMER_FEMALE             1019
#define IDC_CUSTOMER_SPIN               1021
#define IDC_CUSTOMER_COMMENT            1022
#define IDC_CUSTOMER_SPEEDY             1023
#define IDC_CUSTOMER_NO                 1024
#define IDC_CUSTOMER_CITY               1025
#define IDC_CUSTOMER_HOUSE_NO           1026
#define IDC_CUSTOMER_FIRSTNAME          1027
#define IDC_CUSTOMER_STREET             1028
#define IDC_CUSTOMER_PLZ                1029
#define IDC_CUSTOMER_NAME               1030
#define IDC_CUSTOMER_DELETE             1031
#define IDC_CUSTOMER_FIND               1032
#define IDC_CUSTOMER_IMPORT             1035
#define IDC_CUSTOMER_FLAGS              1036
#define IDC_CUSTOMER_SENDEMAIL          1037
#define IDC_CUSTOMER_PRINT_ADR_KL       1038
#define IDC_INVOICE_PRINT_ADR_KL        1038
#define IDC_FIND_LIST                   1040
#define IDC_FIND_EDIT                   1041
#define IDC_FIND_STR                    1042
#define IDC_INVOICE_FLAGS               1049
#define IDC_INVOICE0                    1050
#define IDC_INVOICE1                    1051
#define IDC_INVOICE_NO                  1052
#define IDC_INVOICE_DATE                1053
#define IDC_INVOICE_NN_AMOUNT           1054
#define IDC_INVOICE_FIND                1055
#define IDC_INVOICE_NEW                 1056
#define IDC_INVOICE_DELETE              1057
#define IDC_INVOICE_PRINT_NNZS          1058
#define IDC_INVOICE_ADR_FIELD           1059
#define IDC_INVOICE_PRINT_ADR_RG_NO     1060
#define IDC_INVOICE_PRINT               1061
#define IDC_INVOICE_COMMENT             1062
#define IDC_INVOICE_TOTAL_NETTO         1063
#define IDC_INVOICE_TOTAL_NETTO_STR     1064
#define IDC_INVOICE_TOTAL_STR           1065
#define IDC_INVOICE_TOTAL               1066
#define IDC_INVOICE_TAX_STR             1067
#define IDC_INVOICE_TAX                 1068
#define IDC_INVOICE_FIND_CUST           1069
#define IDC_PRODUCT_NO                  1070
#define IDC_PRODUCT_LIST                1071
#define IDC_PRODUCT_DESCRIPTION         1072
#define IDC_PRODUCT_PRICE               1073
#define IDC_PRODUCT_NEW                 1074
#define IDC_PRODUCT_DELETE              1075
#define IDC_PRODUCT_FIND                1076
#define IDC_PRODUCT_COUNT               1077
#define IDC_PRINT_ADR_CUST_FROM         1080
#define IDC_PRINT_ADR_CUST_TO           1081
#define IDC_PRINT_ADR_HIAK              1082
#define IDC_PRINT_ADR_CALE              1083
#define IDC_PRINT_ADR_SERVICECARD       1084
#define IDC_PRINT_ADR_SELECT            1085
#define IDC_CONVERT_FONT                1086
#define IDC_PRINT_NAME_OF_ADR           1086
#define IDC_FORM_FEED                   1087
#define IDC_INVOICE_CURRENCY            1088
#define IDC_INVOICE_PAY_MOD             1089
#define IDC_PBK_BANKNAME                1090
#define IDC_PBK_BLZ                     1091
#define IDC_PBK_AMOUNT                  1092
#define IDC_PBK_KTO_NO                  1093
#define IDC_PBK_CURRENCY                1094
#define IDC_PBK_COUNT                   1095
#define IDC_PAYMODE_SPIN                1096
#define IDC_PAYMODE_EDIT                1097
#define IDC_INVOICE_SPIN                1098
#define IDC_STATE_NEW                   1099
#define IDC_INVOICE_PAYED               1100
#define IDC_STATE_INSERT                1101
#define IDC_STATE_NAME                  1102
#define IDC_STATE_ID                    1103
#define IDC_STATE_DELETE                1104
#define IDC_EF_COMBO                    1105
#define IDC_EF_NEW                      1106
#define IDC_EF_COMBO_LIST               1107
#define IDC_PAYMODE_DELETE              1110
#define IDC_PAYMODE_NEW                 1111
#define IDC_PAYMODE_SAVE                1112
#define IDC_PAYMODE_SPIN_EDIT           1113
#define IDC_CU_NEW                      1120
#define IDC_CU_SAVE                     1121
#define IDC_CU_DELETE                   1122
#define IDC_CU_UNITSIGN                 1123
#define IDC_CU_STATESIGN                1124
#define IDC_CU_CURRENCY                 1125
#define IDC_CU_UNIT                     1126
#define IDC_CU_STATE                    1127
#define IDC_CU_REFERENCE                1128
#define IDC_COMBO_FIND_PRICE            1129
#define IDC_BD_TAX                      1132
#define IDC_BD_NN_AMOUNT                1133
#define IDC_COMBO_PRODUCT_GROUP         1135
#define IDC_EDT_PRODUCT_GROUP           1136
#define IDC_EDT_PRODUCT_RELEASEL        1137
#define IDC_EDT_PRODUCT_RELEASEH        1138
#define IDC_COMBO_PRODUCT_PRICE_GROUP   1139
#define IDC_EDT_PRODUCT_PRICE_GROUP     1140
#define IDC_EDT_PRODUCT_EAN             1141
#define IDC_EDT_PRODUCT_COMPANY_CODE    1142
#define IDC_EDT_PRODUCT_GROUP1          1143
#define IDC_COMBO_FIND_PRODUCT          1144
#define IDC_EDT_PRODUCT_PRICE_GROUP1    1145
#define IDC_EDT_PRODUCT_EAN_ART_CODE    1146
#define IDC_INVOICE_CANCELED            1147
#define IDC_EDT_TEXT                    1149
#define IDC_EDT_COUNT                   1150
#define IDC_SPIN_COUNT                  1151
#define IDC_INVOICE_RABATT              1153
#define IDC_INVOICE_RABATT_AMOUNT       1154
#define IDC_COMBO_PRODUCT_CURRENCY      1155
#define IDC_INVOICE_PRINT_BANK_KL       1156
#define IDC_PRODUCT_PRICE_GROUP_VISIBLE 1157
#define IDC_PRODUCT_PRICE_HIDDEN        1158
#define IDC_FIND_FULL_TEXT              1159
#define IDC_ADRESS_STRING               1160
#define IDC_INSERT_ADRESS               1161
#define IDC_SEND_DIRECT                 1162
#define IDC_SUBJECT_STRING              1163
#define IDC_BODY_STRING                 1164
#define IDC_ADRESS_STRING2              1165
#define IDC_NAME_STRING                 1166
#define IDC_ADRESS_STRING3              1167
#define IDC_COMBO_ATTTACHMENTS          1168
#define IDC_BTN_INSERT_ATTACHMENT       1169
#define IDC_BTN_DELETE_ATTACHMENT       1170
#define IDC_ADRESS_STRING_FROM          1171
#define IDC_NAME_STRING_FROM            1172
#define IDC_SEND_USER_DATA              1173
#define IDC_SEND_SAVE_USER              1174
#define IDC_INSERT_ADRESS2              1175
#define IDC_LINES                       1180
#define IDC_LENGTH                      1181
#define IDC_SAVESETTINGS                1182
#define IDC_EDT_PROD_FROM               1183
#define IDC_EDT_PROD_TO                 1184
#define IDC_EDT_PFT_LINE_LENGTH         1185
#define IDC_CK_PFT_PRINT_HIDDEN         1186
#define IDC_EDT_LOG_ON_PROFILE          1187
#define IDC_CK_LOG_ON_SAVE_PASSWORD     1188
#define IDC_EDT_LOG_ON_PASSWORD         1189
#define IDC_LOGON_SAVE                  1190
#define IDC_CK_LOG_ON_ENTER_NEW_SESSION 1191
#define IDC_CUSTOMER_SPEEDY_SAVE        1192
#define IDC_CUSTOMER_SPEEDY_DELETE      1193
#define IDC_CUSTOMER_PRT_LOGFILE        1194
#define IDC_INVOICE_BANK_KL_AMOUNT      1195
#define ID_EDIT_NEWCUSTOMER             32771
#define ID_EDIT_INSERT_HIAK_DATA        32772
#define ID_EDIT_NEWINVOICE              32773
#define ID_EDIT_NEWPRODUCTS             32774
#define ID_EDIT_PRODUCT_DELETE          32775
#define ID_EDIT_PRODUCT_NEW             32776
#define ID_EDIT_PRODUCT_FIND            32777
#define ID_OPTIONS_NNZS_PRINTER         32778
#define ID_OPTIONS_ADR_KL_PRINTER       32779
#define ID_EXTRA_PRINT_ADR              32780
#define ID_EXTRA_PRINT_BANK             32781
#define ID_DATA_STATISTIC               32782
#define ID_EDIT_STATES                  32783
#define ID_EXTRA_EXPORT_CUSTOMER        32785
#define ID_EXTRA_IMPORT_CUSTOMER        32786
#define ID_FILE_PRINT_LOGFILE           32790
#define ID_EXTRA_EDIT_FORM              32791
#define ID_EXTRA_PRINT_FORM             32792
#define IDX_SHOW_LABEL_STRUCTURE        32793
#define ID_EDIT_PAYMODES                32794
#define ID_EDIT_CURRENCYUNITS           32795
#define ID_EDIT_BASE_DATA               32796
#define ID_EXTRA_PRINT_FORM_DIRECT      32798
#define ID_EXTRA_PRINT_STANDARD_LETTER  32800
#define ID_OPTIONS_LOGFILE_PRINTER      32801
#define ID_EXTRA_PRINT_PRODUCTS         32802
#define ID_EXTRA_SEND_MAIL              32803
#define ID_PRT_NAME_OF_ADR              32804
#define ID_INSERT_TO_BLIND_COPY         32805
#define ID_INSERT_TO_PHP_CONTENT_FILE   32806
#define ID_EXTRA_PRINT_LABEL            32807
#define ID_PRT_ADR_W_INV_NO             32808
#define ID_SPEEDY_DELETE                32809
#define ID_SPEEDY_SETTINGS              32810
#define IDS_HIAK_FILE                   51046
#define IDS_SEARCHING_FOR               51047
#define IDS_DBASE_FILE                  51048
#define IDS_CUSTOMER_TXT_FILE           51049
#define IDS_CUSTOMER_NO                 51050
#define IDS_CUSTOMER_NAME               51051
#define IDS_CUSTOMER_FIRSTNAME          51052
#define IDS_CUSTOMER_PC                 51053
#define IDS_CUSTOMER_CITY               51054
#define IDS_CUSTOMER_STREET             51055
#define IDS_CUSTOMER_COMPANY            51056
#define IDS_CUSTOMER_FLAGS_DLG          51057
#define IDS_SPEEDY_PRINT_INV            51058
#define IDS_SPEEDY_PRINT_INV2           51059
#define IDS_SPEEDY_PRINT_INV3           51060
#define IDS_SPEEDY_PRINT_INV4           51061
#define IDS_SEND_MAIL_NOW               51062
#define IDS_SENDMAIL_NO_ADRESS          51063
#define IDS_SENDMAIL_NO_SUBJECT         51064
#define IDS_SENDMAIL_NO_BODY            51065
#define IDS_CUSTOMER_EMAIL              51066
#define IDS_PRODUCT_NO                  51070
#define IDS_PRODUCT_DESCRIPTION         51071
#define IDS_PRODUCT_COUNT               51072
#define IDS_PRODUCT_PRICE               51073
#define IDS_PRODUCT_TOTAL               51075
#define IDS_INVOICE_POSITION            51080
#define IDS_INVOICE_NO                  51081
#define IDS_INVOICE_DATE                51082
#define IDS_MISSING_PRODUCT             51083
#define IDS_ADR_KL_PRINTDLG             51090
#define IDS_NNZS_PRINTDLG               51091
#define IDS_PRINTDIALOG_STD             51092
#define IDS_PRINTDIALOG_OK              51093
#define IDS_PRINTDIALOG_ERROR           51094
#define IDS_PRINTINFO_ERROR             51095
#define IDS_INVOICENO_EXITS             51096
#define IDS_CUSTOMER_NOTAVAILABLE       51097
#define IDS_SAVE_BANK_SETTINGS          51098
#define IDS_STATE_ID                    51099
#define IDS_STATE_NAME                  51100
#define IDS_LOG_FILE_NAME               51101
#define IDS_SAVE_IN_REPORT_FILE         51102
#define IDS_DELETE_CUSTOMER_FILE        51103
#define IDS_CREATE_NEW_IVOICE_FOR_CUSTOMER 51104
#define IDS_DELETE_LOGFILE              51105
#define IDS_SAVE_CUSTOMER               51106
#define IDS_PRINTER_NOT_READY           51107
#define IDS_SAVE_INVOICE                51108
#define IDS_PRINT_ADRESS_LABEL          51109
#define IDS_PRINT_REMBOURSEMENT_LABEL   51110
#define IDS_SAVE_PAYMODE                51111
#define IDS_SAVE_PRODUCT                51112
#define IDS_SAVE_CURRENCY_UNIT          51113
#define IDS_CHANGE_CUSTOMER_IN_INVOICE  51114
#define IDS_DATA_INCOMPLETE             51115
#define IDS_PRINT_DLG_CAPTION           51116
#define IDS_VIEW_DLG_CAPTION            51117
#define IDS_SAVE_SPEEDY_CAPTION         51118
#define IDS_CHOOSE_SPEEDY_CAPTION       51119
#define IDS_DELETE_SPEEDY_CAPTION       51120
#define IDS_LOGFILE_PRINTDLG            51121
#define IDS_SAVE_SETTINGS               51122
#define IDS_DELETE_INVOICE              59394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
