//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SecurityLauncher.rc
//
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDS_TEMPERATUR_ALARM            129
#define IDD_ERROR                       130
#define IDS_DEVICE_HARDDISK             130
#define IDD_BEFORE_BACKUP               131
#define IDS_DEVICE_CPU                  131
#define IDD_AFTER_BACKUP                132
#define IDS_DEVICE_POWER_SUPPLY         132
#define IDD_SERVICE                     133
#define IDS_DEVICE_HW_BOARD             133
#define IDB_BUTTON_SYMBOLS              134
#define IDS_DEVICE_UNKNOWN              134
#define IDD_EXTENSION_CODE              134
#define IDB_ERROR_SYMBOLS               135
#define IDS_DEVICE_CASE                 135
#define IDS_FAN_SPEED_ALARM             136
#define IDB_LBG_IST                     137
#define IDS_DEVICE_SYSTEM               137
#define IDB_LBG_SANTEC                  138
#define IDB_LBG_DRESEARCH               139
#define IDB_LBG_ALARMCOM                140
#define IDI_ALARMCOM                    141
#define IDD_LOGIN                       142
#define IDB_LBG_PROTECTION_ONE          143
#define IDB_LBG_SIEMENS                 144
#define IDB_VIDETE_LOGO                 145
#define IDC_USER_ID                     1001
#define IDC_PASSWORD                    1002
#define IDC_ERRORS                      1003
#define IDC_DELETE                      1004
#define IDC_STMOFF                      1005
#define IDC_STMON                       1006
#define IDC_TXT1                        1007
#define IDC_TXT2                        1008
#define IDC_TXT3                        1009
#define IDC_TXT4                        1010
#define IDC_TXT5                        1011
#define IDC_TXT6                        1012
#define IDC_TXT7                        1013
#define IDC_TXT8                        1014
#define IDC_TXT9                        1015
#define IDC_TXT10                       1016
#define IDC_TXT11                       1017
#define IDC_TXT12                       1018
#define IDC_GRP1                        1019
#define IDC_GRP2                        1020
#define IDC_TXT0                        1021
#define IDC_EDIT_SERVICE                1022
#define IDC_SUCCESS                     1023
#define IDC_NO_SUCCESS                  1024
#define IDC_DATE                        1025
#define IDC_GROUP_DATE                  1026
#define IDC_GRP_TIME                    1027
#define IDC_TIME                        1028
#define IDC_TXT_SERIAL_NUMBER           1029
#define IDC_EDT_SERIAL_NUMBER           1030
#define IDC_TXT_EXTENSION_CODE          1031
#define IDC_EDIT2                       1032
#define IDC_EDT_EXTENSION_CODE          1032
#define IDP_EMPTY_REGISTRY              10000
#define IDP_LOGIN_FAILED                10001
#define IDS_PICT_SPACE                  10002
#define IDS_BACKUP_HINT                 10003
#define IDP_NOLOGDIR                    10004
#define IDS_TIME                        10005
#define IDS_MODUL                       10006
#define IDS_MESSAGE                     10007
#define IDS_PARAMETER                   10008
#define IDS_AC_OR_WATCHDOG              10009
#define IDS_YEAR                        10010
#define IDS_MONTH                       10011
#define IDS_DAY                         10012
#define IDS_HOUR                        10013
#define IDS_MINUTE                      10014
#define IDS_SECOND                      10015
#define IDS_MILLISECOND                 10016
#define IDS_UNKOWN                      10017
#define IDP_INVALID_DONGLE              10018
#define IDS_DONGLE_EXE                  10019
#define IDP_SHUTDOWN_FOR_BACKUP         10020
#define IDP_SHUTDOWN_AFTER_BACKUP       10021
#define IDP_DBBACKUP_STILL_RUNNING      10022
#define IDS_BACKUP                      10023
#define IDP_MICOERROR                   10024
#define IDS_SDICONFIG                   10025
#define IDS_RTE                         10026
#define IDS_EXIT                        10027
#define IDS_SYSTEM                      10028
#define IDS_EXTENDED                    10029
#define IDS_RESTART                     10030
#define IDS_EXPLORER                    10031
#define IDS_EXPLORER_SHELL              10032
#define IDS_LAUNCHER_SHELL              10033
#define IDS_ALARM_PERCENT               10034
#define IDS_ISDN_BCHANNEL               10035
#define IDS_NOTIME_PERMISSION_NT        10036
#define IDS_DATETIME                    10037
#define IDS_EURO_CHANGE                 10038
#define IDP_EURO_CHANGE_REALLY          10039
#define IDS_NOT_ALL_RUNNING             10040
#define IDS_SO                          10041
#define IDS_MO                          10042
#define IDS_DI                          10043
#define IDS_MI                          10044
#define IDS_DO                          10045
#define IDS_FR                          10046
#define IDS_SA                          10047
#define IDS_NO_PERMISSION               10048
#define ID_VISION                       32771
#define ID_DATABASE                     32772
#define ID_SUPERVISOR                   32773
#define ID_SKIP                         32774
#define ID_ERROR                        32775
#define ID_PRODUCT_VIEW                 32776
#define ID_BACKUP                       32777
#define ID_DISK                         32778
#define ID_VERSION                      32779
#define ID_SDI_CONFIG                   32780
#define ID_EXPLORER_SHELL               32781
#define ID_LAUNCHER_SHELL               32782
#define ID_LOG_VIEW                     32783
#define ID_DATETIME                     32784
#define ID_EURO_CHANGE                  32785
#define ID_EXPLORER                     32786
#define ID_IMAGE_COMPARE                32787
#define ID_AOT                          32788
#define ID_BUTTON                       32789
#define ID_AIH                          32790
#define ID_UPDATE                       32791
#define ID_SPACE                        32792
#define ID_RESTART                      32793
#define ID_UPDATE_HANDLER               32794
#define ID_SOFTWARE_UPDATE              32795
#define ID_EXTENSION_CODE               32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           142
#endif
#endif
