//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SDITest.rc
//
#define IDD_VIEWSCHNEIDERINTERCOM       103
#define IDR_MAINFRAME                   128
#define IDD_CONFIG_COM                  129
#define IDR_SDITESTYPE                  130
#define IDD_SDITEST_FORM                131
#define IDR_DTP                         132
#define IDD_DTP_FORM                    133
#define IDR_KEBA                        134
#define IDD_KEBA_FORM                   135
#define IDR_NCR                         136
#define IDD_NCR_FORM                    137
#define IDR_ENGEL                       138
#define IDD_ENGEL_FORM                  139
#define IDR_SNI                         140
#define IDD_SNI_FORM                    141
#define IDR_IBM                         142
#define IDD_IBM_FORM                    143
#define IDR_ASCOM                       143
#define IDD_GERMAN_PARCEL_FORM          144
#define IDR_GERMAN_PARCEL               145
#define IDR_NCR_NEW                     146
#define IDD_NCR_NEW_FORM                147
#define IDR_SNI_IBM_EMU                 148
#define IDD_STANDARD                    149
#define IDR_AV_CUSTOMER_SAFE            149
#define IDD_AVM_FORM                    150
#define IDR_SNI_COM                     150
#define IDR_KEBA_PASADOR                151
#define IDD_SNI_COM_FORM                153
#define IDD_KEBA_PASADOR                156
#define IDD_ASCOM                       162
#define IDD_RONDO                       163
#define IDR_RONDO                       164
#define IDD_DIALOGBANK                  166
#define IDR_DIALOGBANK                  167
#define IDR_FILE                        168
#define IDR_PM_100_IP_ALARM             169
#define IDD_CONFIG_IP                   170
#define IDR_PM_100_XML                  171
#define IDR_SCHNEIDER_INTERCOM          172
#define IDR_SDITESTYPE1                 172
#define IDC_TXT_COM_PORT                1000
#define IDC_RADIO_COM_1                 1001
#define IDC_RADIO_COM_2                 1002
#define IDC_RADIO_COM_3                 1003
#define IDC_RADIO_COM_4                 1004
#define IDC_TXT_PORT_NR                 1005
#define IDC_RADIO_COM_5                 1006
#define IDC_RADIO_PORT_NR_1             1007
#define IDC_RADIO_COM_6                 1008
#define IDC_RADIO_PORT_NR_2             1009
#define IDC_RADIO_COM_7                 1010
#define IDC_RADIO_PORT_NR_3             1011
#define IDC_RADIO_COM_8                 1012
#define IDC_RADIO_PORT_NR_4             1013
#define IDC_TXT_CAMERA                  1014
#define IDC_RADIO_CAMERA_NR_1           1015
#define IDC_RADIO_CAMERA_NR_2           1016
#define IDC_CHECK_REPEAT                1017
#define IDC_EDIT_REPEAT_TIME            1018
#define IDC_TXT_REPEAT_TIME             1019
#define IDC_RADIO_CHOSEN_UNITS          1020
#define IDC_CHECK_BIT_ERROR             1021
#define IDC_RADIO_RANDOM                1022
#define IDC_RADIO_SUCCESSIVE            1023
#define IDC_CHECK_LIMITED               1024
#define IDC_EDIT_LIMITED                1025
#define IDC_TXT_LIMITED                 1026
#define IDC_TXT_CARD_READER             1027
#define IDC_TXT_SEND_DELAY              1027
#define IDC_RADIO_CARD_READER_1         1028
#define IDC_RADIO_CARD_READER_2         1029
#define IDC_CHECK_BLZ                   1030
#define IDC_EDIT_BLZ                    1031
#define IDC_CHECK_KONTO                 1032
#define IDC_EDIT_KONTO                  1033
#define IDC_CHECK_BETRAG                1034
#define IDC_EDIT_BETRAG                 1035
#define IDC_CHECK_TAN                   1036
#define IDC_EDIT_TAN                    1037
#define IDC_RADIO_DIAGNOSE              1038
#define IDC_CHECK_DATE                  1039
#define IDC_CHECK_TIME                  1040
#define IDC_EDIT_DATE                   1041
#define IDC_EDIT_TIME                   1042
#define IDC_GROUP_REPEAT                1043
#define IDC_GROUP_EXPLICIT              1044
#define IDC_TXT_KOMMANDO                1045
#define IDC_RADIO_L_COMMAND             1046
#define IDC_RADIO_E_COMMAND             1047
#define IDC_RADIO_POINT_OF_DATA_1       1048
#define IDC_RADIO_POINT_OF_DATA_2       1049
#define IDC_RADIO_POINT_OF_DATA_3       1050
#define IDC_RADIO_POINT_OF_DATA_4       1051
#define IDC_RADIO_POINT_OF_DATA_5       1052
#define IDC_RADIO_POINT_OF_DATA_6       1053
#define IDC_RADIO_POINT_OF_DATA_7       1054
#define IDC_RADIO_POINT_OF_DATA_8       1055
#define IDC_TXT_COMMAND                 1056
#define IDC_RADIO_START_COMMAND         1057
#define IDC_GROUP_POINT_OF_DATA         1058
#define IDC_RADIO_POINT_OF_DATA_9       1059
#define IDC_RADIO_POINT_OF_DATA_10      1060
#define IDC_RADIO_POINT_OF_DATA_11      1061
#define IDC_RADIO_POINT_OF_DATA_12      1062
#define IDC_RADIO_POINT_OF_DATA_13      1063
#define IDC_RADIO_POINT_OF_DATA_14      1064
#define IDC_RADIO_POINT_OF_DATA_15      1065
#define IDC_RADIO_POINT_OF_DATA_16      1066
#define IDC_EDIT_DATA_FORMAT            1067
#define IDC_TXT_START                   1068
#define IDC_TXT_END                     1069
#define IDC_TXT_DATA_FORMAT             1070
#define IDC_TXT_LENGTH                  1071
#define IDC_EDIT_END                    1072
#define IDC_EDIT_LENGTH                 1073
#define IDC_EDIT_START                  1074
#define IDC_BTN_ACTUALIZE               1075
#define IDC_TXT_VARIANT                 1076
#define IDC_RADIO_VARIANT_1             1077
#define IDC_RADIO_VARIANT_2             1078
#define IDC_RADIO_POINT_OF_DATA_0       1079
#define IDC_RADIO_VARIANT_3             1080
#define IDC_CHECK_CURRENCY              1081
#define IDC_COMBO_CURRENCY              1082
#define IDC_EDIT2                       1083
#define IDC_EDIT_TCC                    1083
#define IDC_CHECK_WSID                  1084
#define IDC_EDIT_WSID                   1085
#define IDC_TXT_SAME_AND_NEW_TAN        1086
#define IDC_TXT_EVENT                   1087
#define IDC_RADIO_ACCESS                1088
#define IDC_RADIO_RELEASE               1089
#define IDC_CHECK_STATUS_REQUEST        1090
#define IDC_CHECK_WITH_TERMINAL_ID      1091
#define IDC_TXT_STATUS_REQUEST          1092
#define IDC_CHECK_SEND_SINGLE_BYTE      1093
#define IDC_TXT_DELAY                   1094
#define IDC_EDIT_SEND_DELAY             1097
#define IDC_RADIO_CHECK_ACCESS          1098
#define IDC_CHECK_FILE_BASED            1099
#define IDC_EDIT_FILENAME               1100
#define IDC_BTN_BROWSE                  1101
#define IDC_RADIO_STATUS_REQUEST        1102
#define IDC_RADIO_QUIET                 1103
#define IDC_RADIO_PORTRAIT              1104
#define IDC_RADIO_MONEY                 1105
#define IDC_RADIO_EC_CARD               1106
#define IDC_RADIO_TAN_CARD              1107
#define IDC_TXT_CARD_TYPE               1108
#define IDC_TXT_NAME                    1109
#define IDC_FILE                        1110
#define IDC_BROWSE                      1111
#define IDC_COM                         1112
#define IDC_RADIO_PORT_UPDATE           1113
#define IDC_RADIO_CAMERA_UPDATE_NULL    1114
#define IDC_RADIO_CAMERA_UPDATE_SPACE   1115
#define IDC_COMBO_IP_TYPE               1116
#define IDC_EDIT_PORT                   1117
#define IDC_IPADDRESS1                  1118
#define IDC_IPADDRESS                   1118
#define IDC_EDIT_BFR                    1119
#define IDC_COMBO_ALARM                 1120
#define IDC_EDIT_TNR                    1121
#define IDC_EDIT_SUBSCRIBER             1122
#define IDC_RADIO_ON                    1123
#define IDC_RADIO2                      1124
#define IDC_RADIO_OFF                   1124
#define IDC_COMBO_BAUDRATE              1372
#define IDC_STATIC_BAUDRATE             1373
#define IDC_STATIC_PARITY               1374
#define IDC_STATIC_DATABITS             1375
#define IDC_STATIC_STOPBITS             1376
#define IDC_COMBO_PARITY                1377
#define IDC_COMBO_DATABITS              1378
#define IDC_COMBO_STOPBITS              1379
#define IDP_NO_CONNECTION               10000
#define IDS_ACTIVE                      10001
#define IDS_INVALID_DATE                10002
#define IDS_INVALID_TIME                10003
#define IDS_CUSTOMER_ID                 10004
#define IDS_PROCESS_ID                  10005
#define IDS_FIRST_NAME                  10006
#define IDS_LAST_NAME                   10007
#define IDS_BOX_ID                      10008
#define IDS_DAT_FILTER                  10009
#define IDS_TITLE_COM_CONFIGURATION     10205
#define IDS_NOPARITY                    10206
#define IDS_ODDPARITY                   10207
#define IDS_EVENPARITY                  10208
#define IDS_MARKPARITY                  10209
#define IDS_SPACEPARITY                 10210
#define IDS_COM_PARAMS_CHANGED          10264
#define IDS_REOPEN_COM_AFTER_COM_PARAMS_CHANGED 10265
#define IDD_FILE_FORM                   30722
#define IDD_COM_CONFIGURATION           30723
#define IDD_PM100IPALARM_FORM           30724
#define IDD_PM100XML_FORM               30725
#define ID_SEND                         32771
#define ID_TRACE_RS232_HEX              32773
#define ID_TRACE_RS232_ASCII            32774
#define ID_STOP_SEND                    32775
#define ID_CONFIG_IP                    32776
#define ID_CONFIG_COM                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
