//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemVerwaltung.rc
//
#define IDR_MAINFRAME                   100
#define IDR_SYSTEMTYPE                  101
#define IDR_ICPCONPAGE                  101
#define IDB_IMAGES                      102
#define IDB_3STATE                      103
#define IDB_STATE                       104
#define IDB_RADIO                       105
#define IDD_TIMER_SPAN_EDITOR           106
#define IDD_TIMER_COMBI_EDITOR          107
#define IDD_ACTIVATION                  108
#define IDD_INPUTS                      109
#define IDD_OUTPUTS                     110
#define IDD_PROZ_SAVE                   111
#define IDD_OUTPUT                      112
#define IDD_USERLIST                    113
#define IDD_PROZ_ISDN                   114
#define IDD_HOSTLIST                    115
#define IDD_HARDWARE                    116
#define IDD_PERMISSIONLIST              117
#define IDD_PASSWORDCHECK               118
#define IDD_PASSWORD                    119
#define IDD_SOFTWARE                    120
#define IDD_INPUT_SELECT                124
#define IDD_SIM                         125
#define IDD_ISDN                        126
#define IDD_SOCKET                      127
#define IDD_RS232                       128
#define IDD_GAA                         129
#define IDD_STM                         130
#define IDD_MESZ                        131
#define IDD_SDI                         132
#define IDD_INPUT                       133
#define IDD_RELAY                       134
#define IDD_RELAYS                      135
#define IDD_SDI_ONE                     136
#define IDD_APP                         137
#define IDD_PTUNIT                      138
#define IDD_NTLOGON                     139
#define IDD_INFORMATION                 140
#define IDD_SDI_CONFIGURATION           141
#define IDD_SPECIAL_CHARACTERS          143
#define IDD_COM_CONFIGURATION           144
#define IDB_UP                          145
#define IDD_NOTIFICATION                146
#define IDD_ARCHIV                      147
#define IDB_DOWN                        148
#define IDD_DRIVE                       149
#define IDB_HOT                         150
#define IDD_TIMEREDITOR                 151
#define IDB_COLD                        152
#define IDD_TIMER_SET_DIALOG            153
#define IDB_ARCHIVE                     154
#define IDB_DRIVES                      155
#define IDD_SMS                         156
#define IDD_TIMER_TEST                  157
#define IDD_REMOTE                      158
#define IDD_SECURITY                    159
#define IDD_TIMER_IMPORT                160
#define IDD_PROZ_BACKUP                 161
#define IDR_AVI_READ_SAMPLE             162
#define IDD_PROZ_ACTUAL_IMAGE           163
#define IDR_AVI_READ_SAMPLE_STOPPED     164
#define IDD_PROZ_IMAGE_CALL             165
#define IDD_PROZ_CHECK_CALL             166
#define IDD_JACOB                       167
#define IDD_GEMOS                       168
#define IDD_SAVIC                       169
#define IDD_EMAIL                       170
#define IDD_TOBS                        171
#define IDD_DEF_TREE_KNODE              172
#define IDD_PROPPAGE_VARIABLE           173
#define IDD_WIZARD_CREATOR              174
#define IDD_PROZ_GUARD_TOUR             175
#define IDD_ICPCON_PAGE                 176
#define IDD_MULTI_MONITOR_PAGE          177
#define IDD_SDI_DEFAULT_MICROLOCK       178
#define IDD_YUTA                        179
#define IDD_PROZ_VIDEO_OUT              180
#define IDD_AUDIO                       181
#define IDB_TREE_STATE_MULT             182
#define IDD_DATABASE_FIELDS             183
#define IDD_IP_CAMERA                   184
#define IDD_AUDIO_CHANNELS              185
#define IDD_AUDIO_CHANNEL               186
#define IDD_TASHA                       187
#define IDD_PTZ_CONFIG_DLG              188
#define IDD_SDI_STAR_INTERFACE          189
#define IDD_JOYSTICK                    190
#define IDD_LANGUAGE_DEFS               191
#define IDD_QUAD                        192
#define IDD_MAP_NETWORK_DRIVE           193
#define IDD_MAINTENANCE                 194
#define IDD_IP_CONFIGURATION            195
#define IDD_SDI_ALARM_NUMBERS           196
#define IDD_PROZ_UPLOAD                 197
#define IDD_MISCELLANEOUS_PAGE          198
#define IDD_WIZ_DESIGNA                 199
#define IDD_QUNIT                       200
#define IDC_RESOLUTION                  1000
#define IDC_TIMER_LIST                  1001
#define IDC_RUFNUMMER                   1002
#define IDC_EDIT_TYPE_INPUT             1003
#define IDC_TXT_TIMER_NAME              1004
#define IDC_LIST_USER                   1005
#define IDC_TIMER_SELECTED_NAME         1006
#define IDC_NR_INPUT                    1007
#define IDC_TXT_TIMER_LOCKS             1008
#define IDC_COMPRESSION                 1009
#define IDC_RADIO_TIMER_TYPE_SPAN       1010
#define IDC_BUTTON_COM_SETTINGS         1010
#define IDC_RADIO_TIMER_TYPE_COMBINATION 1011
#define IDC_SCROLLBAR                   1012
#define IDC_CHECK_SYNC                  1013
#define IDC_TIMER_GRP_DUMMY             1014
#define IDC_CHECK_COCO                  1015
#define IDC_TIMER_SPAN_LIST             1016
#define IDC_CHECK_GLOBAL_COLORS         1017
#define IDC_SPAN_EDIT                   1018
#define IDC_EDGE                        1019
#define IDC_SPAN_REMOVE                 1020
#define IDC_IRQ_COCO                    1021
#define IDC_SPAN_ADD                    1022
#define IDC_DO_LISTEN                   1023
#define IDC_ADDRESS_COCO                1024
#define IDC_HOURTABLE                   1025
#define IDC_DO_BEEP_ON_INCOMING         1026
#define IDC_TIMER_COMBI_SOURCE          1027
#define IDC_CHECK_COCO2                 1028
#define IDC_TIMER_COMBI_SOURCE_BLOCKED  1029
#define IDC_TIMER_COMBI_INCLUDE         1030
#define IDC_USE_DNS                     1031
#define IDC_TIMER_COMBI_RESRTICT        1032
#define IDC_TXT_NOTFOREVER              1033
#define IDC_TIMER_COMBI_EXCLUDE         1034
#define IDC_ADDRESS_COCO2               1035
#define IDC_TXT_TIMER_COMBI_SOURCE      1036
#define IDC_DO_CACHE_KNOWN_NAMES        1037
#define IDC_TXT_TIMER_COMBI_SOURCE_BLOCKED 1038
#define IDC_TXT_TIMER_COMBI_INCLUDE     1039
#define IDC_TXT_SEC1                    1040
#define IDC_TXT_TIMER_COMBI_RESTRICT    1041
#define IDC_CHECK_COCO3                 1042
#define IDC_BUTTON_TIMER_COMI_INCLUDE   1043
#define IDC_DO_CACHE_UNKNOWN_NAMES      1044
#define IDC_TXT_TIMER_COMBI_EXCLUDE     1045
#define IDC_TXT_SEC2                    1046
#define IDC_BUTTON_TIMER_COMI_RESTRICT  1047
#define IDC_ADDRESS_COCO3               1048
#define IDC_BUTTON_TIMER_COMI_EXCLUDE   1049
#define IDC_TXT_INCOMING_SETTINGS       1050
#define IDC_BUTTON_TIMER_COMI_BACK      1051
#define IDC_TIMER_SET_TYPE_WEEK_DAY     1052
#define IDC_TXT_DNS                     1053
#define IDC_TIMER_SET_TYPE_DATE         1054
#define IDC_TXT_RECTIME                 1055
#define IDC_TXT_EXTENDED_OPTIONS        1056
#define IDC_TXT_NR                      1057
#define IDC_TXT_PROCESSOR_USAGE         1058
#define IDC_USAGE_HIGH                  1059
#define IDC_TXT_SEC0                    1060
#define IDC_COMBO_CLIENT_EDGE           1061
#define IDC_TXT_SEC3                    1061
#define IDC_TIMER_WEEK_DAY_COMBO        1062
#define IDC_USAGE_MEDIUM                1063
#define IDC_TIMER_DAY                   1064
#define IDC_TXT_VISION                  1065
#define IDC_TIMER_MONTH                 1066
#define IDC_USAGE_LOW                   1067
#define IDC_TIMER_YEAR                  1068
#define IDC_TXT_EDGE                    1069
#define IDC_TIMER_TXT_FOR_TIMER_LABEL   1070
#define IDC_CHECK_CLIENT_BREAK          1071
#define IDC_TXT_TIMER_SET_NAME_LABEL    1072
#define IDC_TXT_NAME                    1073
#define IDC_CHECK_CLIENT_KEEP           1074
#define IDC_TXT_KEEP                    1075
#define IDC_BUTTON_ALARM                1076
#define IDC_TIMER_PLUS_ICON             1077
#define IDC_PRODUCT                     1078
#define IDC_TIMER_DIV_ICON              1079
#define IDC_TIMER_TEXT_DAY_DELIMITER    1080
#define IDC_VERSION                     1081
#define IDC_TIMER_MINUS_ICON            1082
#define IDC_TIMER_TEXT_DAY_DELIMITER2   1083
#define IDC_VER                         1084
#define IDC_COMBO_PROT                  1085
#define IDC_TIMER_HRULE                 1086
#define IDC_TIMER_TXT_DAY               1087
#define IDC_CHECK_LOGIN                 1088
#define IDC_TIMER_TXT_MONTH             1089
#define IDC_TXT_SDI                     1090
#define IDC_TIMER_TXT_YEAR              1091
#define IDC_TXT_ON                      1092
#define IDC_ALLOW_OUTGOING_CALLS        1093
#define IDC_TIMER_HOURS_TEXT            1094
#define IDC_TXT_PROT                    1095
#define IDC_TXT_SYNC_RETRY_TIME         1096
#define IDC_ENABLE_KNOCK_BOX            1097
#define IDC_GRP_VERSION                 1098
#define IDC_SYNC_RETRY_TIME             1099
#define IDC_TXT_COMMENT                 1100
#define IDC_GRP_APP                     1101
#define IDC_NAME_INPUT                  1102
#define IDC_TXT_AUTO_APP                1103
#define IDC_TXT_CONF_APP                1104
#define IDC_EDIT_AUTO_APP               1105
#define IDC_TXT_SELECTED_BITRATE        1106
#define IDC_EDIT_CONF_APP               1107
#define IDC_RADIO_512_KB                1108
#define IDC_CHECK_APP                   1109
#define IDC_RADIO_256_KB                1110
#define IDC_GRP_CONNECTION              1111
#define IDC_RADIO_128_KB                1112
#define IDC_CHECK_CONN                  1113
#define IDC_RADIO_64_KB                 1114
#define IDC_TXT_AUTO_CONN               1115
#define IDC_STATIC_PTUNIT               1116
#define IDC_TXT_CONF_CONN               1117
#define IDC_CHECK_PTUNIT                1118
#define IDC_EDIT_AUTO_CONN              1119
#define IDC_CHECK_BACKUP                1120
#define IDC_EDIT_CONF_CONN              1121
#define IDC_RADIO_NR                    1122
#define IDC_RADIO_ALL                   1123
#define IDC_RADIO_NOTHING               1124
#define IDC_CHECK_MSN                   1125
#define IDC_NR_RELAY                    1126
#define IDC_RADIO_B1                    1127
#define IDC_RADIO_B2                    1128
#define IDC_EDIT_COMMENT                1129
#define IDC_CHECK_SDICONFIG             1130
#define IDC_GRP_NT                      1131
#define IDC_TXT_DOMAIN                  1132
#define IDC_TXT_USER                    1133
#define IDC_TXT_PASSWORD                1134
#define IDC_EDIT_DOMAIN                 1135
#define IDC_EDIT_USER                   1136
#define IDC_CHECK_SHUTDOWN              1137
#define IDC_TXT_INFORMATION_0           1138
#define IDC_TXT_INFORMATION_1           1139
#define IDC_TXT_INPUT                   1140
#define IDC_TXT_OFFICIAL                1141
#define IDC_INFORMATION                 1142
#define IDC_EDITOR                      1143
#define IDC_INSTRUCTION                 1144
#define IDC_SN                          1145
#define IDC_RADIO_PAL_CCIR              1146
#define IDC_RADIO_PAL_SQUARE            1147
#define IDC_RADIO_NTSC_CCIR             1148
#define IDC_RADIO_NTSC_SQUARE           1149
#define IDC_CHECK_MICO_PCI              1150
#define IDC_CHECK_USE2FIELDS            1151
#define IDC_BUTTON_CONFIGURATE_PROTOCOL 1152
#define IDC_GROUP_KIND_OF_IDENTIFIER    1153
#define IDC_RADIO_POS_LEN               1154
#define IDC_RADIO_IDENTIFY_TAG          1155
#define IDC_RADIO_SEPERATOR             1156
#define IDC_GROUP_ORDER                 1157
#define IDC_CHECK_DCF                   1158
#define IDC_LIST_OUTPUTS                1159
#define IDC_GRP_FIELDMAP                1160
#define IDC_CHECK_KTONR                 1161
#define IDC_TXT_CALLTIME                1162
#define IDC_TXT_ORIG                    1163
#define IDC_CALLTIME                    1164
#define IDC_TXT_MAP                     1165
#define IDC_CHECK_BETRAG                1166
#define IDC_CHECK_GANR                  1167
#define IDC_CHECK_TANR                  1168
#define IDC_CHECK_BLZ                   1169
#define IDC_CHECK_DTP_ZEIT              1170
#define IDC_EDIT_KTONR                  1171
#define IDC_EDIT_BETRAG                 1172
#define IDC_EDIT_GANR                   1173
#define IDC_EDIT_TANR                   1174
#define IDC_EDIT_BLZ                    1175
#define IDC_TXTACTIVATE                 1176
#define IDC_EDIT_DTP_TIME               1177
#define IDC_TXTEDGE                     1178
#define IDC_BUTTON_STANDARD             1179
#define IDC_TXTCOMMENT                  1180
#define IDC_TXTNR                       1181
#define IDC_LIST_PROTOCOL               1182
#define IDC_BUTTON_PROTOCOL_NEW         1183
#define IDC_TXTRESOLUTION               1184
#define IDC_BUTTON_PROTOCOL_DELETE      1185
#define IDC_TXTCOMPRESSION              1186
#define IDC_TXT_OUTPUTTYP               1187
#define IDC_TXT_OUTPUTCOMMENT           1188
#define IDC_LIST_DATA                   1189
#define IDC_ISDN_MAINTIME               1190
#define IDC_TXTPAUSE                    1191
#define IDC_EDIT_NAME                   1192
#define IDC_ISDN_PAUSETIME              1193
#define IDC_GROUP_DIFFERENCES           1194
#define IDC_RECTIME                     1195
#define IDC_CHECK_DIFFERENCE_TOTAL_LENGTH 1196
#define IDC_EDIT_DIFFERENCE_TOTAL_LENGTH 1197
#define IDC_ISDN_HOLD                   1198
#define IDC_CHECK_DIFFERENCE_STRING_AT_POSITION 1199
#define IDC_EDIT_DIFFERENCE_STRING_AT_POSITION 1200
#define IDC_EDIT_DIFFERENCE_POSITION_OF_STRING 1201
#define IDC_TXT_DATATYPE                1202
#define IDC_TXT_POSITION                1203
#define IDC_TXT_LENGTH                  1204
#define IDC_TXT_SEPERATOR               1205
#define IDC_TXT_TAG                     1206
#define IDC_TXT_DATA_FORMAT             1207
#define IDC_COMBO_DATA_TYPE             1208
#define IDC_EDIT_POSITION               1209
#define IDC_INTERVALGRP                 1210
#define IDC_EDIT_TAG                    1211
#define IDC_GESTIMEGRP                  1212
#define IDC_COMBO_DATA_FORMAT           1213
#define IDC_ISDN_INTERVAL               1214
#define IDC_ISDN_FOREVER                1215
#define IDC_BUTTON_DATA_NEW             1216
#define IDC_BUTTON_DATA_DELETE          1217
#define IDC_RADIO_ORDER_LEFT            1218
#define IDC_TXT_OUTPUTSN                1219
#define IDC_RADIO_ORDER_RIGHT           1220
#define IDC_TXT_OUTPUTNR                1221
#define IDC_EDIT_DATA_LENGTH            1222
#define IDC_CHECK_DATA_LENGTH_VARIABLE  1223
#define IDC_LIST_HOST                   1224
#define IDC_CHECK_COCO1                 1225
#define IDC_TXT_GAA                     1226
#define IDC_COMBO_PERMISSION            1227
#define IDC_CHECK_MICO_ISA              1228
#define IDC_CHECK_GAA                   1229
#define IDC_LIST_PERMISSION             1230
#define IDC_CHECK_EXTCARD_1             1231
#define IDC_CHECK_EXTCARD_2             1232
#define IDC_LIST_ARCHIVS                1233
#define IDC_CHECK_EXTCARD_3             1234
#define IDC_EDIT_PASSWORD               1235
#define IDC_EDIT_PASSWORD1              1236
#define IDC_EDIT_PASSWORD2              1237
#define IDC_PASSWORD                    1238
#define IDC_ADDRESS_COCO1               1239
#define IDC_ADDRESS_MICO                1240
#define IDC_CHECK_HARDWARE              1241
#define IDC_CHECK_INPUT                 1242
#define IDC_CHECK_OUTPUT                1243
#define IDC_ADDRESS_EXTCARD_1           1244
#define IDC_CHECK_TIMER                 1245
#define IDC_CHECK_PROZESS               1246
#define IDC_ADDRESS_EXTCARD_2           1247
#define IDC_CHECK_LINK                  1248
#define IDC_CHECK_USER                  1249
#define IDC_ADDRESS_EXTCARD_3           1250
#define IDC_CHECK_PERMISSION            1251
#define IDC_CHECK_HOST                  1252
#define IDC_CHECK_ARCHIV                1253
#define IDC_SAVE_NAME                   1254
#define IDC_SAVE_LIST_PROCESS           1255
#define IDC_SAVE_HOLD                   1256
#define IDC_SAVE_INTERVAL               1257
#define IDC_SAVE_PAUSETIME              1258
#define IDC_SAVE_FOREVER                1259
#define IDC_SAVE_MAINTIME               1260
#define IDC_ISDN_NAME                   1261
#define IDC_ISDN_LIST_PROCESS           1262
#define IDC_NR_PICTURE                  1263
#define IDC_COM_GAA                     1264
#define IDC_TXT_COM_GAA                 1265
#define IDC_CHECK_SIMUNIT               1266
#define IDC_LIST_ACTIVATION             1267
#define IDC_IRQ_MICO                    1268
#define IDC_LIST_TIMER                  1269
#define IDC_LIST_OUTPUT                 1270
#define IDC_LIST_PROCESS                1271
#define IDC_GROUP_STATE                 1272
#define IDC_GROUP_PRIORITY              1273
#define IDC_RADIO_STATE_OFF             1274
#define IDC_RADIO_STATE_OK              1275
#define IDC_RADIO_STATE_ALARM           1276
#define IDC_RADIO_PRIORITY_1            1277
#define IDC_RADIO_PRIORITY_2            1278
#define IDC_RADIO_PRIORITY_3            1279
#define IDC_RADIO_PRIORITY_4            1280
#define IDC_RADIO_PRIORITY_5            1281
#define IDC_INPUT_LIST                  1282
#define IDC_COMBO_PRIORITY              1283
#define IDC_ARCHIVS                     1284
#define IDC_NOTIFICATIONS               1285
#define IDC_COM_CAMERA                  1286
#define IDC_MANUFACTURER                1287
#define IDC_ARCHIVS2                    1287
#define IDC_EDIT_CLOSE_RELAY            1288
#define IDC_CHECK_RS232                 1289
#define IDC_COMBO_RS232                 1290
#define IDC_STATIONS_NAME               1291
#define IDC_CHECK_DISTURB               1292
#define IDC_CHECK_SOCKET                1293
#define IDC_CHECK_AKU1                  1294
#define IDC_ADDRESS_AKU1                1295
#define IDC_CHECK_AKU2                  1296
#define IDC_CHECK_AKU3                  1297
#define IDC_CHECK_AKU4                  1298
#define IDC_ADDRESS_AKU2                1299
#define IDC_ADDRESS_AKU3                1300
#define IDC_ADDRESS_AKU4                1301
#define IDC_CHECK_ISDN                  1302
#define IDC_TXT_COM                     1303
#define IDC_TXT_MANU                    1304
#define IDC_TXT_RELAY_CLOSE             1305
#define IDC_EDIT_ID                     1306
#define IDC_TXT_ID                      1307
#define IDC_STATIC_NAME                 1308
#define IDC_STATIC_PERMISSION           1309
#define IDC_STATIC_NUMBER               1310
#define IDC_STATIC_OWN_NAME             1311
#define IDC_STATIC_CC                   1312
#define IDC_STATIC_MC                   1313
#define IDC_STATIC_SM                   1314
#define IDC_STATIC_SU                   1315
#define IDC_STATIC_ISDN                 1316
#define IDC_STATIC_AKU                  1317
#define IDC_STATIC_RS                   1318
#define IDC_STATIC_IRQ_CC               1319
#define IDC_STATIC_ADR_CC               1320
#define IDC_STATIC_ADR_AKU              1321
#define IDC_STATIC_COM                  1322
#define IDC_STATIC_IRQ_MC               1323
#define IDC_STATIC_ADR_MC               1324
#define IDC_STATIC_SOCKET               1325
#define IDC_STATIC_PM                   1326
#define IDC_STATIC_OUT                  1327
#define IDC_STATIC_EDIT                 1328
#define IDC_STATIC_PRIORITY             1329
#define IDC_STATIC_BI                   1330
#define IDC_STATIC_ARCHIV               1331
#define IDC_STATIC_OLD_PW               1332
#define IDC_STATIC_PW                   1333
#define IDC_STATIC_NEW_PW               1334
#define IDC_STATIC_REPEAT               1335
#define IDC_STATIC_TIMER                1336
#define IDC_STATIC_PROCESS              1337
#define IDC_STATIC_CHOOSE               1338
#define IDC_STATIC_IN                   1339
#define IDC_TXT_NOTIFICATION            1340
#define IDC_TXT_ARCHIV                  1341
#define IDC_TXT_PROCESS                 1342
#define IDC_TXT_PERMISSION              1343
#define IDC_TXT_HOSTS                   1344
#define IDC_TXT_CALLHOSTS               1345
#define IDC_TXT_TYP                     1346
#define IDC_COMBO_TYPE_HOST             1347
#define IDC_GRP_MEZ                     1348
#define IDC_CHECK_MEZ                   1349
#define IDC_SOMMER                      1350
#define IDC_WINTER                      1351
#define IDC_WDAY                        1352
#define IDC_SDAY                        1353
#define IDC_WMONTH                      1354
#define IDC_SMONTH                      1355
#define IDC_COMBO_WMONTH                1356
#define IDC_COMBO_SMONTH                1357
#define IDC_EDIT_SEPERATOR              1358
#define IDC_BUTTON_SPECIAL_CHARACTERS_SEPERATOR 1359
#define IDC_LIST_SPECIAL_CHARACTERS     1360
#define IDC_EDIT_SAMPLE_STRING          1361
#define IDC_BUTTON_DATA_UP              1362
#define IDC_BUTTON_DATA_DOWN            1363
#define IDC_BUTTON_PROTOCOL_UP          1364
#define IDC_BUTTON_PROTOCOL_DOWN        1365
#define IDC_TCPIP_TEST                  1366
#define IDC_TXT_TCPIP_TEST_LABEL        1367
#define IDC_TXT_TCPIP_TEST_RESULT       1368
#define IDC_STATIC_PROTOCOL             1369
#define IDC_STATIC_DATA                 1370
#define IDC_BUTTON_CONFIGURATE_COM      1371
#define IDC_COMBO_BAUDRATE              1372
#define IDC_STATIC_BAUDRATE             1373
#define IDC_STATIC_PARITY               1374
#define IDC_STATIC_DATABITS             1375
#define IDC_STATIC_STOPBITS             1376
#define IDC_COMBO_PARITY                1377
#define IDC_COMBO_DATABITS              1378
#define IDC_COMBO_STOPBITS              1379
#define IDC_EDIT_SAMPLE_READ            1380
#define IDC_BUTTON_SAMPLE_TAKEOVER      1381
#define IDC_RADIO_8MBIT                 1382
#define IDC_RADIO_4MBIT                 1383
#define IDC_RADIO_2MBIT                 1384
#define IDC_RADIO_1MBIT                 1385
#define IDC_TIMER_LOCKS                 1386
#define IDC_NOTIFICATION                1387
#define IDC_EDIT_MESSAGE                1388
#define IDC_EDIT_URL                    1389
#define IDC_BUTTON_BROWSE               1390
#define IDC_RADIO_MESSAGE               1391
#define IDC_RADIO_URL                   1392
#define IDC_ARCHIVE                     1393
#define IDC_RADIO_RING                  1394
#define IDC_RADIO_ALARM                 1395
#define IDC_RADIO_SAFERING              1396
#define IDC_STATIC_SIZE                 1397
#define IDC_EDIT_SIZE                   1398
#define IDC_STATIC_MB                   1399
#define IDC_COMBO_ALARM                 1400
#define IDC_STATIC_MAX                  1401
#define IDC_STATIC_MAX_MB               1402
#define IDC_STATIC_FREE                 1403
#define IDC_STATIC_WHOLE                1404
#define IDC_STATIC_USED_MB              1405
#define IDC_STATIC_WHOLE_MB             1406
#define IDC_TXT_USED                    1407
#define IDC_STATIC_SLASH                1408
#define IDC_DRIVES                      1409
#define IDC_RADIO_SAFERING2             1409
#define IDC_RADIO_ALARM_LIST            1409
#define IDC_RADIO_SYSTEM                1410
#define IDC_RADIO_NORMAL                1411
#define IDC_RADIO_DATABASE              1412
#define IDC_RADIO_BACKUP_WRITE_READ     1413
#define IDC_RADIO_BACKUP_READ           1414
#define IDC_TXT_SIZE                    1415
#define IDC_TXT_MB                      1416
#define IDC_GROUP_USE                   1417
#define IDC_TXT_DRIVE                   1418
#define IDC_STATIC_DRIVE                1419
#define IDC_TXT_USE                     1420
#define IDC_EDIT_USE                    1421
#define IDC_TXT_MB2                     1422
#define IDC_GROUP_TYP                   1423
#define IDC_TXT_FIXED_DRIVE             1424
#define IDC_TXT_SIZE2                   1425
#define IDC_COMBO_FIXED_DRIVE           1426
#define IDC_TXT_MB3                     1427
#define IDC_GROUP_PROPERTIES            1428
#define IDC_GROUP_DRIVE                 1429
#define IDC_GROUP_SIZE                  1430
#define IDC_STATIC_DRIVES_MB            1431
#define IDC_STATIC_ARCHIVS_MB           1432
#define IDC_ALL                         1433
#define IDC_BUTTON_SPECIAL_CHARACTERS_IDENTIFY_STRING 1434
#define IDC_BUTTON_DEFAULT              1435
#define IDC_GRP_SMS                     1436
#define IDC_TXT_D1                      1437
#define IDC_TXT_D2                      1438
#define IDC_EDIT_D1                     1439
#define IDC_TXT_EPLUS                   1440
#define IDC_EDIT_D2                     1441
#define IDC_EDIT_EPLUS                  1442
#define IDC_CHECK_SMS                   1443
#define IDC_TXT_PREFIX                  1444
#define IDC_EDIT_PREFIX                 1445
#define IDC_LIST_SAMPLE                 1446
#define IDC_TIMER_IMPORT_DUPLICATES     1447
#define IDC_TIMERTEST_TIMER_LIST        1448
#define IDC_TIMER_DO_TEST               1449
#define IDC_TIMER_IMPORT                1450
#define IDC_TIMER_TEST_DATEPICKER       1451
#define IDC_TIMER_EXPORT                1452
#define IDC_TIMER_TEST_TIMEPICKER       1453
#define IDC_CHECK_DATA_EXPORT           1454
#define IDC_TXT_COPYRIGHT_LUCA          1455
#define IDC_TXT_HOST                    1456
#define IDC_HOST                        1457
#define IDC_TXT_STATE                   1458
#define IDC_STATE                       1459
#define IDC_PROGRESS                    1460
#define IDC_TXT_MIN_PASSWORD            1461
#define IDC_EDIT_MIN_PASSWORD           1462
#define IDC_TXT_MIN_ALPHA               1463
#define IDC_TXT_MIN_NUMERIC             1464
#define IDC_TXT_TIME_LIMIT              1465
#define IDC_EDIT_MIN_ALPHA              1466
#define IDC_EDIT_MIN_NUMERIC            1467
#define IDC_EDIT_TIME_LIMIT             1468
#define IDC_GRP_SECURITY                1469
#define IDC_EDIT_MAX_FAILED             1470
#define IDC_EDIT_FAILED_LOCK            1471
#define IDC_CHECK_DOPPEL_LOGIN          1472
#define IDC_TXT_IMPORT_WARNING          1473
#define IDC_CHECK_SETTINGS              1474
#define IDC_CHECK_SECURITY              1475
#define IDC_CHECK_LOGVIEW               1476
#define IDC_CHECK_DATETIME              1477
#define IDC_TXT_CURRENCY                1478
#define IDC_COMBO_CURRENCY              1479
#define IDC_LINE_1                      1480
#define IDC_LINE_2                      1481
#define IDC_LINE_3                      1482
#define IDC_TXT_SAMPLE_DATA             1483
#define IDC_CHECK_READ_SAMPLE           1484
#define IDC_BUTTON_PORTRAIT             1485
#define IDC_BUTTON_MONEY                1486
#define IDC_STATIC_CURRENCY             1487
#define IDC_STATIC_BACKUP               1488
#define IDC_ARCHIV                      1489
#define IDC_COMBO_ARCHIV                1490
#define IDC_CHECK_DELETE                1491
#define IDC_COMBO_DRIVE                 1492
#define IDC_EDIT_BACKUP_NAME            1493
#define IDC_LIST_BACKUP_PROCESS         1494
#define IDC_CHECK_DTP_DATE              1495
#define IDC_EDIT_DTP_DATE               1496
#define IDC_EDIT_TYPE_RELAY             1497
#define IDC_EDIT_TYPE_CAMERA            1498
#define IDC_COM_SDI                     1499
#define IDC_NAME_RELAY                  1500
#define IDC_NAME_CAMERA                 1501
#define IDC_CHECK_SDI                   1502
#define IDC_NAME_HOST                   1503
#define IDC_NAME_PERMISSION             1504
#define IDC_NAME_USER                   1505
#define IDC_NAME_NOTIFICATION           1506
#define IDC_NAME_ARCHIV                 1507
#define IDC_NAME_BACKUP                 1508
#define IDC_EDIT_TPWL                   1509
#define IDC_HOST_LIST                   1510
#define IDC_REJECT_WITHOUT_NUMBER       1511
#define IDC_USE_HOSTLIST                1512
#define IDC_USE_TPWL                    1513
#define IDC_USE_IPHOSTLIST              1514
#define IDC_EDIT_IPHOSTLIST             1515
#define IDC_NR_OUTPUT                   1516
#define IDC_ADDRESS_HOST                1517
#define IDC_COMBO_PERMISSION_ISDN       1518
#define IDC_ISDN_LIST_HOST_ALL          1519
#define IDC_ISDN_LIST_HOST_CALL         1520
#define IDC_CHECK_COCO_SOFT             1521
#define IDC_CHECK_IMAGECOMPARE          1522
#define IDC_ANIMATE_READ_SAMPLE         1523
#define IDC_STATIC_AI                   1524
#define IDC_STATIC_RES                  1525
#define IDC_STATIC_COMP                 1526
#define IDC_COMBO_RES                   1527
#define IDC_COMBO_COMP                  1528
#define IDC_STATIC_IC                   1529
#define IDC_CHECK_JACOB                 1537
#define IDC_CHECK_JACOB2                1538
#define IDC_CHECK_JACOB_GLOBAL_COLORS   1547
#define IDC_CHECK_JACOB_SYNC            1548
#define IDC_CHECK_JACOB_USE2FIELDS      1549
#define IDC_RADIO_JACOB_PAL_CCIR        1550
#define IDC_RADIO_JACOB_PAL_SQUARE      1551
#define IDC_RADIO_JACOB_NTSC_CCIR       1552
#define IDC_RADIO_JACOB_NTSC_SQUARE     1553
#define IDC_COPY_ISDN_HOSTS             1554
#define IDC_COPY_TCP_LIST               1555
#define IDC_CHECK_REFERENCE             1556
#define IDC_TXT_REFERENCE               1557
#define IDC_CHECK_TIME                  1558
#define IDC_MD_CONFIG                   1559
#define IDC_CHECK_MD_ON                 1560
#define IDC_TXT_GEMOS                   1561
#define IDC_COM_PARAMETER               1562
#define IDC_COM_GEMOS                   1563
#define IDC_CHECK_GEMOS                 1564
#define IDC_EDIT_FUNKUHR                1565
#define IDC_STATIC_FUNKUHR              1566
#define IDC_STATIC_VIDNORM              1567
#define IDC_STATIC_REJECT               1568
#define IDC_STATIC_B_CHANNELS           1569
#define IDC_STATIC_VLINE                1570
#define IDC_STATIC_PT_REJECT            1571
#define IDC_STATIC_LOGIN_FAILED_COUNT   1572
#define IDC_STATIC_LOCK                 1573
#define IDC_STATIC_JACOB_VID_NORM       1574
#define IDC_HOST_ARCHIVES               1575
#define IDC_GRP_EMAIL                   1576
#define IDC_TXT_VERBINDUNG              1577
#define IDC_RADIO_LAN                   1578
#define IDC_RADIO_DFUE                  1579
#define IDC_EDIT_DFUE                   1580
#define IDC_TEXT_DFUE                   1581
#define IDC_EDIT_SMTP                   1582
#define IDC_TEXT_SMTP                   1583
#define IDC_TEXT_MAILSERVER             1583
#define IDC_EDIT_PORT                   1584
#define IDC_TEXT_PORT                   1585
#define IDC_CHECK_EMAIL                 1586
#define IDC_COMBO_DFUE                  1587
#define IDC_EDIT_EMAIL                  1588
#define IDC_TEXT_EMAIL                  1589
#define IDC_EDIT_POPSERVER              1590
#define IDC_TEXT_POPSERVER              1591
#define IDC_GRP_DFUE                    1592
#define IDC_TEXT_USER                   1593
#define IDC_TEXT_PASSWD                 1594
#define IDC_GRP_POP                     1595
#define IDC_CHECK_POP3                  1596
#define IDC_EDIT_POP_USERNAME           1597
#define IDC_EDIT_POP_PASSWORD           1598
#define IDC_STATIC_TOBS                 1599
#define IDC_TEXT_POPPORT                1599
#define IDC_EDIT_POPPORT                1600
#define IDC_CHECK_TOBS                  1601
#define IDC_TXT_PREFIX_MINIMUM          1602
#define IDC_EDIT_PREFIX_MINIMUM         1603
#define IDC_TEXT_POPUSER                1604
#define IDC_TEXT_POPPASSWD              1605
#define IDC_GRP_SMTP                    1606
#define IDC_CHECK_ALARM_OFF_SPAN        1607
#define IDC_TXT_DEACTIVATE              1608
#define IDC_DEACTIVATE                  1609
#define IDC_CHECK_TXT_MSN               1610
#define IDC_EDIT_DFUE_USER              1611
#define IDC_EDIT_DFUE_PASSWORD          1612
#define IDC_COMBO_PERMISSION_PROCESS    1613
#define IDC_DEF_GROUP                   1614
#define IDC_DEF_TEXT                    1616
#define IDC_DEF_TEXT2                   1617
#define IDC_SOFT_TEXT                   1618
#define IDC_SPIN_TYPE_CAMERA            1619
#define IDC_STATIC_TYPE_CAMERA          1620
#define IDC_SPIN_TYPE_RELAY             1621
#define IDC_STATIC_TYPE_RELAY           1622
#define IDC_SPIN_TYPE_INPUT             1623
#define IDC_STATIC_TYPE_INPUT           1624
#define IDC_STATIC_TEST                 1625
#define IDC_STAT_PPVAR_TEXT             1627
#define IDC_STATIC_WIZARD_NAME          1629
#define IDC_EDT_WIZARD_NAME             1630
#define IDC_STATIC_WIZARD_TITLE         1631
#define IDC_EDT_WIZARD_TITLE            1632
#define IDC_STATIC_WIZARD_STATUS_TEXT   1633
#define IDC_EDT_WIZARD_STATUS_TEXT      1634
#define IDC_DEF_ITEM0                   1635
#define IDC_DEF_ITEM1                   1636
#define IDC_DEF_ITEM2                   1637
#define IDC_DEF_ITEM3                   1638
#define IDC_DEF_ITEM4                   1639
#define IDC_DEF_ITEM5                   1640
#define IDC_DEF_ITEM6                   1641
#define IDC_DEF_ITEM7                   1642
#define IDC_DEF_ITEM8                   1643
#define IDC_DEF_ITEM9                   1644
#define IDC_DEF_ITEM10                  1645
#define IDC_STATIC_PT1                  1646
#define IDC_STATIC_PT2                  1647
#define IDC_STATIC_PT3                  1648
#define IDC_STATIC_PT4                  1649
#define IDC_STATIC_PT5                  1650
#define IDC_STATIC_PT6                  1651
#define IDC_STATIC_PT7                  1652
#define IDC_STATIC_PT8                  1653
#define IDC_STATIC_PT9                  1654
#define IDC_STATIC_PT10                 1655
#define IDC_STATIC_PT11                 1656
#define IDC_RADIO_AUTO                  1657
#define IDC_RADIO_PAL                   1658
#define IDC_RADIO_NTSC                  1659
#define IDC_GRP_VIDEO_NORM              1660
#define IDC_EDIT_SMS_OWN_NUMBER         1661
#define IDC_TXT_OWN_NUMBER              1662
#define IDC_CHECK_SAVIC                 1663
#define IDC_CHECK_SAVIC_GLOBAL_COLORS   1664
#define IDC_CHECK_SAVIC_SYNC            1665
#define IDC_CHECK_SAVIC_USE2FIELDS      1666
#define IDC_RADIO_SAVIC_PAL_CCIR        1667
#define IDC_RADIO_SAVIC_PAL_SQUARE      1668
#define IDC_RADIO_SAVIC_NTSC_CCIR       1669
#define IDC_RADIO_SAVIC_NTSC_SQUARE     1670
#define IDC_STATIC_SAVIC_VID_NORM       1671
#define IDC_GRP_RESOLUTION              1672
#define IDC_RADIO_RESOLUTION_HIGH       1673
#define IDC_RADIO_RESOLUTION_LOW        1674
#define IDC_HOST_HAS_PIN                1675
#define IDC_HOST_PIN                    1676
#define IDC_GRP_ICP_CON                 1677
#define IDC_LINE_ONE                    1678
#define IDC_LINE_TWO                    1679
#define IDC_EDT_PORT                    1680
#define IDC_EDT_MODULE_ADDRESS          1681
#define IDC_BTN_CANCEL                  1683
#define IDC_BTN_CONFIG_MODULE           1684
#define IDC_CHECK_PTZ_CONFIG            1685
#define IDC_LINE_THREE                  1685
#define IDC_TREE_OF_MODULES             1686
#define IDC_BTN_POLL_PORT               1687
#define IDC_BTN_SCAN_ALL_PORTS          1688
#define IDC_EDT_PORT_START              1689
#define IDC_EDT_BTN_CY                  1690
#define IDC_EDT_MODULE_ADDRESS_START    1691
#define IDC_PROGRESS_PORT               1692
#define IDC_PROGRESS_ADDRESS            1693
#define IDC_CK_BAUD_1200                1694
#define IDC_CK_BAUD_2400                1695
#define IDC_CK_BAUD_4800                1696
#define IDC_CK_BAUD_9600                1697
#define IDC_CK_BAUD_19200               1698
#define IDC_CK_BAUD_38400               1699
#define IDC_CK_BAUD_57600               1700
#define IDC_CK_BAUD_115200              1701
#define IDC_EDT_TIMEOUT                 1702
#define IDC_EDT_TIME_POLL_RELAIS        1704
#define IDC_TXT_BAUDRATES               1705
#define IDC_TXT_TIMEOUT                 1706
#define IDC_LINE_FOUR                   1707
#define IDC_TXT_TIME_POLL_RELAIS_STATE  1709
#define IDC_RD_EDGE                     1710
#define IDC_RD_LEVEL                    1711
#define IDC_CK_POLL_STATE               1712
#define IDC_CK_MULTIPLE_ACCESS          1713
#define IDC_TXT_AT_DISCONNECT           1716
#define IDC_SN_AT_DISCONNECT            1717
#define IDC_GUARDTOUR_PROCESSES         1718
#define IDC_TXT_CAMERAS                 1719
#define IDC_GUARDTOUR_CAMERAS           1720
#define IDC_TXT_TRY                     1721
#define IDC_GUARDTOUR_TRY               1722
#define IDC_GUARDTOUR_HOSTS             1723
#define IDC_GUARDTOUR_SAVE              1724
#define IDC_GUARDTOUR_HOLD              1726
#define IDC_GUARDTOUR_EXCLUSIVE         1727
#define IDC_GUARDTOUR_EXCLUSIVE2        1728
#define IDC_GUARDTOUR_DISCONNECT        1728
#define IDC_GUARDTOUR_FULLSCREEN        1729
#define IDC_TXT_SWITCH_TIME             1730
#define IDC_GUARDTOUR_SWITCH_TIME       1731
#define IDC_GUARDTOUR_NAME              1732
#define IDC_TXT_GUARDTOUR               1733
#define IDC_TXT_SECONDS                 1735
#define IDC_CK_ENABLE_ICPCON_MODULE     1736
#define IDC_CK_ENABLE_SWITCH_PANEL      1737
#define IDC_TXT_BTN_SIZE                1738
#define IDC_EDT_BTN_CX                  1739
#define IDC_TXT_MULTI_MONITOR_SETTINGS  1739
#define IDC_GRP_MULTI_MONITOR_VISION    1740
#define IDC_RADIO_MULTI_MONITOR_VISION_1 1741
#define IDC_RADIO_MULTI_MONITOR_VISION_2 1742
#define IDC_RADIO_MULTI_MONITOR_VISION_1_2 1743
#define IDC_GRP_MULTI_MONITOR_RECHERCHE 1744
#define IDC_RADIO_MULTI_MONITOR_RECHERCHE_1 1745
#define IDC_RADIO_MULTI_MONITOR_RECHERCHE_2 1746
#define IDC_RADIO_MULTI_MONITOR_RECHERCHE_1_2 1747
#define IDC_RADIO_MULTI_MONITOR_SV_1    1748
#define IDC_RADIO_MULTI_MONITOR_SV_2    1749
#define IDC_GRP_MULTI_MONITOR_SUPERVISOR 1750
#define IDC_TXT_DISCONNECT              1751
#define IDC_EDIT_DISCONNECT             1752
#define IDC_RADIO_DEFAULT_SDI_MICROLOCK_SYSTEM1x 1753
#define IDC_RADIO_DEFAULT_SDI_MICROLOCK_SYSTEM1 1754
#define IDC_STATIC_YUTA                 1755
#define IDC_CK_YUTA_UNIT                1756
#define IDC_GTP_HOST_SPIN               1757
#define IDC_VOUT_LIST_PROCESSES         1758
#define IDC_VOUT_TXT_NAME               1759
#define IDC_VOUT_EDIT_NAME              1760
#define IDC_VOUT_TXT_TYPE               1761
#define IDC_VOUT_LIST_TYPE              1762
#define IDC_VOUT_TXT_EXTENSIONCARD      1763
#define IDC_VOUT_LIST_EXTENSIONCARD     1764
#define IDC_VOUT_TXT_OUT                1765
#define IDC_VOUT_LIST_OUT               1766
#define IDC_VOUT_TXT_CAMERAS            1767
#define IDC_VOUT_EDIT_CAMERAS           1768
#define IDC_VOUT_TXT_DWELLTIME          1769
#define IDC_VOUT_EDIT_DWELLTIME         1770
#define IDC_COMBO_AUDIO_CAPTURE         1775
#define IDC_COMBO_AUDIO_RENDERER        1776
#define IDC_TXT_ENCODER                 1777
#define IDC_TXT_AUDIO_SAMP_FREQUENCY    1778
#define IDC_COMBO_AUDIO_SAMP_FREQUENCY  1779
#define IDC_CK_AUDIO_2BYTES_PER_SAMP    1780
#define IDC_TXT_FRQ_UNIT                1782
#define IDC_RD_AUDIO_LEFT_CHANNEL       1783
#define IDC_RD_AUDIO_RIGHT_CHANNEL      1784
#define IDC_TXT_AUDIO_LENGTH_OF_SEQUENCE 1785
#define IDC_COMBO_AUDIO_LENGTH_OF_SEQUENCE 1786
#define IDC_TXT_MILLI_SECONDS_UNIT      1787
#define IDC_TXT_AUDIO_THRESHOLD         1788
#define IDC_EDT_AUDIO_THRESHOLD         1789
#define IDC_TXT_PERCENT_UNIT            1790
#define IDC_TXT_AUDIO_DWELL_TIME        1791
#define IDC_EDT_AUDIO_DWELL_TIME        1792
#define IDC_TXT_SECONDS_UNIT            1793
#define IDC_GRP_AUDIO_RECORD            1794
#define IDC_COMBO_AUDIO_COMPRESSOR      1795
#define IDC_GRP_AUDIO_DETECTOR          1799
#define IDC_GRP_AUDIO_RENDERER          1800
#define IDC_CK_AUDIO_DETECTOR           1801
#define IDC_CK_AUDIO_UNIT_ACTIVE        1802
#define IDC_CHECK_ALL_CAMERAS           1803
#define IDC_COMBO_AUDIO_INPUTPINS       1804
#define IDC_GRP_VOUT                    1805
#define IDC_SLIDER_INPUT_GAIN           1805
#define IDC_BTN_TEST_COMPRESSION_METHOD 1806
#define IDC_SLIDER_OUTPUT_VOLUME        1806
#define IDC_TREE_CAMERAS                1807
#define IDC_EDIT_MAX_TIME               1808
#define IDC_TXT_HOURS                   1809
#define IDC_TXT_MAX_TIME                1810
#define IDC_CK_AUDIO_HIGH_QUALITY       1811
#define IDC_TXT_AUDIO_QUALITY           1812
#define IDC_COMBO_AUDIO_QUALITY         1813
#define IDC_TXT_INPUT_GAIN              1814
#define IDC_TXT_AUDIO_CHANNEL           1817
#define IDC_TXT_DATABASE_FIELDS         1818
#define IDC_LIST_DBF_DATABASE_FIELDS    1819
#define IDC_TXT_DBF_DATABASE_FIELDS     1820
#define IDC_CHECK_USE                   1821
#define IDC_BTN_DBF_DEFAULT_VALUES      1822
#define IDC_BTN_DBF_DEFAULT_VALUES_ALL  1823
#define IDC_BTN_DBF_CREATE_DEFAULT      1824
#define IDC_TXT_DBF_LENGHT              1825
#define IDC_EDIT_DBF_LENGTH             1826
#define IDC_TXT_DBF_TYPE                1827
#define IDC_COMBO_DBF_TYPE              1828
#define IDC_TXT_DBF_DEFAULT             1829
#define IDC_TXT_DBF_DEFAULT_VALUE       1830
#define IDC_PROGRESS_INPUT_LEVEL        1831
#define IDC_CK_AUDIO_INPUT_LEVEL        1832
#define IDC_CK_AUDIO_INPUT_LISTEN       1833
#define IDC_BTN_AUDIO_VOLUME_CTRL       1834
#define IDC_CK_USBC_UNIT_ACTIVE         1835
#define IDC_PROGRESS_INPUT_LEVEL_PEAK   1835
#define IDC_CK_USBC_MD_ACTIVE           1836
#define IDC_CK_USBC_DETECTORS_ACTIVE    1837
#define IDC_GRP_USBC_MAIN               1838
#define IDC_RD_USBC_FS_0                1840
#define IDC_RD_USBC_FS_1                1841
#define IDC_TXT_USBC_FS                 1842
#define IDC_TXT_USBC_FRAME_RATE         1843
#define IDC_EDT_USBC_FRAMES_PER_SECOND  1844
#define IDC_LIST_CAMERAS                1846
#define IDC_TXT_ACTIVATION              1847
#define IDC_LINE                        1849
#define IDC_CHECK_DBF_USE               1852
#define IDC_EDIT_DBF_NAME               1853
#define IDC_EDIT_DBF_ID                 1854
#define IDC_TXT_DBF_NAME                1855
#define IDC_TXT_DBF_ID                  1856
#define IDC_CK_AUDIO_DEFAULT_REC        1857
#define IDC_CK_AUDIO_DEFAULT_PLAY       1858
#define IDC_GRP_AUDIO_TEST              1859
#define IDC_GRP_AUDIO_REC_EX            1860
#define IDC_AUCP_CHANNEL                1862
#define IDC_AUCP_STEREO_CHANNEL         1863
#define IDC_AUC_EDT_NAME                1864
#define IDC_AUCP_UNIT                   1865
#define IDC_AUCP_ACTIVE                 1866
#define IDC_AUC_RD_DEFAULT              1867
#define IDC_AUCP_NAME                   1868
#define IDC_AUC_EDT_NAME2               1869
#define IDC_AUCP_DEFAULT                1870
#define IDC_AUC_TXT_CHANNEL             1871
#define IDC_AUCP_FIXED                  1872
#define IDC_AUC_TXT_LINE_CHANNEL        1873
#define IDC_AUCP_CHANNEL_OUT            1874
#define IDC_AUC_TXT_UNIT                1875
#define IDC_GRP_MCT                     1876
#define IDC_TXT_MAX_CONNECT             1877
#define IDC_EDIT_MCT                    1878
#define IDC_EDIT_TYPE_AUDIO             1879
#define IDC_SPIN_TYPE_AUDIO             1880
#define IDC_STATIC_TYPE_AUDIO           1881
#define IDC_CHECK_NR                    1882
#define IDC_RADIO_REMOVABLE             1883
#define IDC_CHECK_TASHA                 1884
#define IDC_CHECK_TERMINATION           1885
#define IDC_TXT_TERMINATION             1886
#define IDC_BTN_CAM_COM_PARAMS          1887
#define IDC_BTN_COM_DEFAULT             1888
#define IDC_BTN_CAM_TYPE_SETTINGS       1889
#define IDC_PTZ_CONFIG_LIST             1891
#define IDC_COMBO_MINIMIZE              1893
#define IDC_IPC_COMBO_MINIMIZE          1893
#define IDC_LIST_CONTROLS               1894
#define IDC_STATIC_ID                   1895
#define IDC_COMBO_ID                    1897
#define IDC_STATIC_TYP                  1898
#define IDC_COMBO_TYP                   1899
#define IDC_BUTTON_NEW                  1900
#define IDC_BUTTON_DELETE               1901
#define IDC_GRP_JOYSTICK                1903
#define IDC_JP_GRP_JOYSTICK             1903
#define IDC_GRP_LANGUANGE_DEFS          1904
#define IDC_TXT_CODEPAGE                1905
#define IDC_TXT_CODEPAGE_BITS           1906
#define IDC_TXT_KEYBORD                 1907
#define IDC_TXT_LANGUAGE                1908
#define IDC_TXT_LANGUAGE_NAME           1909
#define IDC_COMBO_CODEPAGE_BITS         1910
#define IDC_COMBO_KEYBOARD              1911
#define IDC_COMBO_CODEPAGE              1912
#define IDC_CK_FONT_SIZES               1913
#define IDC_TXT_START_KEYBORD           1914
#define IDC_COMBO_INITIAL_KEYBOARD      1915
#define IDC_JP_TXT_JOYSTICK             1916
#define IDC_JP_TXT_JOYSTICK_NAME        1917
#define IDC_JP_BTN_RESET                1918
#define IDC_JP_BTN_CHOOSE_JOYSTICK      1919
#define IDC_JP_CK_BTN_1                 1920
#define IDC_JP_CK_BTN_2                 1921
#define IDC_JP_CK_BTN_3                 1922
#define IDC_JP_CK_BTN_4                 1923
#define IDC_JP_CK_BTN_5                 1924
#define IDC_JP_CK_BTN_6                 1925
#define IDC_JP_CK_BTN_7                 1926
#define IDC_JP_CK_BTN_8                 1927
#define IDC_JP_CK_BTN_9                 1928
#define IDC_JP_CK_BTN_10                1929
#define IDC_JP_CK_BTN_11                1930
#define IDC_JP_CK_BTN_12                1931
#define IDC_JP_CK_BTN_13                1932
#define IDC_JP_CK_BTN_14                1933
#define IDC_JP_CK_BTN_15                1934
#define IDC_JP_CK_BTN_16                1935
#define IDC_JP_CK_BTN_17                1936
#define IDC_JP_CK_BTN_18                1937
#define IDC_JP_CK_BTN_19                1938
#define IDC_JP_CK_BTN_20                1939
#define IDC_JP_CK_BTN_21                1940
#define IDC_JP_CK_BTN_22                1941
#define IDC_JP_CK_BTN_23                1942
#define IDC_JP_CK_BTN_24                1943
#define IDC_JP_CK_BTN_25                1944
#define IDC_JP_CK_BTN_26                1945
#define IDC_JP_CK_BTN_27                1946
#define IDC_JP_CK_BTN_28                1947
#define IDC_JP_CK_BTN_29                1948
#define IDC_JP_CK_BTN_30                1949
#define IDC_JP_CK_BTN_31                1950
#define IDC_JP_CK_BTN_32                1951
#define IDC_JP_GRP_JOY_BTNS             1952
#define IDC_JP_GRP_JOY_AXIS             1953
#define IDC_JP_TXT_ZERO_RANGE           1954
#define IDC_JP_EDIT                     1955
#define IDC_JP_EDT_ZERO_RANGE           1955
#define IDC_JP_CTRL_JOY_XY_AXIS         1956
#define IDC_EDT_FIXED_FONT              1958
#define IDC_EDT_VARIABLE_FONT           1959
#define IDC_EDT_DIALOG_FONT             1960
#define IDC_TXT_FIXED_FONT              1961
#define IDC_TXT_VARIABLE_FONT           1962
#define IDC_TXT_DIALOG_FONT             1963
#define IDC_TXT_FONT_KIND               1964
#define IDC_STATIC_TYPE                 1965
#define IDC_STATIC_PORT                 1966
#define IDC_STATIC_V1                   1967
#define IDC_STATIC_V2                   1968
#define IDC_STATIC_V3                   1969
#define IDC_STATIC_V4                   1970
#define IDC_COMBO_O1                    1971
#define IDC_COMBO_O2                    1972
#define IDC_COMBO_O3                    1973
#define IDC_COMBO_O4                    1974
#define IDC_STATIC_GRP                  1975
#define IDC_JP_CK_CONTROL_SPEED         1976
#define IDC_JP_TXT_PTZ_SPEED            1977
#define IDC_COMBO_COM                   1978
#define IDC_ISDN_COMP                   1978
#define IDC_COMBO_V1                    1979
#define IDC_COMBO_V2                    1980
#define IDC_TXT_MND_LETTER              1980
#define IDC_COMBO_V3                    1981
#define IDC_COMBO_MND_LETTER            1981
#define IDC_COMBO_V4                    1982
#define IDC_TXT_MND_PATH                1982
#define IDC_COMBO_ISDN_COMP             1983
#define IDC_EDT_MND_PATH                1990
#define IDC_TXT_MND_DOMAIN              1991
#define IDC_EDT_MND_DOMAIN              1992
#define IDC_TXT_MND_USER                1993
#define IDC_EDT_MND_USER                1994
#define IDC_TXT_MND_PASSWORD            1995
#define IDC_EDT_MND_PASSWORD            1996
#define IDC_EDT_MND_PASSWORD2           1997
#define IDC_TXT_MND_PASSWORD2           1998
#define IDC_TXT_MND_PASSWORD3           1999
#define IDC_TXT_MND_ADDITIONAL_PARAM    2000
#define IDC_MAINT_TXT_SHOW_MAINT        2001
#define IDC_MAINT_GRP_INSTALLER         2002
#define IDC_MAINT_TXT_INST_COMP         2003
#define IDC_MAINT_TXT_INST_STR          2004
#define IDC_MAINT_TXT_TOWN              2005
#define IDC_MAINT_TXT_COUNTRY           2006
#define IDC_MAINT_TXT_TELEFON           2007
#define IDC_MAINT_TXT_EMAIL             2008
#define IDC_MAINT_COMPANY               2009
#define IDC_MAINT_STR                   2010
#define IDC_MAINT_CITY                  2011
#define IDC_MAINT_CODE                  2012
#define IDC_MAINT_TELEFON               2013
#define IDC_MAINT_EMAIL                 2014
#define IDC_MAINT_COUNTRY               2015
#define IDC_MAINT_GRP_SETTINGS          2016
#define IDC_MAINT_BUTTON_SYSTEST        2017
#define IDC_MAINT_BUTTON_STARTDATE      2018
#define IDC_MAINT_BUTTON_REPORT         2019
#define IDC_MAINT_REPORT                2020
#define IDC_MAINT_BUTTON_REPORT_EXPORT  2021
#define IDC_MAINT_GRP_SYSCHECK          2022
#define IDC_MAINT_TXT_MANUAL_MAINT      2023
#define IDC_MAINT_RICHEDIT_MANUAL_MAINT_RTF 2024
#define IDC_MAINT_TXT_SYSTEMCHECK_DESCRIPTION 2025
#define IDC_MAINT_GRP_SYSREPORT         2026
#define IDC_MAINT_LOGIN                 2027
#define IDC_MAINT_USERNAME              2028
#define IDC_MAINT_PASS                  2029
#define IDC_MAINT_TXT_USER              2030
#define IDC_MAINT_TXT_PASS              2031
#define IDC_MAINT_GRP_LOGIN             2032
#define IDC_MAINT_CHECK_NAG             2033
#define IDC_MAINT_COMBO_INTERVALL       2034
#define IDC_MAINT_TXT_INTERVALL         2035
#define IDC_MAINT_START_INTERVALL       2036
#define IDC_MAINT_TXT_START_INTERVALL   2037
#define IDC_TXT_PTZ_PRESET              2038
#define IDC_MAINT_TXT_LOGIN_ERROR       2050
#define IDC_STATIC_BU_TIME_SPAN         2051
#define IDC_COMBO_BU_TIME_SPAN          2052
#define IDC_IP_EDT_ADDRESS              2053
#define IDC_PTZ_PRESET                  2054
#define IDC_IP_EDT_SUBNET_MASK          2055
#define IDC_IP_TXT_ADDRESS              2056
#define IDC_IP_TXT_SUBNET_MASK          2057
#define IDC_IP_RD_UDP                   2058
#define IDC_IP_RD_TCP                   2059
#define IDC_SDI_LIST_ALARM_NO           2059
#define IDC_IP_TXT_SOCKET_TYPE          2060
#define IDC_SDI_BTN_NEW                 2061
#define IDC_SDI_BTN_DELETE              2062
#define IDC_SDI_BTN_SAVE                2063
#define IDC_SDI_BTN_LOAD                2064
#define IDC_IP_TXT_PORT                 2065
#define IDC_IP_EDT_PORT                 2066
#define IDC_CK_AUTO_REDUCE_ARCHIVES     2067
#define IDC_CK_AUTO_REDUCE_ARCHIVES2    2068
#define IDC_CK_DYNAMIC_EXPAND_ARCHIVES  2068
#define IDC_LIST_PROCESSES              2069
#define IDC_STATIC_SERVER               2073
#define IDC_STATIC_LOGIN                2074
#define IDC_STATIC_PWD                  2075
#define IDC_EDIT_SERVER                 2076
#define IDC_EDIT_LOGIN                  2077
#define IDC_STATIC_FILENAME             2079
#define IDC_EDIT_FILENAME               2080
#define IDC_EDIT_RECTIME                2081
#define IDC_MISC_LIST                   2082
#define IDC_MISC_TXT_SETTINGS           2083
#define IDC_PUSHBUTTON                  2084
#define IDC_STATIC_PPVAR_HEADING        2085
#define IDC_TXT_BFR                     2086
#define IDC_TXT_TCC                     2087
#define IDC_EDIT_BFR                    2088
#define IDC_EDIT_TCC                    2089
#define IDC_LIST_PM100_ALARM            2090
#define IDC_TXT_PM100_ALARM             2091
#define IDC_TXT_PM100_XML               2092
#define IDC_LIST_PM100_XML              2093
#define IDC_LIST3                       2095
#define IDC_COMBO_TYPE                  2096
#define IDC_TXT_TYPE                    2097
#define IDC_STATIC_NR_CAMERAS           2098
#define IDC_CHECK_Q                     2099
#define IDC_COMBO1                      2100
#define IDC_COMBO_TIMER                 2100
#define IDC_RADIO_JPEG                  2101
#define IDC_RADIO_MPEG4                 2102
#define IDC_GRP_VIDEO_FORMAT            2103
#define IDC_GRP_VIDEO_AGC               2104
#define IDC_RADIO_AGC_ON                2105
#define IDC_RADIO_AGC_OFF               2106
#define IDC_GRP_IP_CAMERA               2107
#define IDC_CK_IP_CAM_UNIT              2108
#define IDC_LIST_IP_ITEMS               2109
#define IDC_CK_IP_INPUT1                2110
#define IDC_CK_IP_INPUT2                2111
#define IDC_CK_IP_INPUT3                2112
#define IDC_CK_IP_INPUT4                2113
#define IDC_CK_IP_INPUT5                2114
#define IDC_CK_IP_INPUT6                2115
#define IDC_CK_IP_INPUT7                2116
#define IDC_CK_IP_INPUT8                2117
#define IDC_GRP_IP_DETECT               2118
#define IDC_GRP_IP_PARAM                2119
#define IDC_CK_IP_OUTPUT1               2120
#define IDC_CK_IP_OUTPUT2               2121
#define IDC_CK_IP_OUTPUT3               2122
#define IDC_CK_IP_OUTPUT4               2123
#define IDC_CK_IP_OUTPUT5               2124
#define IDC_CK_IP_OUTPUT6               2125
#define IDC_CK_IP_OUTPUT7               2126
#define IDC_CK_IP_OUTPUT8               2127
#define IDC_EDT_IP_USER                 2128
#define IDC_CK_IP_CAMERA1               2130
#define IDC_CK_IP_CAMERA2               2131
#define IDC_CK_IP_CAMERA3               2132
#define IDC_CK_IP_CAMERA4               2133
#define IDC_CK_IP_CAMERA5               2134
#define IDC_CK_IP_CAMERA6               2135
#define IDC_CK_IP_CAMERA7               2136
#define IDC_CK_IP_CAMERA8               2137
#define IDC_TXT_IP_TYPE                 2140
#define IDC_TXT_IP_NAME                 2141
#define IDC_TXT_IP_LOCATION             2142
#define IDC_COMBO_CAPTURE_DEVICES       2143
#define IDC_BTN_IP_SEND                 2144
#define IDC_TXT_IP_DEVICE               2145
#define IDC_BTN_IP_SET_NAME             2146
#define IDC_TXT_IP_CAMERA               2147
#define IDC_TXT_IP_RESOLUTION           2148
#define IDC_COMBO_IP_RESOLUTIONS        2149
#define IDC_TXT_IP_INPUT                2150
#define IDC_TXT_IP_COMPRESSION          2151
#define IDC_COMBO_IP_COMPRESSION        2152
#define IDC_TXT_IP_RELAIS               2153
#define IDC_TXT_IP_ROTATION             2154
#define IDC_COMBO_IP_ROTATION           2155
#define IDC_TXT_IP_FRAMERATE            2156
#define IDC_TXT_IP_FRAMERATES           2157
#define IDC_EDT_IP_NAME                 2158
#define IDC_COMBO_IP_URL                2159
#define IDC_EDT_IP_PORT                 2160
#define IDC_TXT_IP_USER                 2161
#define IDC_BTN_IP_PASSWORD             2162
#define IDS_TIMER_MODE_CHANGE           10000
#define IDS_NOTIMPLEMENTED              10001
#define IDS_SUPERVISOR                  10002
#define IDS_HARDWARE                    10003
#define IDS_OFF                         10004
#define IDS_ON                          10005
#define IDS_LOCK                        10006
#define IDS_PROZ_SAVE                   10007
#define IDS_HOSTS                       10008
#define IDS_PROZ_ISDN                   10009
#define IDS_PROCESSES                   10010
#define IDS_NOTIMER                     10011
#define IDS_SYSTEMTIMERS                10012
#define IDS_SYSTEMPROCESS               10013
#define IDS_SYSTEM                      10014
#define IDS_PPP                         10015
#define IDS_NEW                         10016
#define IDS_INPUT                       10017
#define IDS_OUTPUT                      10018
#define IDS_PERMISSIONPAGE              10019
#define IDS_USERPAGE                    10020
#define IDS_TIMERPAGE                   10021
#define IDS_ACTIVATIONPAGE              10022
#define IDS_SAVEPROCESSPAGE             10023
#define IDS_CALLPROCESSPAGE             10024
#define IDS_SOFTWARE                    10025
#define IDS_MICO1                       10026
#define IDS_IP_CAMERA_UNIT              10026
#define IDS_COCO                        10027
#define IDS_Q_UNIT                      10027
#define IDS_AKU                         10028
#define IDS_STM                         10029
#define IDS_SIM                         10030
#define IDS_NEWHOST                     10031
#define IDS_EXISTING_ACTIVATION_YUTA    10032
#define IDS_DIAGONAL                    10033
#define IDS_ISDN1                       10034
#define IDS_SOCKET                      10035
#define IDS_RS232                       10036
#define IDS_MISCELLANEOUS               10037
#define IDS_WIZ_ACTIVATE_PERMANENT_SAVE_PROCESS 10038
#define IDS_NEWPERMISSION               10039
#define IDS_NEWUSER                     10040
#define IDS_ACTIVATION_STATE            10041
#define IDS_REGISTERED                  10042
#define IDS_ACTIVATION_OUTPUT           10043
#define IDS_WIZ_ACTIVATE_UVVK_OK_SAVE_PROCESS 10044
#define IDS_WIZ_ACTIVATE_UVVK_ALARM_SAVE_PROCESS 10045
#define IDS_OK                          10046
#define IDS_ALARM                       10047
#define IDS_ACTIVATION_INPUT            10048
#define IDS_NONAME                      10049
#define IDS_TYP                         10050
#define IDS_SUPERVISOR_END              10051
#define IDS_NOTHING                     10052
#define IDS_GAA                         10053
#define IDS_SWITCH_PANEL                10053
#define IDS_MESZ                        10054
#define IDS_VARIABLE                    10055
#define IDS_SDI_DATA_TYPE               10056
#define IDS_SDI_DATA_POSITION           10057
#define IDS_SDI_DATA_LENGTH             10058
#define IDS_SDI_DATA_SEPERATOR          10059
#define IDS_SDI_DATA_TAG                10060
#define IDS_SDI_DATA_FORMAT             10061
#define IDS_SDI                         10062
#define IDS_RELAY                       10063
#define IDS_AUTOLOGOUT                  10064
#define IDS_PTUNIT1                     10065
#define IDS_LINK                        10066
#define IDS_NTLOGON                     10067
#define IDS_MICO2                       10068
#define IDS_FIELDMAP                    10069
#define IDS_TO_BE_IGNORED               10070
#define IDS_DATE_DDMMYY                 10071
#define IDS_DATE_DD_MM_YY               10072
#define IDS_DATE_DDMMYYYY               10073
#define IDS_DATE_DD_MM_YYYY             10074
#define IDS_TIME_HHMM                   10075
#define IDS_TIME_HH_MM                  10076
#define IDS_TIME_HHMMSS                 10077
#define IDS_TIME_HH_MM_SS               10078
#define IDP_PASSWORD_INCORRECT          10079
#define IDP_SAVE_CHANGES                10080
#define IDP_HARDWARE_GROUP_DELETE       10081
#define IDP_HARDWARE_PARTIAL_DELETE     10082
#define IDP_HOLD_INTERVAL_NOTIME        10083
#define IDP_INTERVAL_NO_FOREVER_NOR_MAINTIME 10084
#define IDP_HARDWARE_ADDRESS_EMPTY      10085
#define IDP_HARDWARE_MICO_ADDRESS_DOUBLE 10086
#define IDP_PASSWORDS_NOTEQUAL          10087
#define IDP_NO_PASSWORD                 10088
#define IDP_LOGIN_FAILED                10089
#define IDP_MULTIPLE_ARCHIVES_IN_PROCESS 10090
#define IDP_SAVE_NR_PICTURE_WRONG       10091
#define IDP_SAVE_ACTIVE_TIME_WRONG      10092
#define IDP_SAVE_PICTURE_FREQUENCE_WRONG 10093
#define IDP_COCO_OUTPUT_CAMERA_ERROR    10094
#define IDP_WRONG_SELECTED_HOSTS        10095
#define IDP_RELAY_HOLD_NO_TIME          10096
#define IDP_HARDWARE_COCO_COVI_ADDRESS_DOUBLE 10097
#define IDP_SAVE_NO_ARCHIVES_IN_LIST    10098
#define IDS_DO_RESET                    10099
#define IDS_RESET_IN_PROGRESS           10100
#define IDS_RESET_FAILED                10101
#define IDS_RESET_OK                    10102
#define IDP_COMM_DOUBLE                 10103
#define IDP_DELETE_USERS_WITH_PERMISSION 10104
#define IDP_DELETE_PROCESS_WITH_ACTIVATION 10105
#define IDP_DELETE_OUTPUT_WITH_ACTIVATION 10106
#define IDP_DELETE_TIMER_WITH_ACTIVATION 10107
#define IDP_NO_PERMISSION               10108
#define IDP_ACTIVATION_WITHOUT_PROCESS  10109
#define IDP_ACTIVATION_NO_OUTPUT_OR_WRONG_PROCESS 10110
#define IDP_ACTIVATION_OK_KEEPALIVE     10111
#define IDP_ACTIVATION_OK_ISDN          10112
#define IDP_RELAY_CLOSE_TIME            10113
#define IDP_COMM_DIFFERENT              10114
#define IDP_DOUBLE_PERMISSION           10115
#define IDP_DOUBLE_USER                 10116
#define IDP_USER_WITHOUT_PERMISSION     10117
#define IDP_DOUBLE_HOST                 10118
#define IDP_HOST_WITHOUT_NUMBER         10119
#define IDP_HARDWARE_IRQ_DOUBLE         10120
#define IDP_HARDWARE_COCO_ADDRESS_DOUBLE 10121
#define IDS_FINE                        10122
#define IDS_MEDIUM                      10123
#define IDS_COARSE                      10124
#define IDS_COMP1                       10125
#define IDS_COMP2                       10126
#define IDS_COMP3                       10127
#define IDS_COMP4                       10128
#define IDS_COMP5                       10129
#define IDS_JAN                         10130
#define IDS_FEB                         10131
#define IDS_MAR                         10132
#define IDS_APR                         10133
#define IDS_MAY                         10134
#define IDS_JUN                         10135
#define IDS_JUL                         10136
#define IDS_AUG                         10137
#define IDS_SEP                         10138
#define IDS_OCT                         10139
#define IDS_NOV                         10140
#define IDS_DEC                         10141
#define IDS_EDGE                        10142
#define IDS_LEVEL                       10143
#define IDS_EDGECONTROL                 10144
#define IDS_LEVELCONTROL                10145
#define IDP_ACTIVATION_RELAY_WP         10146
#define IDP_ACTIVATION_CAMERA_WP        10147
#define IDP_NOMORE_SUPERVISOR           10148
#define IDP_NOAPPWITHOUTCONN            10149
#define IDP_APP_LT_CONF                 10150
#define IDP_CONN_LT_CONF                10151
#define IDP_APP_LT_CONN                 10152
#define IDP_RELAIS_WITH_ACTIVATION      10153
#define IDP_NO_LOCAL_HOSTNAME           10154
#define IDS_NO_SDI_TYPE_SELECTED        10155
#define IDS_MELDER                      10156
#define IDS_NO_SDI_NAME                 10157
#define IDS_SAVE_PICTURE_FREQUENCE_OVER25 10158
#define IDS_INFORMATION                 10159
#define IDS_EDITOR                      10160
#define IDS_INPUTGROUP                  10161
#define IDP_HARDWARE_COCO_IRQ_DOUBLE    10162
#define IDP_HARDWARE_MICO_COVI_ADDRESS_DOUBLE 10163
#define IDP_HARDWARE_ADDRESS_DOUBLE     10164
#define IDP_RESTART_MICO                10165
#define IDP_2FIELDS_WARNING             10166
#define IDP_HOST_ILLEGAL_ROUTING        10167
#define IDP_RESTART_AKU                 10168
#define IDP_RESTART_COCO                10169
#define IDP_RESTART_WINDOWS             10170
#define IDP_MESZ_DCF                    10171
#define IDP_NOEMPTY_FIELDS              10172
#define IDP_SDI_NO_DIFFERENCES          10173
#define IDP_SDI_WRONG_TOTAL_LENGTH      10174
#define IDP_SDI_NO_DIFFERENCE_STRING    10175
#define IDP_SDI_NO_DATA_FORMAT          10176
#define IDP_SDI_NO_SEPERATOR            10177
#define IDP_SDI_NO_TAG                  10178
#define IDS_KTO_NR                      10179
#define IDS_ARCHIV_NR                   10180
#define IDS_KAMERA_NR                   10181
#define IDS_REC_DATE                    10182
#define IDS_REC_TIME                    10183
#define IDS_DTP_TIME                    10184
#define IDS_GA_NR                       10185
#define IDS_BANKLEITZAHL                10186
#define IDS_TA_NR                       10187
#define IDS_VALUE                       10188
#define IDS_CURRENCY                    10189
#define IDS_STATION                     10190
#define IDS_CAM_NAME                    10191
#define IDS_DTP_DATE                    10192
#define IDS_PICTURE_NR                  10193
#define IDP_INVALID_DONGLE              10194
#define IDP_ACCESS_DENIED               10195
#define IDP_HOLD_INTERVAL_FOREVER       10196
#define IDS_DELETE_INPUT                10197
#define IDP_SDI_DATA_TYPE_DOUBLE        10198
#define IDP_SDI_DATA_OVERLAPPING        10199
#define IDP_SDI_SAME_TOTAL_LENGTH       10200
#define IDP_SDI_SAME_IDENTIFY_STRING    10201
#define IDP_SDI_SAME_TOTAL_LENGTH_AND_IDENTIFY_STRING 10202
#define IDP_SDI_WRONG_POSITION          10203
#define IDP_SDI_DATA_TOO_LONG           10204
#define IDS_TITLE_COM_CONFIGURATION     10205
#define IDS_NOPARITY                    10206
#define IDS_ODDPARITY                   10207
#define IDS_EVENPARITY                  10208
#define IDS_MARKPARITY                  10209
#define IDS_SPACEPARITY                 10210
#define IDS_TASHA1                      10211
#define IDP_NO_ARCHIVES_IN_PROCESS      10212
#define IDS_NEW_PROTOCOLFORMAT          10213
#define IDS_NOTIFICATIONPAGE            10214
#define IDS_PTZ_HEADING                 10215
#define IDS_FILE                        10216
#define IDS_NAME                        10217
#define IDS_NEW_NOTIFICATION            10218
#define IDS_LOAD                        10219
#define IDS_HTML                        10220
#define IDP_MESSAGE_TOO_LONG            10221
#define IDP_DELETE_NOTIFICATION_WITH_ACTIVATION 10222
#define IDS_LOCAL_HOST                  10223
#define IDS_NOTIFICATION                10224
#define IDS_NO_NOTIFICATION             10225
#define IDS_DATABASE                    10226
#define IDS_DRIVES                      10227
#define IDS_ARCHIVES                    10228
#define IDS_NR                          10229
#define IDS_NUMBER                      10230
#define IDS_SIZE_MB                     10231
#define IDS_ALARM_ARCHIV                10232
#define IDS_RING_ARCHIV                 10233
#define IDS_VORRING_ARCHIV              10234
#define IDS_FIXED_DRIVE                 10235
#define IDP_DELETE_ARCHIV_WITH_ACTIVATION 10236
#define IDS_NEW_ARCHIV                  10237
#define IDS_DRIVE                       10238
#define IDS_DESIGNA_BFR                 10239
#define IDS_USED                        10240
#define IDS_SIZE                        10241
#define IDS_QUOTA                       10242
#define IDS_DRIVE_FD                    10243
#define IDS_DRIVE_HD                    10244
#define IDS_DRIVE_NET                   10245
#define IDS_DRIVE_CD                    10246
#define IDS_ALL                         10247
#define IDS_USE_NORMAL                  10248
#define IDS_USE_DATABASE                10249
#define IDS_USE_BACKUP_READ             10250
#define IDS_USE_BACKUP_WRITE_READ       10251
#define IDS_USE_SYSTEM                  10252
#define IDS_TOO_LESS_DATABASE_DRIVES    10253
#define IDS_NO_DRIVE                    10254
#define IDP_ARCHIVS_TOO_BIG             10255
#define IDP_DRIVE_TOO_LESS              10256
#define IDP_ALARM_SAFERING_DIFFERENT    10257
#define IDP_ACTIVATION_WITHOUT_ARCHIV   10258
#define IDS_MICO3                       10259
#define IDS_EXISTING_ACTIVATIONS        10259
#define IDS_MICO4                       10260
#define IDS_NO_OF_CAMS_LIMITED          10260
#define IDP_WRONG_ASCII_IN_TOKEN        10261
#define IDS_CURRENCY_UNKNOWN            10262
#define IDS_WRONG_CURRENCY              10263
#define IDS_COM_PARAMS_CHANGED          10264
#define IDS_SNI_CHASE_2400_8N1          10265
#define IDS_ENGEL_MULTIPASS             10266
#define IDS_KEBA_PASADOR                10267
#define IDS_KEBA_PC2000                 10268
#define IDS_GERMAN_PARCEL               10269
#define IDP_PORT_NOT_OPENED             10270
#define IDS_SMS                         10271
#define IDP_DELETE_HOST_FROM_PROCESS    10272
#define IDP_DELETE_HOST_PROCESS         10273
#define IDS_DELETE_HOST_ARCHIV          10274
#define IDP_CREATE_ALARM_ARCHIVE_FOR_HOST 10275
#define IDP_CREATE_NORMAL_ARCHIVE_FOR_HOST 10276
#define IDP_CREATE_SEARCH_ARCHIVE_FOR_HOST 10277
#define IDS_HOST_ALARM_ARCHIVE          10278
#define IDS_HOST_NORMAL_ARCHIVE         10279
#define IDS_HOST_SEARCH_ARCHIVE         10280
#define IDP_NO_AUTOMATIC_ARCHIV         10281
#define IDS_SAVE                        10282
#define IDS_SETTINGS                    10283
#define IDS_OPEN                        10284
#define IDS_CONNECTING                  10285
#define IDS_CONNECTED                   10286
#define IDS_GOT_REGISTRY                10287
#define IDS_DISCONNECTED_ERROR          10288
#define IDS_SAFETY                      10289
#define IDP_NO_ALARM_FOR_SAFERING       10290
#define IDS_DISCONNECTED_OK             10291
#define IDS_DISCONNECTED_OK2            10292
#define IDS_NEW_TIMER                   10293
#define IDS_SEARCH_RESULT               10294
#define IDS_TIMER_EXPORT                10295
#define IDS_TIMER_IMPORT                10296
#define IDS_TIMER_SETTINGS              10297
#define IDS_VA_ARCHIVE_FULL             10298
#define IDS_VA_VIDEOSIGNAL              10299
#define IDS_VA_OUTGOING_CALL_ISDN1      10300
#define IDS_VA_OUTGOING_CALL_ISDN2      10301
#define IDS_VA_OUTGOING_CALL_PT1        10302
#define IDS_VA_OUTGOING_CALL_PT2        10303
#define IDS_VA_OUTGOING_CALL_TCP        10304
#define IDS_VA_INCOMING_CALL_ISDN1      10305
#define IDS_VA_INCOMING_CALL_ISDN2      10306
#define IDS_VA_INCOMING_CALL_PT1        10307
#define IDS_VA_INCOMING_CALL_PT2        10308
#define IDS_VA_INCOMING_CALL_TCP        10309
#define IDS_VIRTUAL_ALARM               10310
#define IDS_VA_REJECT_ISDN1             10311
#define IDS_VA_REJECT_ISDN2             10312
#define IDS_VA_REJECT_PT1               10313
#define IDS_VA_REJECT_PT2               10314
#define IDS_VA_REJECT_TCP               10315
#define IDS_MONDAY                      10316
#define IDS_TUESDAY                     10317
#define IDS_WEDNESDAY                   10318
#define IDS_THURSDAY                    10319
#define IDS_FRIDAY                      10320
#define IDS_SATURDAY                    10321
#define IDS_SUNDAY                      10322
#define IDS_ISDN2                       10323
#define IDS_PTUNIT2                     10324
#define IDS_CONNECT                     10325
#define IDP_PASSWORD_TOO_SHORT          10326
#define IDP_PASSWORD_NO_NUMBER          10327
#define IDP_PASSWORD_NO_ALPHA           10328
#define IDP_USER_WITHOUT_PASSWORD       10329
#define IDP_PASSWORD_TOO_LONG           10330
#define IDP_PASSWORD_ALPHANUM_TOO_LONG  10331
#define IDP_MAX_LOGIN_TRIES             10332
#define IDS_ARCHIVE_60_PERCENT_FULL     10333
#define IDP_VIRTUAL_ALARM_CHANGED       10334
#define IDS_DATE_MMDDYY                 10335
#define IDS_DATE_MM_DD_YYYY             10336
#define IDS_DATE_MMDDYYYY               10337
#define IDS_DATE_MM_DD_YY               10338
#define IDP_SDI_LENGTH_NULL             10339
#define IDP_SDI_LENGTH_TO_LONG          10340
#define IDS_SDI_SAMPLE_HEADER           10341
#define IDS_SDI_SAMPLE_ALARM            10342
#define IDS_SDI_SAMPLE_DATA             10343
#define IDS_REFERENCE_IMAGE             10344
#define IDS_PORTRAIT                    10345
#define IDS_HAND_TO_MONEY               10346
#define IDS_UNKNOWN                     10347
#define IDS_DATE_YYMMDD                 10348
#define IDS_DATE_YY_MM_DD               10349
#define IDS_DATE_YYYYMMDD               10350
#define IDS_DATE_YYYY_MM_DD             10351
#define IDS_ARCHIV                      10352
#define IDP_ACTIVATION_MD_WITHOUT_HOLD  10353
#define IDS_YES                         10354
#define IDS_NO                          10355
#define IDP_ACTIVATION_OK_BACKUP        10356
#define IDS_ROOM                        10357
#define IDS_DIAGNOSIS                   10358
#define IDS_SAME_TAN_OR_ZERO            10359
#define IDS_NEW_TAN                     10360
#define IDP_REGISTRY_IMPORT_WARNING     10361
#define IDS_BACKUPPROCESSPAGE           10362
#define IDP_DRIVE_FOR_FIXED_NOT_EMPTY   10363
#define IDP_HOST_ILLEGAL_ADDRESS        10364
#define IDP_PASSWORD_ALPHANUM_LONGER_THAN_PASSLEN 10365
#define IDP_ERROR_IN_IPLIST             10366
#define IDS_CANT_DO_IPTEST              10367
#define IDS_IPTEST_SUCCUESS             10368
#define IDS_IPTEST_FAILED               10369
#define IDS_CANT_START_PING             10370
#define IDP_ARCHIV_SIZE_ZERO            10371
#define IDP_ARCHIV_SIZE_TO_BIG          10372
#define IDS_VARIANT                     10373
#define IDS_DIAGNOSE_STARTCOMMAND       10374
#define IDS_LOGIN_SUCCESFUL             10375
#define IDS_LOGIN_DENIED                10376
#define IDP_BACKUP_PROCESS_NO_ARCHIVE   10377
#define IDP_BACKUP_PROCESS_NO_DRIVE     10378
#define IDP_FIXED_ARCHIVES_ON_DRIVE     10379
#define IDS_ACTUAL_IMAGE                10380
#define IDS_IMAGE_CALL                  10381
#define IDS_CHECK_CALL                  10382
#define IDS_JACOB1                      10383
#define IDS_JACOB2                      10384
#define IDS_JACOB3                      10385
#define IDS_JACOB4                      10386
#define IDS_DBD_CSID                    10387
#define IDS_DBD_FINM                    10388
#define IDS_DBD_LANM                    10389
#define IDS_DBD_PRID                    10390
#define IDS_DBD_BXID                    10391
#define IDP_ALARM_SMALLER_THAN_SAFERING 10392
#define IDP_NOTIFICATION_NO_MESSAGE_NOR_URL 10393
#define IDS_SDI_SAMPLE_TOTAL_LEN        10394
#define IDP_PERMISSION_NO_NAME          10395
#define IDP_USER_NO_NAME                10396
#define IDP_NO_PASSWORD_AND_USE_TPWL    10397
#define IDP_ARCHIVE_SIZE_ZERO           10398
#define IDS_VA_CHECK_CALL               10399
#define IDS_VA_CHECK_CALL_ERROR         10399
#define IDP_NO_PHOTOSTEP                10400
#define IDP_PHOTOSTEP_AS_PORTRAIT       10401
#define IDP_PHOTOSTEP_AS_MONEY          10402
#define IDP_SAMPLE_TAKEOVER             10403
#define IDS_ERROR_OPENING_ICPCON_UNIT   10404
#define IDS_SWITCHES                    10405
#define IDS_MULTI_MONITOR               10406
#define IDS_GEMOS                       10407
#define IDS_NO_RC_MODULE                10408
#define IDS_VA_ALWAYS_ALARM             10409
#define IDS_VA_CHECK_CALL_OK            10410
#define IDS_EMAIL                       10411
#define IDS_TOBS                        10412
#define IDS_VA_ALARM_OFF_SPAN           10413
#define IDS_MICE                        10414
#define IDS_HOUR                        10415
#define IDS_HOURS                       10416
#define IDS_WEEKDAY                     10417
#define IDS_DATE                        10418
#define IDS_DEF_KNODE_TXT               10419
#define IDS_SYSTEM_DESCR                10420
#define IDS_HARDWARE_DESCR              10421
#define IDS_LINK_DESCR                  10422
#define IDS_INPUT_DESCR                 10423
#define IDS_OUTPUT_DESCR                10424
#define IDS_RELAY_DESCR                 10425
#define IDS_DATABASE_DESCR              10426
#define IDS_PROCESSES_DESCR             10427
#define IDP_TIMER_NO_TIMESPAN           10428
#define IDP_TIMER_WITHOUT_TIME          10429
#define IDS_DAILY                       10430
#define IDS_MO_FR                       10431
#define IDS_SA_SU                       10432
#define IDS_WIZARD_CAPTION              10433
#define IDS_VERSION                     10434
#define IDS_WIZ_JACOB_ACTIVATE_MD       10435
#define IDS_WIZ_JACOB_ACTIVATE_JACOB    10436
#define IDS_WIZ_ACTIVATE_CAMERAS        10437
#define IDS_WIZ_ACTIVATE_MD_INPUT       10438
#define IDP_NOT_ENOUGH_USERS_FOR_DUAL_LOGIN 10439
#define IDP_USER_ALRM_INVALID           10440
#define IDP_TIMER_WRONG_DATE            10441
#define IDS_GUARD_TOUR                  10442
#define IDS_WIZ_ACTIVATE_MD_SAVE_PROCESS 10443
#define IDP_TIMER_SAME_NAME             10444
#define IDP_MD_OFF_WARNING              10445
#define IDP_NO_SN_TYPE_SELECTED         10446
#define IDP_NO_COM_SELECTED             10447
#define IDP_OPEN_FILE                   10448
#define IDP_SMS_NO_OWN_NUMBER           10449
#define IDS_SAVIC1                      10450
#define IDS_SAVIC2                      10451
#define IDS_SAVIC3                      10452
#define IDS_SAVIC4                      10453
#define IDP_USER_IDIP_SERVICE_RESERVED  10454
#define IDS_LANGUAGE                    10455
#define IDP_EMAIL_NO_DFUE               10456
#define IDP_EMAIL_DFUE_NOT_FOUND        10457
#define IDS_COM_PORT                    10458
#define IDS_PORT_MODULES                10459
#define IDS_BAUDRATE                    10460
#define IDS_FIRMWARE_VERSION            10461
#define IDS_MODULE_LOCATION             10462
#define IDS_DIGITAL_IN                  10463
#define IDS_DIGITAL_IN_N                10464
#define IDS_DIGITAL_OUT                 10465
#define IDS_DIGITAL_OUT_N               10466
#define IDS_ICPCON_MODULES              10467
#define IDS_CHANGE_MODULEPARAMETER      10468
#define IDS_MODULEPARAMETER_CHANGED     10469
#define IDS_MODULEPARAMETER_ERROR       10470
#define IDS_REQUEST_DELETE_PORT         10471
#define IDS_VA_ALARM_EXTERNAL_DEVICE_ERROR 10472
#define IDP_NAME_INVALID                10473
#define IDP_GUARDTOUR_PERMISSION_INVALID 10474
#define IDP_GUARDTOUR_NO_HOSTS          10475
#define IDP_NO_CAMERAS_SELECTED         10476
#define IDP_CAMERAS_INVALID_CHAR        10477
#define IDS_JOYSTICK                    10478
#define IDS_ERROR_NO_MODULE_ACTIVE      10479
#define IDS_ACCESS_GRANTED              10480
#define IDS_ACCESS_DENIED_ID_UNKNOWN    10481
#define IDS_ACCESS_DENIED_ID_INVALID    10482
#define IDS_ACCESS_DENIED_ID_EXPIRED    10483
#define IDS_ACCESS_DENIED_OUT_OF_TIMEZONE 10484
#define IDS_ACCESS_DENIED_ANTI_PASS_BACK 10485
#define IDS_ACCESS_DENIED_PIN_TIMEOUT   10486
#define IDS_ACCESS_DENIED_WRONG_PIN     10487
#define IDS_ACCESS_DENIED_TOO_MANY_WRONG_PIN 10488
#define IDS_ACCESS_DENIED_RELAY_LATCHED_OFF 10489
#define IDS_READ_ERROR                  10490
#define IDS_DATE_DD_MMM_YY              10491
#define IDS_DATE_DD_MMM_YYYY            10492
#define IDS_YUTA_MODULES                10493
#define IDS_YUTA_DETECTOR               10494
#define IDS_YUTA_RELAIS                 10495
#define IDS_EXCLUSIVE                   10496
#define IDS_VIDEO_OUT                   10497
#define IDS_VOUT_CLIENT                 10498
#define IDS_VOUT_SEQUENCER              10499
#define IDS_VOUT_ACTIVATION             10500
#define IDP_VOUT_SUBTYPE_INVALID        10501
#define IDP_VOUT_NO_EXTENSIONCARD       10502
#define IDP_VOUT_NO_OUTPUT              10503
#define IDS_AUDIO                       10504
#define IDS_TIME                        10505
#define IDP_CAMERAS_INVALID_CAM         10506
#define IDP_CAMERAS_INVALID_RANGE       10507
#define IDS_STRING                      10508
#define IDS_DATABASE_FIELDS             10509
#define IDP_DATABASE_FIELD_DOUBLE       10510
#define IDP_DATABASE_FIELD_NAME_DOUBLE  10510
#define IDP_DATABASE_FIELD_NAME_EMPTY   10511
#define IDP_DATABASE_FIELD_LENGTH_INVALID 10512
#define IDP_DATABASE_FIELD_TYPE_INVALID 10513
#define IDP_SDI_NO_DATA_TYPE            10514
#define IDS_USBCAM                      10515
#define IDS_STARTING_UNIT               10516
#define IDS_NO_AUDIO_HARDWARE           10517
#define IDS_AUDIO_TEST_SUCCUESS         10518
#define IDS_AUDIO_TEST_FAILED           10519
#define IDP_DATABASE_FIELD_ID_DOUBLE    10520
#define IDP_DATABASE_FIELD_ID_INVALID   10521
#define IDS_AUDIO_PROCESS               10522
#define IDS_AUDIO_INPUT                 10523
#define IDS_AUDIO_DESCR                 10524
#define IDS_AUDIO_OUTPUT                10525
#define IDS_AUDIO_CHANNELS              10526
#define IDS_LEFT                        10527
#define IDS_RIGHT                       10528
#define IDP_DELETE_AUDIO_WITH_ACTIVATION 10529
#define IDS_AUDIO2                      10530
#define IDS_AUDIO_OUTPUTNAME            10530
#define IDS_DEACTIVATE_INPUT            10531
#define IDS_REMOVABLE                   10532
#define IDS_PTZ_POSITION                10533
#define IDS_UP                          10534
#define IDS_DOWN                        10535
#define IDS_FOCUS_NEAR                  10536
#define IDS_FOCUS_FAR                   10537
#define IDS_IRIS_OPEN                   10538
#define IDS_IRIS_CLOSE                  10539
#define IDS_ZOOM_IN                     10540
#define IDS_ZOOM_OUT                    10541
#define IDS_SET_POS                     10542
#define IDS_SPEED                       10543
#define IDS_CONFIG                      10544
#define IDS_FOCUS_AUTO                  10545
#define IDS_IRIS_AUTO                   10546
#define IDS_TURN_180                    10547
#define IDS_AUX_OUT                     10548
#define IDS_ERASE_PRESET                10549
#define IDS_TOP                         10550
#define IDS_BOTTOM                      10551
#define IDS_LANGUAGE_DEPENDENT          10552
#define IDS_VALID_ID                    10553
#define IDS_INVALID_ID                  10554
#define IDS_INVALID_TIME                10555
#define IDS_ANTI_PASSBACK_IN            10556
#define IDS_ANTI_PASSBACK_OUT           10557
#define IDS_INVALID_PASSWORD            10558
#define IDS_INVALID_FINGER              10559
#define IDS_DURESS_MODE                 10560
#define IDS_DOOR_ERROR                  10561
#define IDS_QUAD                        10562
#define IDS_NOT_SELECTED                10563
#define IDS_MAINTENANCE                 10564
#define IDS_WIZ_ACTIVATE_DRIVES         10565
#define IDS_WIZ_INIT_MD_ARCHIVES        10566
#define IDS_WIZ_ACTIVATE_MD_ACTIVATIONS 10567
#define IDS_AUTO_INIT_AND_ACTIVATE      10568
#define IDS_AUTO_UVVK                   10569
#define IDS_PTZ_PRESET                  10570
#define IDS_STRING10571                 10571
#define IDP_ACTIVATION_OK_PTZ           10571
#define IDS_DESIGNA_TCC                 10572
#define IDS_ALARM_NR                    10573
#define IDS_SUB_NR                      10574
#define IDS_COMMENT                     10575
#define IDS_ALARM_LIST                  10576
#define IDP_ACTIVATION_OK_ALARMLIST     10577
#define IDS_SUBSCRIBER                  10578
#define IDS_NO_ALARMNUMBERS             10579
#define IDS_VA_ALARM_TEMPERATURE        10580
#define IDS_VA_ALARM_SMART              10581
#define IDS_VA_ALARM_HARDDISK_FAILURE   10582
#define IDS_VA_ALARM_FAN_SPEED          10583
#define IDS_PROZESS_UPLOAD              10584
#define IDS_KEY_VALUE                   10585
#define IDS_DESCRIPTION                 10586
#define IDS_DEFAULT_VALUE               10587
#define IDS_CLIENT_PRESENTATION         10588
#define IDS_LOAD_HOSTMAP                10589
#define IDS_LOAD_CAMERA_MAP             10590
#define IDS_CONNECT_TO_LOCAL_HOST       10591
#define IDS_CLOSE_ALARM_WINDOW          10592
#define IDS_SHOW_ALARM_MENU             10593
#define IDS_TOUCH_SCREEN                10594
#define IDS_DISABLE_DOUBLECLICK         10595
#define IDS_DISABLE_RIGHTCLICK          10596
#define IDS_DISABLE_ZOOM                10597
#define IDS_DISABLE_SMALL               10598
#define IDS_CASHBOX                     10599
#define IDS_BARRIER                     10600
#define IDS_CARDREADER                  10601
#define IDS_DE_ACTIVATE_ALL             10602
#define IDS_CONFIRM_DISCONNECT          10603
#define IDS_VERIFYUSER_TO_CLOSENOTE     10604
#define IDS_EXTERNAL                    10605
#define IDS_IP_DEVICE                   10605
#define IDS_REQUEST_TO_INSERT           10606
#define ID_EDIT_NEW                     32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_CANCEL                  32773
#define ID_EDIT_SERVERINIT              32774
#define ID_CONNECT                      32775
#define ID_DISCONNECT                   32776
#define ID_VIEW_TOOLTIPS                32777
#define ID_WIZZ_FIRST                   32778
#define ID_WIZ_ROOM_SURVEILLANCE_MD     32779
#define ID_WIZ_PERMANENT_RECORDING      32780
#define ID_WIZ_UVVK_RECORDING           32781
#define IDC_EDIT_TREE_LABEL             32782
#define ID_FILE_LOAD_REGISTRY           32783
#define ID_FILE_SAVE_AND_CLOSE          32784
#define ID_VIEW_PROFESSIONAL            32785
#define ID_WIZ_DESIGNAPM100RECORDING    32788
#define ID_WIZ_DESIGNAPMABACUSRECORDING 32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         2130
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
