//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ETS3DGLDLG.rc
//
#define IDS_MATHERR_DOMAIN              0x01
#define IDS_MATHERR_SING                0x02
#define IDS_MATHERR_OVERFLOW            0x03
#define IDS_MATHERR_UNDERFLOW           0x04
#define IDS_MATHERR_PLOSS               0x05
#define IDS_MATHERR_TLOSS               0x06
#define IDS_MATHERR_DENORMAL_OPERAND    0x07
#define IDS_MATHERR_INVALID_OPERATION   0x08
#define IDS_MATHERR_INEXACT_RESULT      0x09
#define IDS_MATHERR_STACK_CHECK         0x0a
#define IDS_UNKNOWN_ERROR               0x0b
#define IDS_DESTRUCTION_ERROR           0x0c
#define IDS_ALLOCATION_ERROR            0x0d
#define IDS_HEAP_ERROR                  0x0e
#define IDS_HEAP_DESTROY_ERROR          0x0f
#define IDM_ABOUTBOX                    0x0010
#define IDS_FILEERR_READ                0x11
#define IDS_FILEERR_WRITE               0x12
#define IDS_FILEERR_CRC                 0x13
#define IDS_FILEERR_TYPE                0x14
#define IDS_ERR_INVALID_HANDLE          0x15
#define IDS_ERR_ACCESS_VIOLATION        0x16
#define IDS_ERR_DATATYPE_MISALIGNMENT   0x17
#define IDS_ERR_PRIV_INSTRUCTION        0x18
#define IDS_ERR_IN_PAGE_ERROR           0x19
#define IDS_ERR_STACK_OVERFLOW          0x1a
#define IDS_ERR_INVALID_DISPOSITION     0x1b
#define IDS_ERR_ARRAY_BOUNDS_EXCEEDED   0x1c
#define IDS_ERR_INT_DIVIDE_BY_ZERO      0x1d
#define IDS_ERR_INT_OVERFLOW            0x1e
#define IDS_FUNCTION_LOAD_ERROR         0x1F
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ETS3DGLDLG_DIALOG           102
#define IDD_CARAWALK_DLG                103
#define IDD_REPORT_DLG                  104
#define IDD_PATH_DLG                    105
#define IDD_PRESENTATION_DLG            106
#define IDD_COPY_FOLDER                 107
#define IDD_ANIMATION                   108
#define IDD_ERROR_MESSAGE               109
#define IDD_MATERIAL_CMP                110
#define IDD_TIMER_DLG                   111
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME1                  129
#define IDR_MAINFRAME2                  130
#define IDR_MAINFRAME3                  131
#define IDR_MAINFRAME4                  132
#define IDR_MAINFRAME5                  133
#define IDR_MAINFRAME6                  134
#define IDR_MAINFRAME7                  135
#define IDR_MAINFRAME8                  136
#define IDR_CONTEXT                     136
#define IDR_MAINFRAME9                  137
#define IDS_TEX_AMBIENT_COLOR           501
#define IDS_TEX_DIFFUSE_COLOR           502
#define IDS_TEX_SPECULAR_COLOR          503
#define IDS_DIR_CREATED                 504
#define IDS_FILE_COPIED                 505
#define IDS_SAVE_CHANGED_PATH           506
#define IDC_SEARCH_PATH                 507
#define IDS_SHOW_INFO                   507
#define IDS_HIDE_INFO                   508
#define IDS_FILE_OLDER                  509
#define IDS_ICON_INFO_TIP               510
#define IDS_ICON_INFO_TIP_EX            511
#define IDS_SELECT_MATERIAL_HEADING     512
#define IDS_SAVE_MATERIAL_NOW           513
#define IDS_T_NO                        514
#define IDS_T_DATE                      515
#define IDS_T_TIME                      516
#define IDS_T_MSG                       517
#define IDS_T_TIME_FMT                  518
#define IDS_T_DATE_FMT                  519
#define IDS_T_SAVE_PARAMS               520
#define IDS_SHORT_KEY_HELP              521
#define IDS_BASE_MODULE                 1000
#define IDC_BUGFIX_NORMALVECTOR         1001
#define IDS_CARA_MODULE                 1001
#define IDC_BUGFIX_MOVEWINDOW           1002
#define IDS_CAPE_MODULE                 1002
#define IDC_BUGFIX_BUFFERSIZE           1003
#define IDS_UNKNOWN_MODULE              1003
#define IDC_BUGFIX_LIGHTTEXTURE         1004
#define IDS_MODULE                      1004
#define IDC_CARAWALK_ACCELERATED        1005
#define IDS_PRODUCT                     1005
#define IDC_ETS3DV_ACCELERATED          1006
#define IDS_ETSDIV                      1006
#define IDC_CARAWALK_BMP                1007
#define IDS_ETS3DGL                     1007
#define IDC_GENERIC_ACCELERATED         1008
#define IDC_ETS3DV_BMP                  1008
#define IDS_CARAWALK                    1008
#define IDC_CARAWALK_DOUBLE_BUFFER      1009
#define IDS_CARABOX                     1009
#define IDC_ETS3DV_DOUBLE_BUFFER        1010
#define IDS_CARASDB                     1010
#define IDC_BUGFIX_INIT_ALWAYS          1011
#define IDC_COLOR_BITS                  1013
#define IDC_DEPTH_BITS                  1014
#define IDC_REPORT_ETS2DVIEW            1014
#define IDC_STENCIL_BITS                1015
#define IDC_REPORT_ETS3DVIEW            1015
#define IDC_ALPHA_BITS                  1016
#define IDC_REPORT_ETS3DGL              1016
#define IDC_ACCUM_BITS                  1017
#define IDC_REPORT_ETSPRTD              1017
#define IDC_REPORT_CARAWALK             1018
#define IDC_REFRESH_TIME                1019
#define IDC_REPORT_CARASDB              1019
#define IDC_DLL_PATH                    1020
#define IDC_PERSPECTIVE_ANGLE           1020
#define IDC_REPORT_CARABOX              1020
#define IDC_2DV_MENU_BMP                1021
#define IDC_REPORT_ETSCDPL              1021
#define IDC_AVG_COL_FROM                1021
#define IDC_3DV_MENU_BMP                1022
#define IDC_REPORT_AC_COM               1022
#define IDC_AVG_COL_TO                  1022
#define IDC_2DV_MENU_SCALE              1023
#define IDC_AMBIENT_COL_FACTOR          1023
#define IDC_3DV_MENU_SCALE              1024
#define IDC_FILL_PATH                   1025
#define IDC_2DV_MENU_RECENT_FILES       1026
#define IDC_DEFAULT                     1027
#define IDC_POLYGON_OFFSET              1028
#define IDC_3DV_MENU_RECENT_FILES       1028
#define IDC_POLYGON_FACTOR              1029
#define IDC_2_3DV_PRINTER_OFFSET_X      1029
#define IDC_PIXELFORMAT                 1030
#define IDC_2_3DV_PRINTER_OFFSET_Y      1030
#define IDC_INFO                        1031
#define IDC_COPY                        1032
#define IDC_CPF_SOURCE_PATH             1033
#define IDC_CPF_DESTINATION_PATH        1034
#define IDC_CPF_INCLUDES                1035
#define IDC_CPF_SEARCH_SOURCE_PATH      1036
#define IDC_CPF_SEARCH_DESTINATION_PATH 1037
#define IDC_CPF_INCLUDE_FILES           1040
#define IDC_BUGFIX_BUFFER               1042
#define IDC_REPORT                      1043
#define IDC_PIXELFORMAT_TXT             1045
#define IDC_CARAWALK_SHADOWS            1046
#define IDC_TEX_AMBIENT                 1047
#define IDC_TEX_DIFFUSE                 1048
#define IDC_APPLY                       1048
#define IDC_TEX_SPECULAR                1049
#define IDC_LOG_WINDOW                  1049
#define IDC_ANIMATION                   1056
#define IDC_MMCONTROL                   1057
#define IDC_R_PATH0                     1058
#define IDC_R_PATH1                     1059
#define IDC_EDT_ERROR_NUMBER            1059
#define IDC_R_PATH2                     1060
#define IDC_EDT_ERRRO_MESSAGE           1060
#define IDC_R_PATH3                     1061
#define IDC_MATERIAL_NO                 1061
#define IDC_BORDER                      1062
#define IDC_GENERATE_TEX_COORD          1063
#define IDC_SCALEFACTOR_T               1065
#define IDC_SHININESS                   1066
#define IDC_ALPHA_AMBIENT               1067
#define IDC_ALPHA_DIFFUSE               1068
#define IDC_ALPHA_SPECULAR              1069
#define IDC_ALPHA_EMISSION              1070
#define IDC_RED_AMBIENT                 1071
#define IDC_RED_DIFFUSE                 1072
#define IDC_RED_SPECULAR                1073
#define IDC_RED_EMISSION                1074
#define IDC_GREEN_AMBIENT               1075
#define IDC_GREEN_DIFFUSE               1076
#define IDC_GREEN_SPECULAR              1077
#define IDC_GREEN_EMISSION              1078
#define IDC_BLUE_AMBIENT                1079
#define IDC_BLUE_DIFFUSE                1080
#define IDC_BLUE_SPECULAR               1081
#define IDC_BLUE_EMISSION               1082
#define IDC_BORDER_COLOR                1083
#define IDC_AMBIENT_LIGHT               1084
#define IDC_DIFFUSE_LIGHT               1085
#define IDC_INFO_TEXT                   1085
#define IDC_SPECULAR_LIGHT              1086
#define IDC_EMISSION_LIGHT              1087
#define IDC_SCALEFACTOR_S               1088
#define IDC_CPF_COPY_ONLY_NEWER         1089
#define IDC_BITMAP_FILE                 1089
#define IDC_SELECT_MATERIAL             1090
#define IDC_MATERIA_DESCR               1091
#define IDC_CK_DEBUG                    1092
#define IDC_CK_NO_DLLPATH               1093
#define IDC_TIMER_CALENDAR              1097
#define IDC_TIMER_LIST                  1100
#define IDC_TIMER_MESSAGE               1101
#define IDC_TIMER_PATH                  1102
#define IDC_BTN_TIMER_PATH              1103
#define IDC_TIMER_CLOCK                 1104
#define IDC_TIMER_CLOCK_CURRENT         1105
#define IDC_TIMER_BTN_SET               1106
#define IDC_TIMER_BTN_DELETE            1107
#define IDC_BTN_FILES                   1107
#define IDC_TIMER_BTN_NEW               1108
#define IDC_CPF_COPY_CREATE_DIR         1108
#define IDC_CPF_COPY_IN_ONE_DIR         1109
#define IDS_ETSDIV_ERROR_DISTANCE       0x1021
#define IDS_ETSDIV_ERROR_STEPS          0x1022
#define IDS_ETSDIV_ERROR_RANGE          0x1023
#define IDS_ETSDIV_ERROR_STEPWIDTH      0x1024
#define IDS_ETSDIV_ERROR_NUMSTEPS       0x1025
#define IDS_ETSDIV_ERROR_TEXTLEN        0x1026
#define IDS_ETSDIV_ERROR_MODE           0x1027
#define IDS_ETSDIV_ERROR_POINTER        0x1028
#define IDS_ETSDIV_ERROR_DIV_FKT        0x1029
#define IDS_ETSDIV_ERROR_NO_ARRAY       0x102A
#define IDS_CARAWALK_ROOMDATA_ERROR     0x1821
#define IDS_CARAWALK_PARENTWND_ERROR    0x1822
#define IDS_CARAWALK_BOXDATA_ERROR      0x1823
#define IDS_ETS3DERR_SET_HDC            0x2021
#define IDS_ETS3DERR_SET_PIXFMT         0x2022
#define IDS_ETS3DERR_CREATE_RC          0x2023
#define IDS_ETS3DERR_MKCURR_RC          0x2024
#define IDS_ETS3DERR_NOSYNCEVEVT        0x2025
#define IDS_ETS3DERR_NOTHREAD           0x2026
#define IDS_ETS3DERR_TIMEOUT            0x2027
#define IDS_ETS3DERR_NOTIMER            0x2028
#define IDS_ETS3DERR_NOPALETTE          0x2029
#define ID_CALL_GLSETUP                 40001
#define ID_CALL_CARAWALKSETUP           40002
#define ID_CALL_DLL_PATHSETUP           40003
#define ID_CALL_CARAVIEW_SETUP          40004
#define ID_SET_DEBUG_PATH               40005
#define ID_SET_RELEASE_PATH             40006
#define ID_SET_RELEASE_ENG_PATH         40007
#define ID_CALL_SAVE_PROJECT            40008
#define ID_CALL_REPORT_SETUP            40009
#define ID_CALL_MATERIALSETUP           40010
#define ID_CALL_ETSMMPLAYER             40011
#define ID_CALL_TIMEPLAN                40012
#define ID_CALL_ETSMMRECORDER           40013
#define ID_CALL_ETSMIXER                40014
#define IDS_DLL_LOAD_ERROR              0xFFFF

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
