//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MicoUnit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_MICOAPP_DIALOG              102
#define IDS_NO_VIDEO                    102
#define IDS_RTE_NO_VIDEO                102
#define IDD_DLG_COLOR                   103
#define IDS_VIDEO                       103
#define IDS_RTE_VIDEO                   103
#define IDS_RTE_PCD8584_READ_BACK       104
#define IDS_RTE_BT829_WRONG_ID          105
#define IDS_RTE_BT829_READ_BACK         106
#define IDS_RTE_BT856_WRONG_ID          107
#define IDS_RTE_VXD_WRONG_VERSION       108
#define IDS_RTE_UNKNOWN_IRQ             110
#define IDS_RTE_IRQ_FAILED              111
#define IDS_RTE_NO_INI                  112
#define IDS_RTE_VXD_NOT_FOUND           113
#define IDS_RTE_VXD_NO_IOCTL            114
#define IDS_RTE_VXD_API_FAILED          115
#define IDS_RTE_VIRTUALIZE              116
#define IDS_RTE_RUN_MICOUNIT            117
#define IDS_RTE_ALLOW_HARDDECODE_MICO   118
#define IDR_MAINFRAME                   128
#define IDR_MICOUNIT                    130
#define IDD_SETTINGS                    131
#define IDI_ABOUT                       132
#define IDD_LOGIN                       133
#define DLG_MSGBOX_OK                   134
#define IDC_USER_ID                     1000
#define IDC_PASSWORD                    1001
#define IDC_SOURCE1                     1004
#define IDC_SOURCE2                     1005
#define IDC_SOURCE3                     1006
#define IDC_SOURCE4                     1007
#define IDC_SOURCE5                     1008
#define IDC_SOURCE6                     1009
#define IDC_SOURCE7                     1010
#define IDC_SOURCE8                     1011
#define IDC_EXTCARD0                    1012
#define IDC_EXTCARD1                    1013
#define IDC_EXTCARD2                    1014
#define IDC_EXTCARD3                    1015
#define IDC_FE_PAL_CCIR                 1016
#define IDC_FE_NTSC_CCIR                1017
#define IDC_FE_PAL_SQUARE               1018
#define IDC_FE_NTSC_SQUARE              1019
#define IDC_FE_FBAS                     1020
#define IDC_FE_SVHS                     1021
#define IDC_BE_PAL_CCIR                 1022
#define IDC_BE_NTSC_CCIR                1023
#define IDC_BE_PAL_SQUARE               1024
#define IDC_BE_NTSC_SQUARE              1025
#define IDC_DLG_LUMINANCE               1026
#define IDC_DLG_SETTINGS                1027
#define IDC_DLG_SATURATION              1028
#define IDC_SEND                        1029
#define IDC_SEND_DATA                   1030
#define IDC_RECEIVE_DATA                1031
#define IDC_EXTCARDMEGRA                1032
#define IDC_BE_COMPOSITE                1033
#define IDC_BE_RGB                      1034
#define IDC_FE_LNOTCH                   1035
#define IDC_FE_LDEC                     1036
#define IDC_EDGE7                       1037
#define IDC_EDGE6                       1038
#define IDC_EDGE5                       1039
#define IDC_EDGE4                       1040
#define IDC_EDGE3                       1041
#define IDC_EDGE2                       1042
#define IDC_EDGE1                       1043
#define IDC_EDGE0                       1044
#define IDC_ACK7                        1045
#define IDC_ACK6                        1046
#define IDC_ACK5                        1047
#define IDC_ACK4                        1048
#define IDC_ACK3                        1049
#define IDC_ACK2                        1050
#define IDC_ACK1                        1051
#define IDC_ACK0                        1052
#define IDC_RELAIS3                     1053
#define IDC_RELAIS2                     1054
#define IDC_RELAIS1                     1055
#define IDC_RELAIS0                     1056
#define IDC_EDIT_SEND_MCI               1057
#define IDC_SEND_MCI                    1058
#define IDC_SEND_SCRIPT                 1059
#define IDC_MICOID0                     1060
#define IDC_MICOID1                     1061
#define IDC_MICOID2                     1062
#define IDC_MICOID3                     1063
#define IDC_TR_DATA                     1064
#define IDC_RE_DATA                     1065
#define IDC_DECODED_FRAMES              1066
#define IDC_ENCODED_FRAMES              1067
#define IDC_DEC_START                   1068
#define IDC_DEC_STOP                    1069
#define IDC_ENC_START                   1070
#define IDC_ENC_STOP                    1071
#define IDC_TEST                        1072
#define IDC_DEC_BITRATE                 1073
#define IDC_ENC_BITRATE                 1074
#define IDC_SET_DEC_BITRATE             1075
#define IDC_SET_ENC_BITRATE             1076
#define IDC_LUM                         1077
#define IDC_POSITION                    1078
#define IDC_ACQUISITION                 1079
#define IDC_DELAYS                      1080
#define IDC_PLL                         1081
#define IDC_COLOR                       1082
#define IDC_768X576                     1083
#define IDC_HIGH_RES                    1083
#define IDC_768X288                     1084
#define IDC_384X576                     1085
#define IDC_384X288                     1086
#define IDC_LOW_RES                     1086
#define IDC_COMPRESS_1                  1087
#define IDC_COMPRESS_2                  1088
#define IDC_COMPRESS_3                  1089
#define IDC_COMPRESS_4                  1090
#define IDC_COMPRESS_5                  1091
#define IDC_COLCO_RESET                 1092
#define IDC_SBRIGHTNESS                 1093
#define IDC_SCONTRAST                   1094
#define IDC_SSATURATION                 1095
#define IDC_VCONTRAST                   1096
#define IDC_VSATURATION                 1097
#define IDC_VBRIGHTNESS                 1098
#define IDC_UEBERNAHME                  1099
#define IDC_SHUE                        1100
#define IDC_VHUE                        1101
#define IDC_STATIC_NAME_PW              1106
#define IDC_STATIC_NAME                 1107
#define IDC_STATIC_PW                   1108
#define IDC_STATIC_BRIGHTNESS           1109
#define IDC_STATIC_CONTRAST             1110
#define IDC_STATIC_SATURATION           1111
#define IDC_STATIC_HUE                  1112
#define IDC_GROUP_EXTENSION             1113
#define IDC_GROUP_VIDEOSOURCE           1114
#define IDC_GROUP_VIDEOFRONTEND         1115
#define IDC_GROUP_VIDEOBACKEND          1116
#define IDC_GROUP_SOURCETYPE            1117
#define IDC_TXT_EDGE                    1118
#define IDC_TXT_ACK                     1119
#define IDC_TXT_RELAIS                  1120
#define IDC_TXT_FRAMES1                 1121
#define IDC_TXT_FRAMES2                 1122
#define IDC_TXT_DECODER                 1123
#define IDC_TXT_ENCODER                 1124
#define IDC_GROUP_RESOLUTION            1125
#define IDC_GROUP_COMPRESSION           1126
#define IDC_MESSAGE                     1128
#define ID_SETTINGS                     59142
#define IDP_LOGIN_FAILED                59143
#define IDP_OLD_MICO                    59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
