//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CARAWALK.rc
//
#define IDAPPLY                         10
#define IDR_ROOM_WALKING                103
#define IDR_CARAWALK_MENU               104
#define IDR_ACCELERATOR                 105
#define IDD_LIGHTPARAM                  106
#define IDD_BOX_POSITION                107
#define IDR_CONTEXT_DETAIL              108
#define IDD_BOX_PROPERTIES              108
#define IDC_WALKING                     111
#define IDC_TURN_LIGHT                  112
#define IDC_LOOK_AROUND                 113
#define ID_CLOSE                        1009
#define IDC_BPR_POLY_EDT                1010
#define IDC_BPR_SCALE_X_EDT             1011
#define IDC_BPR_SCALE_Y_EDT             1012
#define IDC_BPR_POLY_SPIN               1013
#define IDC_BPR_SIZE_X_EDT              1014
#define IDC_BPR_MATERIAL_CK             1015
#define IDC_BPR_SIZE_Y_EDT              1015
#define IDC_BPR_SHININESS_EDT           1016
#define IDC_LIGHTDLG_LIGHTCOMBO         1020
#define IDC_LIGHTDLG_CUT_OFF            1021
#define IDC_LIGHTDLG_LIGHTON            1022
#define IDC_LIGHTDLG_EXPONENT           1023
#define IDC_LIGHTDLG_SPOT               1024
#define IDC_LIGHTDLG_COLOR              1025
#define IDC_LIGHTDLG_DIMMER             1026
#define IDC_MATERIAL_COMBO              1029
#define IDC_BPR_SAVE_BOX                1030
#define IDC_BOXDLG_BOXCOMBO             1040
#define IDC_BOXDLG_E_PHI                1041
#define IDC_BOXDLG_E_THETA              1042
#define IDC_BOXDLG_C_PSI                1045
#define IDC_BTN_AMBIENT                 1050
#define IDC_BTN_COLOR                   1051
#define IDC_BTN_DIFFUSE                 1052
#define IDC_BTN_SPECULAR                1053
#define IDC_BTN_BITMAP                  1054
#define IDC_BTN_EMISSION                1055
#define IDC_AMBIENT_COL                 1056
#define IDC_DIFFUSE_COL                 1057
#define IDC_SPECULAR_COL                1058
#define IDC_EMISSION_COL                1059
#define IDC_MATERIAL_COL                1060
#define IDC_CK_BMP_FILE                 1061
#define IDC_CK_TEX_GENCOORD             1062
#define IDC_PHIRIGHT                    1140
#define IDC_PHILEFT                     1141
#define IDC_THETAUP                     1142
#define IDC_PSILEFT                     1144
#define IDC_PSIRIGHT                    1145
#define IDC_THETADOWN                   1155
#define IDM_WALK_FORWARD                30001
#define IDM_WALK_BACKWARD               30002
#define IDM_WALK_TURNRIGHT              30003
#define IDM_WALK_TURNLEFT               30004
#define IDM_WALK_LOOKUP                 30005
#define IDM_WALK_LOOKDOWN               30006
#define IDM_WALK_GEAR_LEFT              30007
#define IDS_MOVING_MOUSE                30007
#define IDM_WALK_GEAR_RIGHT             30008
#define IDS_LOOKING_MOUSE               30008
#define IDS_TURNLIGHT_MOUSE             30009
#define IDM_WALK_BACKWARD_CTRL          30011
#define IDM_WALK_TURNLEFT_CTRL          30012
#define IDM_WALK_LOOKDOWN_CTRL          30013
#define IDM_WALK_LOOKUP_CTRL            30014
#define IDM_WALK_TURNRIGHT_CTRL         30015
#define IDM_WALK_FORWARD_CTRL           30016
#define IDM_WALK_GEAR_LEFT_CTRL         30017
#define IDM_WALK_GEAR_RIGHT_CTRL        30018
#define IDM_VIEW_TEXTURE                30050
#define IDM_VIEW_LIGHT                  30051
#define IDM_VIEW_BOXES                  30052
#define IDM_VIEW_DETAIL                 30054
#define IDM_VIEW_DETAIL_VERYLOW         30055
#define IDM_VIEW_DETAIL_LOW             30056
#define IDM_VIEW_DETAIL_MEAN            30057
#define IDM_VIEW_DETAIL_HIGH            30058
#define IDM_VIEW_DETAIL_VERYHIGH        30059
#define IDM_VIEW_TEX_MAG_LINEAR         30060
#define IDM_VIEW_TEX_MIN_LINEAR         30061
#define IDM_OPTIONS_LIGHT               30072
#define IDM_OPTIONS_BOX                 30073
#define IDM_OPTIONS_GHOSTMODE           30081
#define IDM_OPTIONS_FLYMODE             30082
#define IDM_STATUSBAR                   40004
#define IDM_PRINT                       40023
#define IDM_PRINTERSETUP                40024
#define ID_FILE_CLOSE_PROGRAM           40025
#define IDM_HELP_THEMES                 40039
#define IDM_HELP_INFO                   40040
#define IDM_SELECTALL                   40059
#define IDM_SHOWFLOORVIEW               40081
#define IDM_SHOWCEILINGVIEW             40082
#define IDM_SHOWWALLVIEW                40083
#define IDM_SHOWSOURCEVIEW              40084
#define IDM_SHOW3DVIEW                  40085
#define IDM_TOGGLEFULLVIEW              40090
#define IDM_TOOLBAR3D                   40119
#define IDS_VALUES_CHANGED              57608
#define IDS_LIGHTCOLORDLG_HEADING       57609
#define IDS_BMP_FILTER                  57610
#define IDS_ERROR_MSG_BOX               57611
#define IDS_HELP_STRING                 57612
#define IDS_MSG_CARA_WALK               57613
#define IDS_ERROR_HEAP                  57614
#define IDS_ERROR_WRONG_FOLDER          57615
#define IDS_ERROR_LS_BOX_FOLDER         57616
#define IDS_IDOK                        61001
#define IDS_IDCANCEL                    61002
#define IDS_IDAPPLY                     61010
#define IDS_FORMAT_MIN_MAX_INT2         61011
#define IDS_FORMAT_MIN_MAX_DOUBLE2      61012
#define IDS_REG_KEY                     61013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
