######################################################################
# Automatically generated by qmake (2.01a) Di 2. Sep 22:19:54 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += NewXMLItemDlg.h XMLEdit.h NewXMLItemDlg.moc XMLEdit.moc
SOURCES += Main.cpp NewXMLItemDlg.cpp XMLEdit.cpp
