//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MICO.RC
//
#define IDI_ICON1                       101
#define ID_SBBRIGHT						1100
#define ID_SBCONTRAST					1101
#define ID_SBSAT					    1102
#define ID_EBBRIGHT						1103
#define ID_EBCONTRAST					1104
#define ID_EBSAT						1105								 
#define IDC_Bright						1106
#define IDC_Contrast					1107
#define IDC_Sat							1108
#define ID_INPUTA                       1001
#define ID_INPUTB                       1002
#define ID_INPUTC                       1003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
