//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Recherche.rc
//
#define IDR_MAINFRAME                   101
#define IDR_CONTEXT                     102
#define IDB_IMAGES                      103
#define IDD_FIELD                       104
#define IDD_QUERY_RESULT                105
#define IDR_SEARCH                      106
#define IDD_COMMENT                     107
#define IDB_STATES                      108
#define IDR_TOOLBARMENU                 109
#define IDD_SELECT_BACKUP_DRIVE         110
#define IDB_HOT                         111
#define IDD_DATABASE_INFO               112
#define IDB_COLD                        113
#define IDR_DIB                         114
#define IDR_DISPLAY                     115
#define IDD_STATION_NAME                116
#define IDD_QUERY                       117
#define IDD_QUERY_FIELD_NUM             118
#define IDD_BACKUP                      119
#define IDD_QUERY_FIELD_TIME            120
#define IDD_QUERY_FIELD_DATE            121
#define IDD_QUERY_FIELD_CHAR            122
#define IDD_NAVIGATION                  123
#define IDB_DRIVES                      124
#define IDD_CONNECTING                  125
#define IDD_BACKUP_NEW                  126
#define IDC_GLASS                       127
#define IDD_ALARM_LIST                  128
#define IDB_SYNC_HOT                    129
#define IDD_SYNC                        130
#define IDR_HTML                        131
#define IDR_DISPLAY_DTS                 132
#define IDR_ALARM_LIST                  133
#define IDW_SYNC_DATE                   134
#define IDW_SYNC_TIME                   135
#define IDW_SYNC_SLIDER                 136
#define IDC_RECT                        137
#define IDI_HOSTICON                    138
#define IDC_SLIDER                      1000
#define IDC_EDIT_DATA                   1001
#define IDC_NUMBER                      1002
#define IDC_TXT_PICTURE                 1003
#define IDC_TXT_FOUND                   1004
#define IDC_CHECK_DISCONNECT            1005
#define IDC_ANIMATE_SEARCH              1006
#define IDC_CHECK_ALL                   1007
#define IDC_CHECK_OPEN                  1008
#define IDC_COMMENT                     1009
#define IDC_SERVER_ARCHIVES             1010
#define IDC_BLZ_TEXT                    1011
#define IDC_PROGRESS_PROCESS            1012
#define IDC_EDIT_QUERY                  1013
#define IDC_LIST_RESULTS                1014
#define IDC_CHECK_COPY                  1015
#define IDC_EDIT_SEARCH_IN              1016
#define IDC_PCDATE                      1017
#define IDC_TIME_EXACT                  1018
#define IDC_TIME_FROM                   1019
#define IDC_TIME_TO                     1020
#define IDC_BIS_ZEIT_TEXT               1021
#define IDC_PCDATE_END                  1021
#define IDC_CHECK_EXACT_TIME            1022
#define IDC_CHECK_TIME_FROM             1023
#define IDC_CHECK_DATE                  1024
#define IDC_TXT_FIELD                   1025
#define IDC_TIME_END                    1025
#define IDC_EDIT_VALUE                  1026
#define IDC_SCROLLBAR_FIELDS            1027
#define IDC_TIME                        1028
#define IDC_DATE                        1029
#define IDC_TXT_SEARCH_IN               1030
#define IDC_GROUP_TIME                  1031
#define IDC_TXT_ELAPSED                 1032
#define IDC_ELAPSED                     1033
#define IDC_GRP_FIELDS                  1034
#define IDC_GRP_DRIVE                   1035
#define IDC_LISTE                       1036
#define IDC_TXT_DESTINATION             1037
#define IDC_COMBO_DESTINATION           1038
#define IDC_STATIC_TYPE                 1039
#define IDC_TXT_TYPE                    1040
#define IDC_STATIC_FREE                 1041
#define IDC_TXT_MB_FREE                 1042
#define IDC_STATIC_MB                   1043
#define IDC_ARCHIV_INFO_LISTE           1044
#define IDC_TXT_BANK                    1045
#define IDC_STATIC_SELECTED             1046
#define IDC_EDIT_NAME                   1047
#define IDC_TXT_SELECTED_MB             1048
#define IDC_STATIC_MB2                  1049
#define IDC_GRP_BACKUP                  1050
#define IDC_TXT0                        1051
#define IDC_TXT_SIZE                    1052
#define IDC_SIZE_MB                     1053
#define IDC_TXT_TIME                    1054
#define IDC_TIME_S                      1055
#define IDC_TXT_VELOCITY                1056
#define IDC_VELOCITY_KBS                1057
#define IDC_CLOSE                       1058
#define IDC_STATIC_SEQUENCES            1059
#define IDC_STATIC_PROGRESS             1060
#define IDC_LIST_SEQUENCES              1061
#define IDC_STATIC_STATE                1062
#define IDC_TXT_STATE                   1063
#define IDC_STATIC_NAME                 1064
#define IDC_EDIT_BACKUP_NAME            1065
#define IDC_CDR                         1066
#define IDC_STATIC_ARCHIVE              1067
#define IDC_LIST_ARCHIVES               1068
#define IDC_CAMERA                      1069
#define IDC_RESOLUTION                  1070
#define IDC_COMBO_CAMERA                1071
#define IDC_RICHEDIT_DATA               1072
#define IDC_TXT_COPIED                  1073
#define IDC_COPIED                      1074
#define IDC_TXT_HOST                    1075
#define IDC_HOST                        1077
#define IDC_PROGRESS_CONNECT            1079
#define IDC_PCDATEEND_TEXT              1089
#define IDC_TIMEEND_TEXT                1090
#define IDC_SEARCHAREA                  1093
#define IDC_LIST_ALARM                  1094
#define IDC_CHECK_ACTIVITY              1098
#define IDC_CHECK_1                     1099
#define IDC_CHECK_2                     1100
#define IDC_TXT_DATE                    1101
#define IDC_COMPRESSION                 1103
#define IDC_START_DATE                  1104
#define IDC_TXT_START_DATE              1105
#define IDC_TXT_START_TIME              1106
#define IDC_TXT_END_DATE                1107
#define IDC_TXT_END_TIME                1108
#define IDC_START_TIME                  1109
#define IDC_END_DATE                    1110
#define IDC_END_TIME                    1111
#define IDC_RESET_START_END             1112
#define IDC_CALCULATE_END               1113
#define IDC_CALCULATE_SIZE              1114
#define IDC_GROUP_BACKUP_SPAN           1115
#define IDP_NO_DISK                     10000
#define IDP_DISK_RO                     10001
#define IDP_NO_DISK_SPACE               10002
#define IDP_DISK_WRITTEN                10003
#define IDS_DATABASE_INFO               10004
#define IDS_OPEN                        10005
#define IDS_JPEG                        10006
#define IDS_JPX                         10007
#define IDS_HTML                        10008
#define IDS_SAVE                        10009
#define IDS_DIB                         10010
#define IDS_FIELD_NAME                  10011
#define IDS_FIELD_VALUE                 10012
#define IDS_PICTURE                     10013
#define IDS_PICTURE_TABBED              10014
#define IDP_NO_CONNECTION               10015
#define IDS_LOCAL_SERVER                10016
#define IDS_CAMERA_NR                   10017
#define IDP_NO_CONNECTION_INVALID_PERMISSION 10018
#define IDS_ERROR_ON                    10019
#define IDP_NO_CONNECTION_LINK_MODUL    10020
#define IDP_NO_CONNECTION_SERVER        10021
#define IDP_NO_CONNECTION_RESET         10022
#define IDP_NO_CONNECTION_MAX_CLIENT    10023
#define IDP_NO_CONNECTION_UNKNOWN       10024
#define IDS_CONNECT                     10025
#define IDS_KTO_NR                      10026
#define IDS_ARCHIV_NR                   10027
#define IDS_KAMERA_NR                   10028
#define IDS_REC_DATE                    10029
#define IDS_REC_TIME                    10030
#define IDS_DTP_TIME                    10031
#define IDS_GA_NR                       10032
#define IDS_TA_NR                       10033
#define IDS_BANKLEITZAHL                10034
#define IDS_VALUE                       10035
#define IDS_CURRENCY                    10036
#define IDS_STATION                     10037
#define IDS_CAM_NAME                    10038
#define IDS_DTP_DATE                    10039
#define IDS_PICTURE_NR                  10040
#define IDS_COMMENT                     10041
#define IDS_ARCHIVE                     10042
#define IDS_STATION2                    10043
#define IDS_AND                         10044
#define IDS_ALL_CAMERAS                 10045
#define IDS_RESOLUTION                  10046
#define IDP_DELETE_ARCHIV               10047
#define IDS_SUM                         10048
#define IDS_TOOLTIP_ARCHIV              10049
#define IDS_TOOLTIP_DIB                 10050
#define IDS_NO_BACKUP_3X                10051
#define IDS_CANCEL_BACKUP               10052
#define IDS_DRIVE_FD                    10053
#define IDS_DRIVE_HD                    10054
#define IDS_DRIVE_NET                   10055
#define IDS_DRIVE_CD                    10056
#define IDS_BACKUP_NOT_STARTED          10057
#define IDS_BACKUP_RUNNING              10058
#define IDS_BACKUP_CANCELLED            10059
#define IDS_BACKUP_FINISHED             10060
#define IDS_TITLE_BACKUP                10061
#define IDS_BACKUP_FAILED               10062
#define IDP_BACKUP_INITIALIZE_FAILED    10063
#define IDP_BACKUP_COPY_FAILED          10064
#define IDS_COPY_ROV                    10065
#define IDS_COPY_ROV_DONE               10066
#define IDS_CDR_CHECK                   10067
#define IDS_ASK_CLOSE_CDR               10068
#define IDP_EJECT_DIRECTCD              10069
#define IDS_SEARCH_FROM                 10070
#define IDS_DRIVE                       10071
#define IDS_USEDAS                      10072
#define IDS_USED                        10073
#define IDS_SIZE                        10074
#define IDS_TYP                         10075
#define IDP_ASK_DELETE_ARCHIV           10076
#define IDP_DELETE_SEQUENCE             10077
#define IDS_DBPROP_NR                   10078
#define IDS_DBPROP_FUELL                10079
#define IDS_DBPROP_NAME                 10080
#define IDS_DBPROP_TYP                  10081
#define IDS_DBPROP_MB                   10082
#define IDS_DBPROP_BENUTZT              10083
#define IDS_DBPROP_FREI                 10084
#define IDS_DBPROP_AKTUELL              10085
#define IDS_READ_ERROR                  10086
#define IDP_NO_CONNECTION_INVALID_SERIAL 10087
#define IDS_TIME                        10088
#define IDS_ALARM_LIST_PRINT_TITLE      10089
#define IDS_ALARM_LIST_PRINT_PAGE       10090
#define IDS_BACKUP_CALCULATING          10091
#define IDP_BACKUP_ASK_FOR_CONTINUATION 10092
#define IDP_DELETE_DATE_SEQUENCES       10093
#define IDP_FILE_OVERWRITE              10094
#define IDS_MEDIUM_CD_R                 10095
#define IDS_MEDIUM_CD_RW                10096
#define IDS_MEDIUM_DVD_ROM              10097
#define IDS_MEDIUM_DVD_RAM              10098
#define IDS_MEDIUM_DVD_R                10099
#define IDS_MEDIUM_DVD_RW               10100
#define IDS_TEMP_BACKUP_RUNNING         10101
#define IDP_DELETE_CDRW                 10102
#define IDP_MULTISESSION_NOT_POSSIBLE   10103
#define IDS_CLEAN_RW                    10104
#define IDS_NO_MEDIUM_FOUND             10105
#define IDS_MEDIUM_CD_ROM               10106
#define IDS_DRIVE_DVD_RAM               10107
#define IDS_WRITE_FAILED                10108
#define IDS_BACKUP                      10109
#define IDS_BACKUP_REMOTE               10110
#define IDS_BACKUP_DRIVE_REMOTE         10111
#define IDS_AUDIO_BUSY                  10112
#define IDS_MAP                         10113
#define IDS_DBD_CSID                    10114
#define IDS_DBD_FINM                    10115
#define IDS_DBD_LANM                    10116
#define IDS_DBD_PRID                    10117
#define IDS_DBD_BXID                    10118
#define IDS_WAIT_FOR_IMAGE              10119
#define IDP_NOTHING_TO_BACKUP           10120
#define IDP_ERROR                       10121
#define IDP_NO_HOST                     10122
#define IDS_DATE                        10123
#define ID_VIEW_FULLSCREEN              32771
#define ID_DISCONNECT                   32772
#define ID_CONNECT                      32773
#define ID_CONNECT_LOCAL                32774
#define ID_NEW_LOGIN                    32775
#define ID_SEARCH                       32776
#define ID_NAVIGATE_POS1                32777
#define ID_NAVIGATE_END                 32778
#define ID_NAVIGATE_NEXT                32779
#define ID_NAVIGATE_PREV                32780
#define ID_NAVIGATE_REVIEW              32781
#define ID_NAVIGATE_FORWARD             32782
#define ID_VIEW_1                       32783
#define ID_NAVIGATE_STOP                32784
#define ID_VIEW_2_2                     32785
#define ID_VIEW_3_3                     32786
#define ID_VIEW_4_4                     32787
#define ID_SMALL_CLOSE                  32788
#define ID_SMALL_CONTEXT                32789
#define ID_SEQUENCE_OPEN                32790
#define ID_ARCHIV_DELETE                32791
#define ID_DELETE                       32792
#define ID_VIEW_ORIGINAL                32793
#define ID_HTML_PREV                    32793
#define ID_EDIT_STATION                 32794
#define ID_HTML_NEXT                    32794
#define ID_EDIT_COMMENT                 32795
#define ID_FILE_HTML                    32796
#define ID_FILE_JPG                     32797
#define ID_FILE_DIB                     32798
#define ID_FILE_JPX                     32799
#define ID_FILE_DISK                    32800
#define ID_ARCHIV_EMPTY                 32801
#define ID_DISPLAY_1                    32802
#define ID_DISPLAY_4                    32803
#define ID_DISPLAY_9                    32804
#define ID_VIEW_TOGGLE                  32805
#define ID_FILE_OPEN_DISK               32806
#define ID_DATABASE_INFO                32807
#define ID_DISPLAY_ZOOM_OUT             32808
#define ID_ARCHIV_BACKUP                32809
#define ID_SMALL_CLOSE_ALL              32810
#define ID_PROGRESS                     32811
#define ID_PROGRESS_TEXT                32812
#define ID_VIDEO_FULLSCREEN             32813
#define ID_SEQUENCE_OPEN_SINGLE         32814
#define ID_SEARCH_AT_START              32815
#define ID_SEARCH_RECTANGLE             32816
#define ID_SEARCH_RECTANGLE_DELETE      32818
#define ID_NAVIGATE_SKIP_FORWARD        32820
#define ID_NAVIGATE_FAST_FORWARD        32821
#define ID_NAVIGATE_FAST_BACK           32822
#define ID_NAVIGATE_SKIP_BACK           32823
#define ID_CONNECT_MAP                  32824
#define ID_SYNC_BACK                    32825
#define ID_SYNC_STEP_BACK               32826
#define ID_SYNC_STOP                    32827
#define ID_SYNC_STEP_FORWARD            32828
#define ID_SYNC_FORWARD                 32829
#define ID_SYNC_EJECT                   32830
#define ID_SYNC                         32831
#define ID_SEQUENCE_OVER                32832
#define ID_DATE_SEQUENCES_DELETE        32833
#define ID_SEQUENZ_REALTIME             32835
#define ID_SEQUENCE_REALTIME            32836
#define ID_VIEW_TARGET_DISPLAY          32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
