//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProductView.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PRODUCTVIEW_DIALOG          102
#define IDP_ISDN_OR_SOCKET              102
#define IDD_ERROR_DIALOG                103
#define IDP_BOX                         103
#define IDP_CRYPT_WRONG                 104
#define IDS_CRYPT_OK                    105
#define IDS_CRYPT_ERROR                 106
#define IDP_SERIAL_DIFFERENT            107
#define IDS_OEM_ERROR                   108
#define IDP_NO_VALID_PRODUCT            109
#define IDR_MAINFRAME                   128
#define IDD_PIN                         135
#define IDC_PRODUCT_NAME                1001
#define IDC_TXT_PRODUCT                 1002
#define IDC_RUN_BASE                    1003
#define IDC_TXT_BASE                    1003
#define IDC_RUN_CODECS                  1004
#define IDC_RUN_COCO                    1005
#define IDC_RUN_QUNIT                   1005
#define IDC_RUN_MICO                    1006
#define IDC_RUN_IP_UNIT                 1006
#define IDC_TXT_PRODUCT_VERSION         1007
#define IDC_TXT_DATABASE_MODULES        1009
#define IDC_TXT_FULL_PRODUCT_Name       1009
#define IDC_RUN_DATABASE_SERVER         1010
#define IDC_TXT_FULL_VERSION            1010
#define IDC_RUN_DATABASE_CLIENT         1011
#define IDC_TXT_SERIAL                  1011
#define IDC_RUN_CDR_WRITER              1012
#define IDC_TXT_LINK_MODULES            1013
#define IDC_RUN_ISDN_UNIT               1014
#define IDC_RUN_SOCKET_UNIT             1015
#define IDC_RUN_VCS_UNIT                1016
#define IDC_RUN_PRESENCE_UNIT           1017
#define IDC_RUN_SERVER                  1018
#define IDC_RUN_VISION                  1019
#define IDC_TXT_OPTIONAL_MODULES        1020
#define IDC_RUN_AKU_UNIT                1021
#define IDC_RUN_COMM_UNIT               1022
#define IDC_RUN_SDI_UNIT                1023
#define IDC_RUN_GAA_UNIT                1024
#define IDC_RUN_SIM_UNIT                1025
#define IDC_TXT_FUNCTIONALITIES         1026
#define IDC_DO_SAVE                     1027
#define IDC_STATIC_ICON                 1028
#define IDC_RUN_SDI_CONFIG              1029
#define IDC_ALLOW_SOFT_DECODE_MICO      1030
#define IDC_RUN_ANALYZER                1031
#define IDC_OEM_CODE                    1032
#define IDC_TXT_BOX_MODULES             1033
#define IDC_TXT_ERROR_INFO              1034
#define IDC_TXT_ERROR_MSG               1035
#define IDC_ALLOW_INTERNAL_ACCESS       1036
#define IDC_ALLOW_MULTI_MONITOR         1037
#define IDC_ALLOW_LOCAL_STORAGE_PROCESSES 1038
#define IDC_ERROR_INSTRUCTION           1039
#define IDC_TXT_ERROR_MSG_HEAD          1040
#define IDC_SERIAL                      1041
#define IDC_ALLOW_HTML_NOTIFICATION     1042
#define IDC_RUN_AUDIO_UNIT              1043
#define IDC_ALLOW_HTML_INFORMATION      1044
#define IDC_ALLOW_HTML_INFORMATION2     1045
#define IDC_ALLOW_SDI_GA                1046
#define IDC_ALLOW_ROUTING               1047
#define IDC_RUN_MICO2                   1048
#define IDC_ALLOW_SOFT_DECODE_COCO      1049
#define IDC_RUN_ISDN_UNIT2              1050
#define IDC_ALLOW_SDI_ACCESS_CONTROL    1051
#define IDC_ALLOW_SDI_INDUSTRIAL        1052
#define IDC_RUN_PRESENCE_UNIT2          1053
#define IDC_ALLOW_SOFT_DECODE_PT        1054
#define IDC_RUN_MICO3                   1055
#define IDC_RUN_MICO4                   1056
#define IDC_RUN_SMS                     1057
#define IDC_RUN_JACOB1                  1058
#define IDC_RUN_JACOB2                  1059
#define IDC_RUN_JACOB3                  1060
#define IDC_RUN_JACOB4                  1061
#define IDC_RUN_GEMOS_UNIT              1062
#define IDC_ALLOW_MOTION_DETECTION      1063
#define IDC_RUN_EMAIL_UNIT              1064
#define IDC_RUN_FAX_UNIT                1065
#define IDC_RUN_HTTP                    1066
#define IDC_RUN_TOBS_UNIT               1067
#define IDC_CRYPT                       1068
#define IDC_PIN                         1069
#define IDC_ALLOW_SDI_PARK_MANAGMENT    1069
#define IDC_ALLOW_TIMERS                1070
#define IDC_EDIT_HDD1                   1071
#define IDC_RADIO_HDD                   1072
#define IDC_EDIT_HDD2                   1073
#define IDC_HDD_ID2                     1074
#define IDC_TXT_PIN                     1075
#define IDC_ALLOW_HTML_MAPS             1076
#define IDC_RESTRICTED_TO_8_CAMERAS_PER_BOARD 1077
#define IDC_ALL_PRODUCTS                1078
#define IDC_STATIC_LINE                 1079
#define IDC_RUN_SAVIC1                  1080
#define IDC_RUN_SAVIC2                  1081
#define IDC_RUN_SAVIC3                  1082
#define IDC_RUN_SAVIC4                  1083
#define IDC_RUN_ICPCON_UNIT             1084
#define IDC_RUN_USB_CAMERA              1085
#define IDC_RADIO_SERIAL                1086
#define IDC_EDIT_SERIAL                 1087
#define IDC_RUN_TASHA1                  1088
#define IDC_RUN_TASHA2                  1089
#define IDC_RUN_TASHA3                  1090
#define IDC_RUN_SAVIC8                  1091
#define IDC_RUN_TASHA4                  1091
#define IDC_EDT_NO_OF_HOSTS             1092
#define IDC_SPIN_NO_OF_HOSTS            1093
#define IDC_TXT_NO_OF_HOSTS             1094
#define IDC_TXT_NO_OF_HOSTS1            1094
#define IDC_TXT_NO_OF_HOSTS2            1095
#define IDC_COMBO1                      1096
#define IDC_COMBO_NR_CAMERAS            1096
#define IDC_STATIC_NR_CAMERAS           1097
#define IDC_STATIC_NR_IP_CAMERAS        1098
#define IDC_COMBO_NR_CAMERAS2           1099
#define IDC_COMBO_NR_IP_CAMERAS         1099
#define ID_HIDDEN_WRITE                 32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
