/////////////////////////////////////////////////////////////////////////////
// PROJECT:		CoCoUnit
// FILE:		$Workfile: message.h $
// ARCHIVE:		$Archive: /Project/Units/CoCoUnit/message.h $
// CHECKIN:		$Date: 5.08.98 9:43 $
// VERSION:		$Revision: 5 $
// LAST CHANGE:	$Modtime: 5.08.98 9:43 $
// BY AUTHOR:	$Author: Martin $
// $Nokeywords:$
//////////////////////////////////////////////////////////////////////

#ifndef __MESSAGE_H__
#define __MESSAGE_H__
#include "wk_msg.h"

// Messages zur Steuerung der CoCo ISA
#define COCO_OPEN						COCO_MSGBASE + 1
#define COCO_CLOSE						COCO_MSGBASE + 2
#define COCO_GET_VERSION	   			COCO_MSGBASE + 3
#define COCO_GET_LAST_ERROR				COCO_MSGBASE + 4
#define COCO_CHECK_HARDWARE				COCO_MSGBASE + 5
#define COCO_GET_STATE					COCO_MSGBASE + 6
#define COCO_SET_INPUT_SOURCE   		COCO_MSGBASE + 7
#define COCO_GET_INPUT_SOURCE   		COCO_MSGBASE + 8

#define COCO_SET_FE_VIDEO_FORMAT 	    COCO_MSGBASE + 9
#define COCO_SET_FE_SOURCE_TYPE			COCO_MSGBASE + 10
#define COCO_SET_BE_VIDEO_FORMAT 	    COCO_MSGBASE + 11
#define COCO_SET_BE_VIDEO_TYPE			COCO_MSGBASE + 12
#define COCO_SET_FE_BRIGHTNESS          COCO_MSGBASE + 13
#define COCO_SET_FE_CONTRAST			COCO_MSGBASE + 14
#define COCO_SET_FE_SATURATION			COCO_MSGBASE + 15
#define COCO_SET_FE_HUE					COCO_MSGBASE + 16
#define COCO_SET_FE_HSCALE				COCO_MSGBASE + 17
#define COCO_SET_FE_VSCALE				COCO_MSGBASE + 18
#define COCO_SET_FE_FILTER				COCO_MSGBASE + 19
#define COCO_DLG_LUMINANCE				COCO_MSGBASE + 20

#define COCO_GET_CURRENT_ALARM_STATUS   COCO_MSGBASE + 21
#define	COCO_GET_ALARM_STATUS           COCO_MSGBASE + 22
#define	COCO_SET_ALARM_EDGE             COCO_MSGBASE + 23
#define	COCO_SET_ALARM_ACK              COCO_MSGBASE + 24
#define COCO_SET_RELAIS					COCO_MSGBASE + 25
#define COCO_EXECUTE_MCI_SCRIPT			COCO_MSGBASE + 26

#define COCO_REQUEST_DATA				COCO_MSGBASE + 27
#define COCO_ENC_START					COCO_MSGBASE + 28
#define COCO_ENC_STOP					COCO_MSGBASE + 29
#define COCO_ENC_BREAK					COCO_MSGBASE + 30

#define COCO_ENC_SET_FORMAT				COCO_MSGBASE + 31
#define COCO_ENC_SET_FRAMERATE			COCO_MSGBASE + 32
#define COCO_ENC_SET_BITRATE			COCO_MSGBASE + 33
#define COCO_ENC_SET_MODE				COCO_MSGBASE + 34
														
#define COCO_DEC_START					COCO_MSGBASE + 35
#define COCO_DEC_STOP					COCO_MSGBASE + 36
#define COCO_DEC_BREAK					COCO_MSGBASE + 37
#define COCO_DEC_SET_BITRATE			COCO_MSGBASE + 38

#define COCO_CONNECT_OUTPUT				COCO_MSGBASE + 39
#define COCO_GET_RELAIS					COCO_MSGBASE + 40

#define COCO_ENC_GET_STATE				COCO_MSGBASE + 41
#define COCO_DEC_GET_STATE				COCO_MSGBASE + 42

// Messages, an die Applikation 						
#define	WM_COCO_CHANGED_SOURCE		 	COCO_MSGBASE + 50
#define	WM_COCO_CHANGED_FE_SOURCE_TYPE  COCO_MSGBASE + 51
#define	WM_COCO_CHANGED_FE_VIDEO_FORMAT COCO_MSGBASE + 52
#define	WM_COCO_CHANGED_FE_BRIGHTNESS   COCO_MSGBASE + 53
#define	WM_COCO_CHANGED_FE_CONTRAST     COCO_MSGBASE + 54
#define	WM_COCO_CHANGED_FE_SATURATION   COCO_MSGBASE + 55
#define	WM_COCO_CHANGED_FE_HUE		    COCO_MSGBASE + 56
#define WM_COCO_CHANGED_FE_HSCALE		COCO_MSGBASE + 57
#define WM_COCO_CHANGED_FE_VSCALE		COCO_MSGBASE + 58
#define WM_COCO_CHANGED_FE_FILTER		COCO_MSGBASE + 59
#define WM_COCO_CHANGED_ALARM_ACK		COCO_MSGBASE + 60
#define WM_COCO_CHANGED_ALARM_EDGE		COCO_MSGBASE + 61
#define WM_COCO_CHANGED_BE_VIDEO_FORMAT	COCO_MSGBASE + 62
#define WM_COCO_CHANGED_BE_VIDEO_TYPE	COCO_MSGBASE + 63
#define WM_COCO_CHANGED_RELAIS			COCO_MSGBASE + 64
#define WM_COCO_CHANGED_ENC_FORMAT		COCO_MSGBASE + 65
#define WM_COCO_CHANGED_ENC_FRAMERATE	COCO_MSGBASE + 66
#define WM_COCO_CHANGED_ENC_BITRATE		COCO_MSGBASE + 67
#define WM_COCO_CHANGED_DEC_BITRATE		COCO_MSGBASE + 68

#define WM_COCO_ALARM					COCO_MSGBASE + 69
#define WM_COCO_DEC_START				COCO_MSGBASE + 70
#define WM_COCO_DEC_STOP				COCO_MSGBASE + 71
#define WM_COCO_ENC_START				COCO_MSGBASE + 72
#define WM_COCO_ENC_STOP				COCO_MSGBASE + 73
#define WM_COCO_SLEEP					COCO_MSGBASE + 74


#endif // __MESSAGE_H__
