//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CoCoUnit.rc
//
#define ID_ABOUT                        101
#define IDD_DLG_COLOR                   103
#define IDD_COCOAPP_DIALOG              104
#define IDR_COCOUNIT                    130
#define IDD_SETTINGS                    131
#define IDD_LOGIN                       132
#define IDR_MAINFRAME                   134
#define IDC_USER_ID                     1000
#define IDC_PASSWORD                    1001
#define IDC_SOURCE1                     1002
#define IDC_SOURCE2                     1003
#define IDC_SOURCE3                     1004
#define IDC_SOURCE4                     1005
#define IDC_SOURCE5                     1006
#define IDC_SOURCE6                     1007
#define IDC_SOURCE7                     1008
#define IDC_SOURCE8                     1009
#define IDC_EXTCARD0                    1010
#define IDC_EXTCARD1                    1011
#define IDC_EXTCARD2                    1012
#define IDC_EXTCARD3                    1013
#define IDC_FE_PAL                      1014
#define IDC_FE_SECAM                    1015
#define IDC_FE_NTSC                     1016
#define IDC_FE_FBAS                     1017
#define IDC_FE_SVHS                     1018
#define IDC_BE_PAL                      1019
#define IDC_BE_SECAM                    1020
#define IDC_BE_NTSC                     1021
#define IDC_DLG_SETTINGS                1022
#define IDC_SEND                        1023
#define IDC_SEND_DATA                   1024
#define IDC_RECEIVE_DATA                1025
#define IDC_EXTCARDMEGRA                1026
#define IDC_BE_COMPOSITE                1027
#define IDC_BE_RGB                      1028
#define IDC_FE_LNOTCH                   1029
#define IDC_FE_LDEC                     1030
#define IDC_EDGE7                       1031
#define IDC_EDGE6                       1032
#define IDC_EDGE5                       1033
#define IDC_EDGE4                       1034
#define IDC_EDGE3                       1035
#define IDC_EDGE2                       1036
#define IDC_EDGE1                       1037
#define IDC_EDGE0                       1038
#define IDC_ACK7                        1039
#define IDC_ACK6                        1040
#define IDC_ACK5                        1041
#define IDC_ACK4                        1042
#define IDC_ACK3                        1043
#define IDC_ACK2                        1044
#define IDC_ACK1                        1045
#define IDC_ACK0                        1046
#define IDC_RELAIS3                     1047
#define IDC_RELAIS2                     1048
#define IDC_RELAIS1                     1049
#define IDC_RELAIS0                     1050
#define IDC_EDIT_SEND_MCI               1051
#define IDC_SEND_MCI                    1052
#define IDC_SEND_SCRIPT                 1053
#define IDC_COCOID0                     1054
#define IDC_COCOID1                     1055
#define IDC_COCOID2                     1056
#define IDC_COCOID3                     1057
#define IDC_TR_DATA                     1058
#define IDC_RE_DATA                     1059
#define IDC_TR_SPEED                    1060
#define IDC_RE_SPEED                    1061
#define IDC_DEC_START                   1062
#define IDC_DEC_STOP                    1063
#define IDC_ENC_START                   1064
#define IDC_ENC_STOP                    1065
#define IDC_TEST                        1066
#define IDC_DEC_BITRATE                 1067
#define IDC_ENC_BITRATE                 1068
#define IDC_SET_DEC_BITRATE             1069
#define IDC_SET_ENC_BITRATE             1070
#define IDC_LUM                         1071
#define IDC_POSITION                    1072
#define IDC_ACQUISITION                 1073
#define IDC_DELAYS                      1074
#define IDC_PLL                         1075
#define IDC_QCIF                        1076
#define IDC_CIF                         1077
#define IDC_COMPRESS_1                  1078
#define IDC_COMPRESS_2                  1079
#define IDC_COMPRESS_3                  1080
#define IDC_COMPRESS_4                  1081
#define IDC_COMPRESS_5                  1082
#define IDC_SBRIGHTNESS                 1083
#define IDC_VCONTRAST                   1084
#define IDC_SCONTRAST                   1085
#define IDC_SSATURATION                 1086
#define IDC_VSATURATION                 1087
#define IDC_VBRIGHTNESS                 1088
#define IDC_UEBERNAHME                  1089
#define IDC_SHUE                        1090
#define IDC_VHUE                        1091
#define IDC_STATIC_NAME_PW              1092
#define IDC_STATIC_NAME                 1093
#define IDC_STATIC_PW                   1094
#define IDC_STATIC_BRIGHTNESS           1095
#define IDC_STATIC_CONTRAST             1096
#define IDC_STATIC_SATURATION           1097
#define IDC_STATIC_HUE                  1098
#define IDC_GROUP_COCOID                1099
#define IDC_GROUP_EXTENSIONCARD         1100
#define IDC_GROUP_VIDEOSOURCE           1101
#define IDC_GROUP_VIDEOFRONTEND         1102
#define IDC_GROUP_VIDEOBACKEND          1103
#define IDC_GROUP_SOURCETYPE            1104
#define IDC_TXT_DECODER                 1105
#define IDC_TXT_ENCODER                 1106
#define IDC_TXT_BIT2                    1107
#define IDC_TXT_BIT1                    1108
#define IDC_TXT_EDGE                    1109
#define IDC_TXT_ACK                     1110
#define IDC_TXT_RELAIS                  1111
#define IDC_GROUP_FORMAT                1112
#define IDC_GROUP_COMPRESSION           1113
#define ID_SETTINGS                     59142
#define IDP_LOGIN_FAILED                59143
#define IDS_RTE_RUN_COCOUNIT            59144
#define IDS_RTE_ALLOW_HARDDECODE_COCO   59145
#define IDS_RTE_COCOSRV_OPEN            59146
#define IDS_RTE_MCI_SCRIPT              59147
#define IDS_RTE_LOAD_SERVER             59148
#define IDS_RTE_LOAD_SERVER_TIMEOUT     59149
#define IDS_RTE_MEGRA_INIT              59151

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
