//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UpdateHandler.rc
//
#define IDR_MAINFRAME                   1
#define IDD_ABOUTBOX                    100
#define IDS_NAME                        100
#define IDD_CONNECTION                  101
#define IDS_SIZE                        101
#define IDD_RECEIVE                     102
#define IDS_TYP                         102
#define IDD_SEND                        103
#define IDS_TIME                        103
#define ID_PROGRESS                     104
#define IDP_NO_CONNECTION               105
#define IDS_VALUE                       106
#define IDD_DELETE                      131
#define IDD_EXECUTE                     132
#define IDB_SYMBOL                      133
#define IDD_TITLE_BAR                   134
#define IDR_UPDATE                      137
#define IDD_SETTINGS                    140
#define IDD_SYSTEMINFO                  141
#define IDR_CONTEXT                     146
#define IDD_SERVICE                     147
#define IDD_SETUP                       150
#define IDD_CMD_LINE_PARAMS             151
#define IDC_EDIT_FILE_SOURCE            1000
#define IDC_RADIO_APPDIR                1001
#define IDC_RADIO_ROOT                  1002
#define IDC_REMOTE                      1003
#define IDC_RADIO_WINDOWS               1003
#define IDC_RADIO_SYSTEM                1004
#define IDC_RADIO_FULL                  1005
#define IDC_STATIC_DESTINATION          1006
#define IDC_SAVE                        1007
#define IDC_STATIC_SOURCE               1008
#define IDC_OPEN                        1009
#define IDC_CHECK_REBOOT                1010
#define IDC_NAME                        1013
#define IDC_HOST                        1014
#define IDC_STATIC_HOST                 1015
#define IDC_PASSWORD                    1016
#define IDC_DIRECTORY                   1017
#define IDC_FILES                       1018
#define IDC_REPORT                      1019
#define IDC_CHECK_DISCONNECT            1020
#define IDC_CHECK_ONLY_EXISTING         1021
#define IDC_TXT_PROZESSOR               1027
#define IDC_TXT_OSVERSION               1031
#define IDC_TXT_MEMORY                  1032
#define IDC_TXT_SOFTWARE                1033
#define IDC_EDIT_SERVICE                1034
#define IDC_RADIO_UPDATE                1035
#define IDC_RADIO_EXECUTE               1036
#define IDC_ADD                         1038
#define IDC_DELETE                      1039
#define IDC_TXT_VERSION                 1040
#define IDC_EDIT_VERSION                1041
#define IDC_TXT_SEND                    1042
#define IDC_LIST_SEND                   1043
#define IDC_TXT_SENT                    1044
#define IDC_LIST_CONFIRMED              1045
#define IDC_BUTTON_SEND                 1046
#define IDC_BUTTON_UPDATE               1047
#define IDC_TXT_FILE                    1048
#define IDC_PROGRESS_SEND               1049
#define IDC_EDIT_CMD_LINE_PARAMS        1051
#define IDC_EDT_WAIT_TIME               1052
#define IDC_TXT_WAIT_TIME               1053
#define ID_DIRECTORY                    20000
#define ID_FILES                        20001
#define ID_ACTIONS                      20002
#define ID_HOST                         20003
#define ID_VERBINDEN                    32771
#define ID_TRENNEN                      32772
#define ID_CONNECTION                   32773
#define ID_FILE_RECEIVE                 32774
#define ID_FILE_SEND                    32775
#define IDS_OPENFILE                    32776
#define IDS_READFILE                    32777
#define IDS_SENDFILE                    32778
#define IDS_NO_OPENFILE                 32779
#define IDS_NO_READFILE                 32780
#define IDS_RECEIVEFILE                 32781
#define ID_MESSAGE_STRING               32782
#define IDS_SAVEFILE                    32782
#define IDS_FILESAVED                   32783
#define ID_FILE_DELETE                  32783
#define ID_FILE_EXECUTE                 32784
#define IDS_DELETEFILE                  32784
#define IDS_DELETEDFILE                 32785
#define IDS_EXECUTEFILE                 32786
#define ID_UPDATE_SOURCE                32786
#define IDS_EXECUTEDFILE                32787
#define ID_UPDATE_LAUNCHER              32787
#define ID_UPDATE_EXPLORER              32788
#define ID_UPDATE_PH                    32789
#define ID_UPDATE_SERVER                32790
#define ID_UPDATE_SV                    32791
#define ID_UPDATE_ISDN                  32792
#define ID_UPDATE_TCPIP                 32793
#define ID_UPDATE_DBS                   32794
#define ID_UPDATE_SWCODEC               32795
#define ID_UPDATE_COCO                  32796
#define ID_UPDATE_MICO                  32797
#define ID_UPDATE_AKU                   32798
#define ID_UPDATE_SIM                   32799
#define ID_UPDATE_GAUNIT                32800
#define ID_UPDATE_COMM                  32801
#define ID_UPDATE_FILE                  32802
#define ID_UPDATE_HELP                  32803
#define ID_UPDATE_COMPLETE              32804
#define ID_FILE_PROPERTIES              32805
#define ID_OPTIONS_CLEAR_REPORT         32814
#define ID_OPTIONS_SETTINGS             32815
#define ID_FILE_SYSTEM_INFO             32817
#define ID_FILE_REGEXPORT               32818
#define ID_INFO_TIME                    32819
#define ID_UPDATE_SECANA                32820
#define ID_UPDATE_REBOOT                32821
#define ID_UPDATE_SOURCE_GARNY          32822
#define ID_UPDATE_ZIEL                  32823
#define ID_UPDATE_DISK                  32825
#define ID_UPDATE_SDIUNIT               32826
#define ID_UPDATE_SOCKET                32827
#define ID_CONNECT_LOCAL                32828
#define ID_SETUP                        32830
#define ID_CONNECTION_RESET             32832
#define IDS_EXECUTE_CMD_LINE            32833
#define ID_FILE_EXECUTE_CMD_LINE        32834
#define ID_OPTION_PARTIAL_TRANSMISSION  32835
#define ID_FILE_FETCH_CMD_FILE          32836
#define ID_REG_EDIT                     32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
